import { mutation } from './_generated/server';

import { ensureTemplateData, validateTemplateData } from './templateData';

export const seedQuick = mutation({
    args: {},
    handler: async (ctx) => {
        const now = Date.now();
        const samples = [
            {
                slug: 'popular-minimal-promo',
                title: 'Minimal Promo',
                category: 'popular',
                description: 'Clean social promo with headline, subhead, and CTA.',
                tags: ['promo', 'instagram', 'minimal'],
                isFeatured: true,
                thumbnailUrl: 'https://images.unsplash.com/photo-1524995997946-a1c2e315a42f?auto=format&fit=crop&w=1200&q=80',
                canvas: { width: 1080, height: 1080 },
                background: '#ffffff',
                elements: [
                    {
                        id: 'promo-bg',
                        type: 'rect',
                        name: 'Accent block',
                        position: { x: 80, y: 140 },
                        size: { width: 920, height: 460 },
                        fill: { type: 'solid', color: '#EEF2FF' },
                        rotation: 0,
                    },
                    {
                        id: 'promo-title',
                        type: 'text',
                        text: 'Weekend Sale',
                        fontFamily: 'Inter',
                        fontSize: 76,
                        position: { x: 120, y: 180 },
                        size: { width: 820, height: 100 },
                        color: '#111827',
                    },
                    {
                        id: 'promo-sub',
                        type: 'text',
                        text: 'Up to 40% off selected items',
                        fontFamily: 'Inter',
                        fontSize: 48,
                        position: { x: 120, y: 290 },
                        size: { width: 720, height: 72 },
                        color: '#4F46E5',
                    },
                    {
                        id: 'promo-cta',
                        type: 'text',
                        text: 'Shop now →',
                        fontFamily: 'Inter',
                        fontSize: 32,
                        position: { x: 120, y: 380 },
                        size: { width: 320, height: 56 },
                        color: '#111827',
                    },
                ],
            },
            {
                slug: 'biz-pitch-deck-clean',
                title: 'Pitch Deck – Clean',
                category: 'business',
                description: 'Corporate cover slide with hero title and accent band.',
                tags: ['deck', 'presentation'],
                isFeatured: true,
                thumbnailUrl: 'https://images.unsplash.com/photo-1521737604893-d14cc237f11d?auto=format&fit=crop&w=1400&q=80',
                canvas: { width: 1920, height: 1080 },
                background: '#ffffff',
                elements: [
                    {
                        id: 'cover-band',
                        type: 'rect',
                        position: { x: 0, y: 940 },
                        size: { width: 1920, height: 140 },
                        fill: { type: 'solid', color: '#EEF2FF' },
                    },
                    {
                        id: 'cover-title',
                        type: 'text',
                        text: 'Company Pitch Deck',
                        fontFamily: 'Inter',
                        fontSize: 96,
                        position: { x: 160, y: 200 },
                        size: { width: 1500, height: 120 },
                        color: '#0F172A',
                    },
                    {
                        id: 'cover-sub',
                        type: 'text',
                        text: 'Investor Update • Q4 2025',
                        fontFamily: 'Inter',
                        fontSize: 48,
                        position: { x: 160, y: 340 },
                        size: { width: 1100, height: 80 },
                        color: '#4F46E5',
                    },
                    {
                        id: 'cover-foot',
                        type: 'text',
                        text: 'Prepared by Your Company',
                        fontFamily: 'Inter',
                        fontSize: 28,
                        position: { x: 160, y: 980 },
                        size: { width: 900, height: 44 },
                        color: '#6B7280',
                    },
                ],
            },
            {
                slug: 'enterprise-annual-report',
                title: 'Annual Report Summary',
                category: 'enterprise',
                description: 'Summary spread with highlight band for KPIs.',
                tags: ['report', 'summary'],
                isFeatured: false,
                thumbnailUrl: 'https://images.unsplash.com/photo-1556740749-887f6717d7e4?auto=format&fit=crop&w=1400&q=80',
                canvas: { width: 1920, height: 1080 },
                background: '#ffffff',
                elements: [
                    {
                        id: 'report-band',
                        type: 'rect',
                        position: { x: 120, y: 160 },
                        size: { width: 1680, height: 280 },
                        fill: { type: 'solid', color: '#F8FAFC' },
                    },
                    {
                        id: 'report-title',
                        type: 'text',
                        text: '2025 Annual Report',
                        fontFamily: 'Inter',
                        fontSize: 80,
                        position: { x: 180, y: 200 },
                        size: { width: 1400, height: 96 },
                        color: '#0F172A',
                    },
                    {
                        id: 'report-body',
                        type: 'text',
                        text: 'Executive summary lorem ipsum dolor sit amet, consectetur adipiscing elit. Replace with your narrative and key figures.',
                        fontFamily: 'Inter',
                        fontSize: 32,
                        position: { x: 180, y: 480 },
                        size: { width: 1520, height: 320 },
                        color: '#334155',
                        lineHeight: 1.4,
                    },
                ],
            },
            {
                slug: 'ecom-ig-product-post',
                title: 'E-com Product Post',
                category: 'ecommerce',
                description: 'Product spotlight for social media.',
                tags: ['ecommerce', 'instagram'],
                isFeatured: true,
                thumbnailUrl: 'https://images.unsplash.com/photo-1512496015851-a90fb38ba796?auto=format&fit=crop&w=1200&q=80',
                canvas: { width: 1080, height: 1080 },
                background: '#ffffff',
                elements: [
                    {
                        id: 'product-card',
                        type: 'rect',
                        position: { x: 100, y: 120 },
                        size: { width: 880, height: 520 },
                        fill: { type: 'solid', color: '#F8FAFC' },
                    },
                    {
                        id: 'product-image',
                        type: 'image',
                        src: 'https://images.unsplash.com/photo-1512496015851-a90fb38ba796?auto=format&fit=crop&w=900&q=60',
                        position: { x: 120, y: 140 },
                        size: { width: 420, height: 480 },
                    },
                    {
                        id: 'product-title',
                        type: 'text',
                        text: 'Air Sneakers X2',
                        fontFamily: 'Inter',
                        fontSize: 56,
                        position: { x: 560, y: 180 },
                        size: { width: 360, height: 80 },
                        color: '#111827',
                    },
                    {
                        id: 'product-price',
                        type: 'text',
                        text: '$129.00',
                        fontFamily: 'Inter',
                        fontSize: 48,
                        position: { x: 560, y: 260 },
                        size: { width: 360, height: 72 },
                        color: '#059669',
                    },
                    {
                        id: 'product-cta',
                        type: 'text',
                        text: 'Buy now →',
                        fontFamily: 'Inter',
                        fontSize: 36,
                        position: { x: 560, y: 340 },
                        size: { width: 320, height: 64 },
                        color: '#4F46E5',
                    },
                ],
            },
            {
                slug: 'popular-yt-thumbnail-clean',
                title: 'YouTube Thumbnail – Clean',
                category: 'popular',
                description: 'Bold thumbnail with split layout.',
                tags: ['youtube', 'thumbnail'],
                isFeatured: true,
                thumbnailUrl: 'https://images.unsplash.com/photo-1517430816045-df4b7de11d1d?auto=format&fit=crop&w=1280&q=80',
                canvas: { width: 1280, height: 720 },
                background: '#0B1220',
                elements: [
                    {
                        id: 'thumb-panel',
                        type: 'rect',
                        position: { x: 740, y: 0 },
                        size: { width: 540, height: 720 },
                        fill: { type: 'solid', color: '#111827' },
                    },
                    {
                        id: 'thumb-title',
                        type: 'text',
                        text: 'Design in Minutes',
                        fontFamily: 'Inter',
                        fontSize: 72,
                        position: { x: 80, y: 200 },
                        size: { width: 600, height: 120 },
                        color: '#FFFFFF',
                    },
                    {
                        id: 'thumb-tag',
                        type: 'text',
                        text: 'TUTORIAL',
                        fontFamily: 'Inter',
                        fontSize: 40,
                        position: { x: 80, y: 320 },
                        size: { width: 240, height: 64 },
                        color: '#22D3EE',
                    },
                ],
            },
            {
                slug: 'print-resume-modern',
                title: 'Resume – Modern',
                category: 'business',
                description: 'Single-page resume layout with hero and columns.',
                tags: ['resume', 'print'],
                isFeatured: false,
                thumbnailUrl: 'https://images.unsplash.com/photo-1517245386807-bb43f82c33c4?auto=format&fit=crop&w=900&q=80',
                canvas: { width: 794, height: 1123 },
                background: '#ffffff',
                elements: [
                    {
                        id: 'resume-col',
                        type: 'rect',
                        position: { x: 72, y: 200 },
                        size: { width: 650, height: 840 },
                        fill: { type: 'solid', color: '#F8FAFC' },
                    },
                    {
                        id: 'resume-name',
                        type: 'text',
                        text: 'Alex Carter',
                        fontFamily: 'Inter',
                        fontSize: 42,
                        position: { x: 72, y: 96 },
                        size: { width: 600, height: 64 },
                        color: '#111827',
                    },
                    {
                        id: 'resume-role',
                        type: 'text',
                        text: 'Product Designer',
                        fontFamily: 'Inter',
                        fontSize: 24,
                        position: { x: 72, y: 150 },
                        size: { width: 600, height: 48 },
                        color: '#4B5563',
                    },
                    {
                        id: 'resume-summary',
                        type: 'text',
                        text: 'Summary: Replace with a concise profile that highlights experience, strengths, and goals.',
                        fontFamily: 'Inter',
                        fontSize: 16,
                        position: { x: 96, y: 240 },
                        size: { width: 540, height: 160 },
                        color: '#1F2937',
                        lineHeight: 1.5,
                    },
                ],
            },
        ];

        for (const sample of samples) {
            const existing = await ctx.db
                .query('templates')
                .withIndex('by_slug', (q) => q.eq('slug', sample.slug))
                .first();
            if (existing) continue;

            const data = ensureTemplateData(
                {
                    version: 1,
                    canvas: sample.canvas,
                    background: sample.background,
                    elements: sample.elements,
                },
                { artboardId: `ab-${sample.slug}`, artboardName: sample.title }
            );
            validateTemplateData(data);

            await ctx.db.insert('templates', {
                title: sample.title,
                slug: sample.slug,
                category: sample.category,
                description: sample.description ?? undefined,
                data,
                tags: sample.tags ?? [sample.category],
                isFeatured: sample.isFeatured ?? false,
                isPremium: false,
                thumbnailUrl: sample.thumbnailUrl ?? undefined,
                popularityScore: 0,
                usageCount: 0,
                status: 'active',
                createdAt: now,
                updatedAt: now,
            });
        }

        return 'Seeded sample templates';
    },
});
