export const BUSINESS_ENTERPRISE_TEMPLATES = [
    {
        version: 1,
        title: 'Business Card – Modern Blue',
        slug: 'business-card-modern-blue-1',
        category: 'business',
        tags: ['business card', 'corporate', 'identity'],
        defaultArtboardId: 'canvas-1',
        artboards: [
            {
                id: 'canvas-1',
                size: { width: 1050, height: 600 },
                background: { kind: 'color', value: '#ffffff' },
                layers: [
                    {
                        id: 'left-panel',
                        type: 'shape',
                        shape: 'rect',
                        transform: { x: 0, y: 0, width: 350, height: 600, rotation: 0 },
                        fill: { kind: 'solid', color: '#1d4ed8' },
                        opacity: 1,
                        zIndex: 0,
                    },
                    {
                        id: 'logo',
                        type: 'image',
                        src: 'https://images.unsplash.com/photo-1606813902912-5e6e4e9e3a43?w=400',
                        transform: { x: 120, y: 230, width: 110, height: 110, rotation: 0 },
                        fit: 'cover',
                        flip: { horizontal: false, vertical: false },
                        filters: { contrast: 0, brightness: 0, saturation: 0, blur: 0 },
                        opacity: 1,
                        zIndex: 1,
                    },
                    {
                        id: 'name',
                        type: 'text',
                        content: 'Jane Doe',
                        transform: { x: 400, y: 150, width: 600, height: 80, rotation: 0 },
                        fontFamily: 'Inter, sans-serif',
                        fontSize: 48,
                        fontWeight: 700,
                        fill: '#1e293b',
                        align: 'left',
                        opacity: 1,
                        zIndex: 2,
                    },
                    {
                        id: 'title',
                        type: 'text',
                        content: 'Creative Director',
                        transform: { x: 400, y: 230, width: 600, height: 50, rotation: 0 },
                        fontFamily: 'Inter, sans-serif',
                        fontSize: 28,
                        fontWeight: 500,
                        fill: '#64748b',
                        align: 'left',
                        opacity: 1,
                        zIndex: 3,
                    },
                    {
                        id: 'email',
                        type: 'text',
                        content: 'jane@studio.com',
                        transform: { x: 400, y: 350, width: 600, height: 40, rotation: 0 },
                        fontFamily: 'Inter, sans-serif',
                        fontSize: 22,
                        fill: '#475569',
                        align: 'left',
                        opacity: 1,
                        zIndex: 4,
                    },
                ],
            },
        ],
        editableData: {
            name: 'Jane Doe',
            title: 'Creative Director',
            email: 'jane@studio.com',
            panelColor: '#1d4ed8',
            accentColor: '#1e293b',
        },
    },
    {
        version: 1,
        title: 'Business Proposal – Gradient Header',
        slug: 'business-proposal-gradient-1',
        category: 'business',
        tags: ['proposal', 'document', 'presentation'],
        defaultArtboardId: 'canvas-1',
        artboards: [
            {
                id: 'canvas-1',
                size: { width: 1080, height: 1528 },
                background: { kind: 'color', value: '#ffffff' },
                layers: [
                    {
                        id: 'header-bg',
                        type: 'shape',
                        shape: 'rect',
                        transform: { x: 0, y: 0, width: 1080, height: 280, rotation: 0 },
                        fill: {
                            kind: 'gradient',
                            gradient: {
                                type: 'linear',
                                angle: 135,
                                stops: [
                                    { at: 0, color: '#6366f1' },
                                    { at: 1, color: '#8b5cf6' },
                                ],
                            },
                        },
                        opacity: 1,
                        zIndex: 0,
                    },
                    {
                        id: 'title',
                        type: 'text',
                        content: 'Project Proposal',
                        transform: { x: 80, y: 100, width: 920, height: 80, rotation: 0 },
                        fontFamily: 'Inter, sans-serif',
                        fontSize: 64,
                        fontWeight: 700,
                        fill: '#ffffff',
                        align: 'center',
                        opacity: 1,
                        zIndex: 1,
                    },
                    {
                        id: 'content',
                        type: 'text',
                        content: 'Prepared for: Pelican Logistics\nPrepared by: Dropple Design Studio',
                        transform: { x: 80, y: 400, width: 920, height: 300, rotation: 0 },
                        fontFamily: 'Inter, sans-serif',
                        fontSize: 28,
                        fontWeight: 400,
                        fill: '#1e293b',
                        align: 'left',
                        opacity: 1,
                        zIndex: 2,
                    },
                ],
            },
        ],
        editableData: {
            title: 'Project Proposal',
            company: 'Pelican Logistics',
            preparedBy: 'Dropple Design Studio',
            headerGradient: ['#6366f1', '#8b5cf6'],
        },
    },
    {
        version: 1,
        title: 'Letterhead – Minimal Gray',
        slug: 'business-letterhead-gray-1',
        category: 'business',
        tags: ['letterhead', 'document', 'corporate'],
        defaultArtboardId: 'canvas-1',
        artboards: [
            {
                id: 'canvas-1',
                size: { width: 1080, height: 1528 },
                background: { kind: 'color', value: '#f8fafc' },
                layers: [
                    {
                        id: 'logo',
                        type: 'image',
                        src: 'https://images.unsplash.com/photo-1601933470928-c8b3a3f81f4f?w=600',
                        transform: { x: 80, y: 80, width: 120, height: 120, rotation: 0 },
                        fit: 'cover',
                        flip: { horizontal: false, vertical: false },
                        filters: { contrast: 0, brightness: 0, saturation: 0, blur: 0 },
                        opacity: 1,
                        zIndex: 0,
                    },
                    {
                        id: 'title',
                        type: 'text',
                        content: 'Pelican Group of Companies',
                        transform: { x: 240, y: 100, width: 760, height: 80, rotation: 0 },
                        fontFamily: 'Inter, sans-serif',
                        fontSize: 40,
                        fontWeight: 700,
                        fill: '#1e293b',
                        align: 'left',
                        zIndex: 1,
                    },
                    {
                        id: 'footer-bar',
                        type: 'shape',
                        shape: 'rect',
                        transform: { x: 0, y: 1440, width: 1080, height: 88, rotation: 0 },
                        fill: { kind: 'solid', color: '#e2e8f0' },
                        zIndex: 2,
                    },
                ],
            },
        ],
        editableData: {
            company: 'Pelican Group of Companies',
            accentColor: '#e2e8f0',
        },
    },
    {
        version: 1,
        title: 'Email Signature – Professional Blue',
        slug: 'business-email-signature-blue-1',
        category: 'business',
        tags: ['email', 'signature', 'corporate'],
        defaultArtboardId: 'canvas-1',
        artboards: [
            {
                id: 'canvas-1',
                size: { width: 600, height: 200 },
                background: { kind: 'color', value: '#ffffff' },
                layers: [
                    {
                        id: 'photo',
                        type: 'image',
                        src: 'https://images.unsplash.com/photo-1502685104226-ee32379fefbe?w=400',
                        transform: { x: 30, y: 30, width: 140, height: 140, rotation: 0 },
                        fit: 'cover',
                        flip: { horizontal: false, vertical: false },
                        filters: { contrast: 0, brightness: 0, saturation: 0, blur: 0 },
                        zIndex: 0,
                    },
                    {
                        id: 'name',
                        type: 'text',
                        content: 'John Smith',
                        transform: { x: 200, y: 50, width: 380, height: 40, rotation: 0 },
                        fontFamily: 'Inter, sans-serif',
                        fontSize: 24,
                        fontWeight: 700,
                        fill: '#1e293b',
                    },
                    {
                        id: 'title',
                        type: 'text',
                        content: 'Operations Manager',
                        transform: { x: 200, y: 90, width: 380, height: 30, rotation: 0 },
                        fontFamily: 'Inter, sans-serif',
                        fontSize: 18,
                        fill: '#475569',
                    },
                    {
                        id: 'divider',
                        type: 'shape',
                        shape: 'rect',
                        transform: { x: 200, y: 130, width: 370, height: 1, rotation: 0 },
                        fill: { kind: 'solid', color: '#e2e8f0' },
                    },
                    {
                        id: 'company',
                        type: 'text',
                        content: 'Pelican Logistics Ltd.',
                        transform: { x: 200, y: 150, width: 380, height: 30, rotation: 0 },
                        fontFamily: 'Inter, sans-serif',
                        fontSize: 18,
                        fill: '#3b82f6',
                    },
                ],
            },
        ],
        editableData: {
            name: 'John Smith',
            title: 'Operations Manager',
            company: 'Pelican Logistics Ltd.',
            accentColor: '#3b82f6',
        },
    },
    {
        version: 1,
        title: 'Invoice – Modern Minimal',
        slug: 'business-invoice-modern-1',
        category: 'business',
        tags: ['invoice', 'document', 'finance'],
        defaultArtboardId: 'canvas-1',
        artboards: [
            {
                id: 'canvas-1',
                size: { width: 1080, height: 1528 },
                background: { kind: 'color', value: '#ffffff' },
                layers: [
                    {
                        id: 'header',
                        type: 'shape',
                        shape: 'rect',
                        transform: { x: 0, y: 0, width: 1080, height: 180, rotation: 0 },
                        fill: { kind: 'solid', color: '#3b82f6' },
                        zIndex: 0,
                    },
                    {
                        id: 'logo',
                        type: 'image',
                        src: 'https://images.unsplash.com/photo-1629904853698-eef7db4b8a6a?w=600',
                        transform: { x: 60, y: 40, width: 100, height: 100, rotation: 0 },
                        fit: 'cover',
                        flip: { horizontal: false, vertical: false },
                        filters: { contrast: 0, brightness: 0, saturation: 0, blur: 0 },
                        zIndex: 1,
                    },
                    {
                        id: 'title',
                        type: 'text',
                        content: 'INVOICE',
                        transform: { x: 880, y: 60, width: 140, height: 60, rotation: 0 },
                        fontFamily: 'Inter, sans-serif',
                        fontSize: 40,
                        fontWeight: 700,
                        fill: '#ffffff',
                        align: 'right',
                        zIndex: 2,
                    },
                ],
            },
        ],
        editableData: {
            company: 'Pelican Group',
            title: 'INVOICE',
            accentColor: '#3b82f6',
        },
    },
    {
        version: 1,
        title: 'Enterprise Dashboard – Analytics Overview',
        slug: 'enterprise-dashboard-analytics-1',
        category: 'enterprise',
        tags: ['dashboard', 'analytics', 'data'],
        defaultArtboardId: 'canvas-1',
        artboards: [
            {
                id: 'canvas-1',
                size: { width: 1920, height: 1080 },
                background: { kind: 'color', value: '#0f172a' },
                layers: [
                    {
                        id: 'chart-bg',
                        type: 'shape',
                        shape: 'rect',
                        transform: { x: 60, y: 220, width: 1800, height: 720, rotation: 0 },
                        fill: { kind: 'solid', color: '#1e293b' },
                        opacity: 1,
                        zIndex: 0,
                    },
                    {
                        id: 'header',
                        type: 'text',
                        content: 'Monthly Performance Dashboard',
                        transform: { x: 80, y: 80, width: 1760, height: 80, rotation: 0 },
                        fontFamily: 'Inter, sans-serif',
                        fontSize: 56,
                        fontWeight: 700,
                        fill: '#38bdf8',
                        align: 'center',
                        zIndex: 1,
                    },
                    {
                        id: 'graph-img',
                        type: 'image',
                        src: 'https://images.unsplash.com/photo-1581093588401-22e8a7f2bfc1?w=1200',
                        transform: { x: 100, y: 260, width: 1720, height: 680, rotation: 0 },
                        fit: 'cover',
                        flip: { horizontal: false, vertical: false },
                        filters: { contrast: 0, brightness: 0, saturation: 0, blur: 0 },
                        opacity: 0.5,
                        zIndex: 2,
                    },
                ],
            },
        ],
        editableData: {
            title: 'Monthly Performance Dashboard',
            accentColor: '#38bdf8',
            bgColor: '#0f172a',
        },
    },
    {
        version: 1,
        title: 'Enterprise Report – Annual Summary',
        slug: 'enterprise-annual-report-1',
        category: 'enterprise',
        tags: ['report', 'summary', 'business'],
        defaultArtboardId: 'canvas-1',
        artboards: [
            {
                id: 'canvas-1',
                size: { width: 1080, height: 1528 },
                background: { kind: 'color', value: '#ffffff' },
                layers: [
                    {
                        id: 'header-bar',
                        type: 'shape',
                        shape: 'rect',
                        transform: { x: 0, y: 0, width: 1080, height: 240, rotation: 0 },
                        fill: {
                            kind: 'gradient',
                            gradient: {
                                type: 'linear',
                                angle: 120,
                                stops: [
                                    { at: 0, color: '#06b6d4' },
                                    { at: 1, color: '#3b82f6' },
                                ],
                            },
                        },
                        zIndex: 0,
                    },
                    {
                        id: 'title',
                        type: 'text',
                        content: '2025 Annual Business Report',
                        transform: { x: 100, y: 100, width: 880, height: 80, rotation: 0 },
                        fontFamily: 'Inter, sans-serif',
                        fontSize: 52,
                        fontWeight: 700,
                        fill: '#ffffff',
                        align: 'center',
                        zIndex: 1,
                    },
                    {
                        id: 'image',
                        type: 'image',
                        src: 'https://images.unsplash.com/photo-1504384308090-c894fdcc538d?w=1200',
                        transform: { x: 80, y: 300, width: 920, height: 480, rotation: 0 },
                        fit: 'cover',
                        flip: { horizontal: false, vertical: false },
                        filters: { contrast: 0, brightness: 0, saturation: 0, blur: 0 },
                        zIndex: 2,
                    },
                ],
            },
        ],
        editableData: {
            title: '2025 Annual Business Report',
            accentColor: '#06b6d4',
        },
    },
    {
        version: 1,
        title: 'Enterprise KPI – Metrics Panel',
        slug: 'enterprise-kpi-panel-1',
        category: 'enterprise',
        tags: ['kpi', 'metrics', 'dashboard'],
        defaultArtboardId: 'canvas-1',
        artboards: [
            {
                id: 'canvas-1',
                size: { width: 1920, height: 1080 },
                background: { kind: 'color', value: '#111827' },
                layers: [
                    {
                        id: 'title',
                        type: 'text',
                        content: 'Q4 Key Performance Indicators',
                        transform: { x: 100, y: 80, width: 1720, height: 100, rotation: 0 },
                        fontFamily: 'Inter, sans-serif',
                        fontSize: 64,
                        fontWeight: 700,
                        fill: '#22d3ee',
                        align: 'center',
                    },
                    {
                        id: 'metrics',
                        type: 'image',
                        src: 'https://images.unsplash.com/photo-1605902711622-cfb43c4437e1?w=1200',
                        transform: { x: 200, y: 240, width: 1520, height: 640, rotation: 0 },
                        fit: 'cover',
                        flip: { horizontal: false, vertical: false },
                        filters: { contrast: 0, brightness: 0, saturation: 0, blur: 0 },
                        opacity: 0.5,
                    },
                ],
            },
        ],
        editableData: {
            title: 'Q4 Key Performance Indicators',
            accentColor: '#22d3ee',
        },
    },
    {
        version: 1,
        title: 'Enterprise Roadmap – Product Vision',
        slug: 'enterprise-roadmap-vision-1',
        category: 'enterprise',
        tags: ['roadmap', 'product', 'strategy'],
        defaultArtboardId: 'canvas-1',
        artboards: [
            {
                id: 'canvas-1',
                size: { width: 1920, height: 1080 },
                background: { kind: 'color', value: '#ffffff' },
                layers: [
                    {
                        id: 'bg-shape',
                        type: 'shape',
                        shape: 'ellipse',
                        transform: { x: 600, y: -200, width: 1200, height: 1200, rotation: 0 },
                        fill: { kind: 'solid', color: '#e0f2fe' },
                        zIndex: 0,
                    },
                    {
                        id: 'title',
                        type: 'text',
                        content: 'Product Roadmap 2025',
                        transform: { x: 200, y: 160, width: 1520, height: 100, rotation: 0 },
                        fontFamily: 'Inter, sans-serif',
                        fontSize: 64,
                        fontWeight: 700,
                        fill: '#0ea5e9',
                        align: 'center',
                        zIndex: 1,
                    },
                    {
                        id: 'illustration',
                        type: 'image',
                        src: 'https://images.unsplash.com/photo-1605902711622-cfb43c4437e1?w=1200',
                        transform: { x: 400, y: 340, width: 1120, height: 540, rotation: 0 },
                        fit: 'cover',
                        flip: { horizontal: false, vertical: false },
                        filters: { contrast: 0, brightness: 0, saturation: 0, blur: 0 },
                        opacity: 0.7,
                        zIndex: 2,
                    },
                ],
            },
        ],
        editableData: {
            title: 'Product Roadmap 2025',
            accentColor: '#0ea5e9',
        },
    },
    {
        version: 1,
        title: 'Enterprise Architecture – Tech Layout',
        slug: 'enterprise-architecture-layout-1',
        category: 'enterprise',
        tags: ['architecture', 'technology', 'infrastructure'],
        defaultArtboardId: 'canvas-1',
        artboards: [
            {
                id: 'canvas-1',
                size: { width: 1920, height: 1080 },
                background: { kind: 'color', value: '#f9fafb' },
                layers: [
                    {
                        id: 'photo',
                        type: 'image',
                        src: 'https://images.unsplash.com/photo-1620712943543-bcc4688b9a6b?w=1200',
                        transform: { x: 0, y: 0, width: 1920, height: 1080, rotation: 0 },
                        fit: 'cover',
                        flip: { horizontal: false, vertical: false },
                        filters: { contrast: 0, brightness: 0, saturation: 0, blur: 0 },
                        opacity: 0.5,
                        zIndex: 0,
                    },
                    {
                        id: 'title',
                        type: 'text',
                        content: 'Enterprise Architecture Overview',
                        transform: { x: 200, y: 440, width: 1520, height: 100, rotation: 0 },
                        fontFamily: 'Inter, sans-serif',
                        fontSize: 60,
                        fontWeight: 800,
                        fill: '#0f172a',
                        align: 'center',
                        zIndex: 1,
                    },
                ],
            },
        ],
        editableData: {
            title: 'Enterprise Architecture Overview',
            accentColor: '#0f172a',
        },
    },
];

export const BUSINESS_TEMPLATE_RECORD: Record<string, Record<string, unknown>> = BUSINESS_ENTERPRISE_TEMPLATES.reduce(
    (acc, template) => {
        acc[template.slug] = template;
        return acc;
    },
    {} as Record<string, Record<string, unknown>>
);
