export const CULTURAL_HERITAGE_TEMPLATES = [
    {
        version: 1,
        title: 'African Heritage Festival Poster',
        slug: 'cultural-african-festival-1',
        category: 'popular',
        tags: ['africa', 'heritage', 'festival'],
        thumbnail: {
            type: 'css',
            style: {
                background: 'linear-gradient(135deg, #78350f, #facc15)',
                borderRadius: '12px',
                boxShadow: '0 4px 18px rgba(250,204,21,0.25)',
            },
        },
        defaultArtboardId: 'canvas-1',
        artboards: [
            {
                id: 'canvas-1',
                name: 'Heritage Festival',
                size: { width: 1080, height: 1350 },
                background: { kind: 'color', value: '#0f172a' },
                layers: [
                    {
                        id: 'background-photo',
                        type: 'image',
                        src: 'https://images.unsplash.com/photo-1505839673365-e3971f8d9184?w=1600',
                        transform: { x: 0, y: 0, width: 1080, height: 1350, rotation: 0 },
                        fit: 'cover',
                        opacity: 1,
                        flip: { horizontal: false, vertical: false },
                        filters: { contrast: 0, brightness: 0, saturation: 0, blur: 0 },
                    },
                    {
                        id: 'overlay',
                        type: 'shape',
                        shape: 'rect',
                        transform: { x: 0, y: 0, width: 1080, height: 1350, rotation: 0 },
                        fill: { kind: 'solid', color: '#000000' },
                        opacity: 0.4,
                    },
                    {
                        id: 'title',
                        type: 'text',
                        content: 'AFRICAN HERITAGE FESTIVAL',
                        transform: { x: 100, y: 480, width: 880, height: 200, rotation: 0 },
                        fontFamily: 'Inter, sans-serif',
                        fontSize: 72,
                        fontWeight: 900,
                        fill: '#facc15',
                        align: 'center',
                    },
                    {
                        id: 'subtitle',
                        type: 'text',
                        content: 'Music • Dance • Culture',
                        transform: { x: 100, y: 700, width: 880, height: 80, rotation: 0 },
                        fontFamily: 'Inter, sans-serif',
                        fontSize: 32,
                        fontWeight: 600,
                        fill: '#fefce8',
                        align: 'center',
                    },
                ],
            },
        ],
        editableData: {
            title: 'AFRICAN HERITAGE FESTIVAL',
            subtitle: 'Music • Dance • Culture',
            image: 'https://images.unsplash.com/photo-1505839673365-e3971f8d9184?w=1600',
        },
    },
    {
        version: 1,
        title: 'Black History Tribute Card',
        slug: 'cultural-bhm-1',
        category: 'education',
        tags: ['black history', 'tribute', 'heritage'],
        thumbnail: {
            type: 'css',
            style: {
                background: 'linear-gradient(135deg, #1e293b, #0f172a)',
                borderRadius: '12px',
                boxShadow: '0 4px 18px rgba(15,23,42,0.25)',
            },
        },
        defaultArtboardId: 'canvas-1',
        artboards: [
            {
                id: 'canvas-1',
                name: 'Black History Tribute',
                size: { width: 1080, height: 1080 },
                background: { kind: 'color', value: '#1e293b' },
                layers: [
                    {
                        id: 'pattern',
                        type: 'image',
                        src: 'https://images.unsplash.com/photo-1597848212624-60b19c43ecb9?w=1600',
                        transform: { x: 0, y: 0, width: 1080, height: 1080, rotation: 0 },
                        fit: 'cover',
                        opacity: 0.2,
                        flip: { horizontal: false, vertical: false },
                        filters: { contrast: 0, brightness: 0, saturation: 0, blur: 0 },
                    },
                    {
                        id: 'title',
                        type: 'text',
                        content: 'BLACK HISTORY MONTH',
                        transform: { x: 100, y: 420, width: 880, height: 100, rotation: 0 },
                        fontFamily: 'Inter, sans-serif',
                        fontSize: 72,
                        fontWeight: 900,
                        fill: '#facc15',
                        align: 'center',
                    },
                    {
                        id: 'subtitle',
                        type: 'text',
                        content: 'Celebrate Strength. Honor Legacy.',
                        transform: { x: 100, y: 540, width: 880, height: 60, rotation: 0 },
                        fontFamily: 'Inter, sans-serif',
                        fontSize: 28,
                        fontWeight: 400,
                        fill: '#e2e8f0',
                        align: 'center',
                    },
                ],
            },
        ],
        editableData: {
            title: 'BLACK HISTORY MONTH',
            subtitle: 'Celebrate Strength. Honor Legacy.',
        },
    },
    {
        version: 1,
        title: 'Cultural Exhibition Flyer',
        slug: 'cultural-exhibition-1',
        category: 'marketing',
        tags: ['exhibition', 'flyer', 'culture'],
        thumbnail: {
            type: 'css',
            style: {
                background: 'linear-gradient(135deg, #f97316, #facc15)',
                borderRadius: '12px',
                boxShadow: '0 4px 18px rgba(249,115,22,0.25)',
            },
        },
        defaultArtboardId: 'canvas-1',
        artboards: [
            {
                id: 'canvas-1',
                name: 'Cultural Exhibition',
                size: { width: 1080, height: 1920 },
                background: { kind: 'color', value: '#fafaf9' },
                layers: [
                    {
                        id: 'image',
                        type: 'image',
                        src: 'https://images.unsplash.com/photo-1512427691650-1c7b3c88732d?w=1600',
                        transform: { x: 100, y: 200, width: 880, height: 600, rotation: 0 },
                        fit: 'cover',
                        opacity: 1,
                        flip: { horizontal: false, vertical: false },
                        filters: { contrast: 0, brightness: 0, saturation: 0, blur: 0 },
                    },
                    {
                        id: 'title',
                        type: 'text',
                        content: 'CULTURE THROUGH ART',
                        transform: { x: 100, y: 880, width: 880, height: 120, rotation: 0 },
                        fontFamily: 'Inter, sans-serif',
                        fontSize: 64,
                        fontWeight: 800,
                        fill: '#1e293b',
                        align: 'center',
                    },
                ],
            },
        ],
        editableData: {
            title: 'CULTURE THROUGH ART',
            image: 'https://images.unsplash.com/photo-1512427691650-1c7b3c88732d?w=1600',
        },
    },
    {
        version: 1,
        title: 'Heritage Poster – Earth Tones',
        slug: 'cultural-earthtone-1',
        category: 'popular',
        tags: ['heritage', 'earth', 'poster'],
        thumbnail: {
            type: 'css',
            style: {
                background: 'linear-gradient(135deg, #92400e, #f59e0b)',
                borderRadius: '12px',
                boxShadow: '0 4px 18px rgba(146,64,14,0.25)',
            },
        },
        defaultArtboardId: 'canvas-1',
        artboards: [
            {
                id: 'canvas-1',
                name: 'Heritage Poster',
                size: { width: 1080, height: 1350 },
                background: {
                    kind: 'gradient',
                    gradient: {
                        type: 'linear',
                        angle: 90,
                        stops: [
                            { at: 0, color: '#92400e' },
                            { at: 1, color: '#f59e0b' },
                        ],
                    },
                },
                layers: [
                    {
                        id: 'title',
                        type: 'text',
                        content: 'ROOTS & RHYTHMS',
                        transform: { x: 100, y: 500, width: 880, height: 100, rotation: 0 },
                        fontFamily: 'Inter, sans-serif',
                        fontSize: 72,
                        fontWeight: 900,
                        fill: '#ffffff',
                        align: 'center',
                    },
                    {
                        id: 'subtitle',
                        type: 'text',
                        content: 'A Celebration of Culture & Sound',
                        transform: { x: 100, y: 640, width: 880, height: 60, rotation: 0 },
                        fontFamily: 'Inter, sans-serif',
                        fontSize: 28,
                        fontWeight: 500,
                        fill: '#fde68a',
                        align: 'center',
                    },
                ],
            },
        ],
        editableData: {
            title: 'ROOTS & RHYTHMS',
            subtitle: 'A Celebration of Culture & Sound',
            gradient: ['#92400e', '#f59e0b'],
        },
    },
    {
        version: 1,
        title: 'Afro-Futurism Poster',
        slug: 'cultural-afrofuturism-1',
        category: 'enterprise',
        tags: ['afrofuturism', 'digital', 'art'],
        thumbnail: {
            type: 'css',
            style: {
                background: 'linear-gradient(135deg, #0f172a, #0e7490)',
                borderRadius: '12px',
                boxShadow: '0 4px 18px rgba(14,116,144,0.25)',
            },
        },
        defaultArtboardId: 'canvas-1',
        artboards: [
            {
                id: 'canvas-1',
                name: 'Afro-Futurism',
                size: { width: 1080, height: 1350 },
                background: { kind: 'color', value: '#0f172a' },
                layers: [
                    {
                        id: 'background-photo',
                        type: 'image',
                        src: 'https://images.unsplash.com/photo-1529626455594-4ff0802cfb7e?w=1600',
                        transform: { x: 0, y: 0, width: 1080, height: 1350, rotation: 0 },
                        fit: 'cover',
                        opacity: 1,
                        flip: { horizontal: false, vertical: false },
                        filters: { contrast: 0, brightness: 0, saturation: 0, blur: 0 },
                    },
                    {
                        id: 'overlay',
                        type: 'shape',
                        shape: 'rect',
                        transform: { x: 0, y: 0, width: 1080, height: 1350, rotation: 0 },
                        fill: { kind: 'solid', color: '#000000' },
                        opacity: 0.5,
                    },
                    {
                        id: 'title',
                        type: 'text',
                        content: 'AFRO-FUTURE VISIONS',
                        transform: { x: 100, y: 520, width: 880, height: 120, rotation: 0 },
                        fontFamily: 'Inter, sans-serif',
                        fontSize: 68,
                        fontWeight: 900,
                        fill: '#22d3ee',
                        align: 'center',
                    },
                    {
                        id: 'subtitle',
                        type: 'text',
                        content: 'The Intersection of Culture & Technology',
                        transform: { x: 100, y: 680, width: 880, height: 80, rotation: 0 },
                        fontFamily: 'Inter, sans-serif',
                        fontSize: 28,
                        fontWeight: 500,
                        fill: '#e2e8f0',
                        align: 'center',
                    },
                ],
            },
        ],
        editableData: {
            title: 'AFRO-FUTURE VISIONS',
            subtitle: 'The Intersection of Culture & Technology',
            image: 'https://images.unsplash.com/photo-1529626455594-4ff0802cfb7e?w=1600',
        },
    },
];

export const CULTURAL_HERITAGE_RECORD: Record<string, Record<string, unknown>> = CULTURAL_HERITAGE_TEMPLATES.reduce(
    (acc, template) => {
        acc[template.slug] = template;
        return acc;
    },
    {} as Record<string, Record<string, unknown>>
);

