import { SOCIAL_TEMPLATE_RECORD } from './socialTemplates';
import { BUSINESS_TEMPLATE_RECORD } from './businessEnterpriseTemplates';
import { MARKETING_INVOICES_RECORD } from './marketingInvoicesTemplates';
import { ECOMMERCE_EDUCATION_RECORD } from './ecommerceEducationTemplates';
import { REAL_ESTATE_FOOD_RECORD } from './realEstateFoodTemplates';
import { MEDICAL_TRAVEL_RECORD } from './medicalTravelTemplates';
import { PHOTOGRAPHY_CAMPAIGNS_TECH_LOGISTICS_RECORD } from './photographyCampaignsTechLogisticsTemplates';
import { FOOD_REALESTATE_FASHION_NATURE_RECORD } from './foodRealEstateFashionNatureTemplates';
import { EDUCATION_RESUME_MARKETING_INVOICES_RECORD } from './educationResumeMarketingInvoicesTemplates';
import { PRESENTATIONS_SOCIAL_POPULAR_RECORD } from './presentationsSocialPopularTemplates';
import { TECH_TRANSPORT_STARTUP_RECORD } from './techTransportStartupTemplates';
import { TRAVEL_REALESTATE_PHOTOGRAPHY_RECORD } from './travelRealEstatePhotographyTemplates';
import { FOOD_CAMPAIGNS_RECORD } from './foodCampaignsTemplates';
import { MEDICAL_HEALTH_RECORD } from './medicalHealthTemplates';
import { ECOMMERCE_MARKETING_RECORD } from './ecommerceMarketingTemplates';
import { BRAND_IDENTITY_RECORD } from './brandIdentityTemplates';
import { CONTENT_CREATOR_RECORD } from './contentCreatorTemplates';
import { EVENTS_INVITATIONS_RECORD } from './eventsInvitationsTemplates';
import { INFOGRAPHICS_DATA_RECORD } from './infographicsDataTemplates';
import { SEASONAL_HOLIDAY_RECORD } from './seasonalHolidayTemplates';
import { ABSTRACT_GRADIENT_RECORD } from './abstractGradientTemplates';
import { CULTURAL_HERITAGE_RECORD } from './culturalHeritageTemplates';
import { AI_MOCKUP_RECORD } from './aiMockupTemplates';

const instagramPostMinimal = {
    version: 1,
    title: 'Instagram Post - Minimalist',
    slug: 'social-instagram-post-1',
    category: 'social',
    tags: ['instagram', 'social media', 'minimalist'],
    defaultArtboardId: 'canvas-1',
    artboards: [
        {
            id: 'canvas-1',
            name: 'Instagram Post',
            size: { width: 1080, height: 1080 },
            background: { kind: 'color', value: '#f8f9fa' },
            layers: [
                {
                    id: 'bg-image',
                    type: 'image',
                    name: 'Background Image',
                    transform: { x: 240, y: 90, width: 600, height: 600, rotation: 0 },
                    opacity: 0.15,
                    visible: true,
                    locked: false,
                    zIndex: 0,
                    src: 'https://images.unsplash.com/photo-1687042268510-c790c643ba4a?w=800',
                    fit: 'cover',
                },
                {
                    id: 'bg-shape',
                    type: 'shape',
                    name: 'Background Circle',
                    transform: { x: 340, y: 340, width: 400, height: 400, rotation: 0 },
                    opacity: 1,
                    visible: true,
                    locked: false,
                    zIndex: 1,
                    shape: 'ellipse',
                    fill: { kind: 'solid', color: '#6366f1' },
                    stroke: { color: '#4f46e5', width: 0 },
                },
                {
                    id: 'title',
                    type: 'text',
                    name: 'Title',
                    transform: { x: 100, y: 450, width: 880, height: 100, rotation: 0 },
                    opacity: 1,
                    visible: true,
                    locked: false,
                    zIndex: 2,
                    content: 'Your Title Here',
                    fontFamily: 'Inter, sans-serif',
                    fontSize: 64,
                    fontWeight: '700',
                    fill: '#1e293b',
                    align: 'center',
                    lineHeight: 1.2,
                    letterSpacing: -1,
                },
                {
                    id: 'subtitle',
                    type: 'text',
                    name: 'Subtitle',
                    transform: { x: 100, y: 580, width: 880, height: 60, rotation: 0 },
                    opacity: 1,
                    visible: true,
                    locked: false,
                    zIndex: 3,
                    content: 'Add your message here',
                    fontFamily: 'Inter, sans-serif',
                    fontSize: 28,
                    fontWeight: '400',
                    fill: '#64748b',
                    align: 'center',
                    lineHeight: 1.5,
                },
            ],
        },
    ],
};

const presentationSlideModern = {
    version: 1,
    title: 'Presentation Slide - Modern',
    slug: 'presentation-slide-1',
    category: 'presentation',
    tags: ['presentation', 'business', 'modern'],
    defaultArtboardId: 'canvas-2',
    artboards: [
        {
            id: 'canvas-2',
            name: 'Presentation Slide',
            size: { width: 1920, height: 1080 },
            background: { kind: 'color', value: '#ffffff' },
            layers: [
                {
                    id: 'header-bg',
                    type: 'shape',
                    name: 'Header Background',
                    transform: { x: 0, y: 0, width: 1920, height: 200, rotation: 0 },
                    opacity: 1,
                    visible: true,
                    locked: false,
                    zIndex: 0,
                    shape: 'rect',
                    fill: { kind: 'solid', color: '#1e293b' },
                },
                {
                    id: 'header-title',
                    type: 'text',
                    name: 'Header Title',
                    transform: { x: 100, y: 60, width: 1720, height: 80, rotation: 0 },
                    opacity: 1,
                    visible: true,
                    locked: false,
                    zIndex: 1,
                    content: 'Presentation Title',
                    fontFamily: 'Inter, sans-serif',
                    fontSize: 72,
                    fontWeight: '700',
                    fill: '#ffffff',
                    align: 'left',
                    lineHeight: 1.2,
                    letterSpacing: -1,
                },
                {
                    id: 'content-title',
                    type: 'text',
                    name: 'Content Title',
                    transform: { x: 100, y: 300, width: 1720, height: 120, rotation: 0 },
                    opacity: 1,
                    visible: true,
                    locked: false,
                    zIndex: 2,
                    content: 'Main Content',
                    fontFamily: 'Inter, sans-serif',
                    fontSize: 56,
                    fontWeight: '600',
                    fill: '#1e293b',
                    align: 'left',
                    lineHeight: 1.3,
                    letterSpacing: -0.5,
                },
                {
                    id: 'bullet-1',
                    type: 'text',
                    name: 'Bullet Point 1',
                    transform: { x: 150, y: 460, width: 1620, height: 60, rotation: 0 },
                    opacity: 1,
                    visible: true,
                    locked: false,
                    zIndex: 3,
                    content: '• First key point goes here',
                    fontFamily: 'Inter, sans-serif',
                    fontSize: 36,
                    fontWeight: '400',
                    fill: '#475569',
                    align: 'left',
                    lineHeight: 1.5,
                },
                {
                    id: 'bullet-2',
                    type: 'text',
                    name: 'Bullet Point 2',
                    transform: { x: 150, y: 550, width: 1620, height: 60, rotation: 0 },
                    opacity: 1,
                    visible: true,
                    locked: false,
                    zIndex: 4,
                    content: '• Second key point goes here',
                    fontFamily: 'Inter, sans-serif',
                    fontSize: 36,
                    fontWeight: '400',
                    fill: '#475569',
                    align: 'left',
                    lineHeight: 1.5,
                },
                {
                    id: 'bullet-3',
                    type: 'text',
                    name: 'Bullet Point 3',
                    transform: { x: 150, y: 640, width: 1620, height: 60, rotation: 0 },
                    opacity: 1,
                    visible: true,
                    locked: false,
                    zIndex: 5,
                    content: '• Third key point goes here',
                    fontFamily: 'Inter, sans-serif',
                    fontSize: 36,
                    fontWeight: '400',
                    fill: '#475569',
                    align: 'left',
                    lineHeight: 1.5,
                },
            ],
        },
    ],
};

const flyerBoldColorful = {
    version: 1,
    title: 'Flyer - Bold & Colorful',
    slug: 'flyer-modern-1',
    category: 'marketing',
    tags: ['flyer', 'marketing', 'colorful'],
    defaultArtboardId: 'canvas-3',
    artboards: [
        {
            id: 'canvas-3',
            name: 'Flyer',
            size: { width: 1080, height: 1920 },
            background: { kind: 'color', value: '#fef3c7' },
            layers: [
                {
                    id: 'bg-image',
                    type: 'image',
                    name: 'Party Image',
                    transform: { x: 140, y: 200, width: 800, height: 400, rotation: 0 },
                    opacity: 0.2,
                    visible: true,
                    locked: false,
                    zIndex: 0,
                    src: 'https://images.unsplash.com/photo-1659407490039-27cc03c0b4b3?w=800',
                    fit: 'cover',
                },
                {
                    id: 'top-shape',
                    type: 'shape',
                    name: 'Top Shape',
                    transform: { x: -200, y: -200, width: 600, height: 600, rotation: 0 },
                    opacity: 1,
                    visible: true,
                    locked: false,
                    zIndex: 1,
                    shape: 'ellipse',
                    fill: { kind: 'solid', color: '#f59e0b' },
                },
                {
                    id: 'bottom-shape',
                    type: 'shape',
                    name: 'Bottom Shape',
                    transform: { x: 680, y: 1520, width: 600, height: 600, rotation: 0 },
                    opacity: 1,
                    visible: true,
                    locked: false,
                    zIndex: 1,
                    shape: 'ellipse',
                    fill: { kind: 'solid', color: '#ef4444' },
                },
                {
                    id: 'main-title',
                    type: 'text',
                    name: 'Main Title',
                    transform: { x: 80, y: 700, width: 920, height: 200, rotation: 0 },
                    opacity: 1,
                    visible: true,
                    locked: false,
                    zIndex: 2,
                    content: 'AMAZING\nEVENT',
                    fontFamily: 'Inter, sans-serif',
                    fontSize: 96,
                    fontWeight: '800',
                    fill: '#1e293b',
                    align: 'center',
                    lineHeight: 1.1,
                    letterSpacing: -2,
                },
                {
                    id: 'subtitle',
                    type: 'text',
                    name: 'Subtitle',
                    transform: { x: 80, y: 950, width: 920, height: 80, rotation: 0 },
                    opacity: 1,
                    visible: true,
                    locked: false,
                    zIndex: 3,
                    content: 'Join us for something special',
                    fontFamily: 'Inter, sans-serif',
                    fontSize: 32,
                    fontWeight: '500',
                    fill: '#475569',
                    align: 'center',
                    lineHeight: 1.4,
                },
                {
                    id: 'date',
                    type: 'text',
                    name: 'Date',
                    transform: { x: 80, y: 1100, width: 920, height: 60, rotation: 0 },
                    opacity: 1,
                    visible: true,
                    locked: false,
                    zIndex: 4,
                    content: 'October 15, 2025',
                    fontFamily: 'Inter, sans-serif',
                    fontSize: 36,
                    fontWeight: '600',
                    fill: '#1e293b',
                    align: 'center',
                    lineHeight: 1.5,
                },
            ],
        },
    ],
};

const instagramStoryGradient = {
    version: 1,
    title: 'Instagram Story - Gradient',
    slug: 'social-story-1',
    category: 'social',
    tags: ['instagram', 'story', 'gradient'],
    defaultArtboardId: 'canvas-4',
    artboards: [
        {
            id: 'canvas-4',
            name: 'Instagram Story',
            size: { width: 1080, height: 1920 },
            background: {
                kind: 'gradient',
                gradient: {
                    type: 'linear',
                    angle: 135,
                    stops: [
                        { at: 0, color: '#667eea' },
                        { at: 1, color: '#764ba2' },
                    ],
                },
            },
            layers: [
                {
                    id: 'main-text',
                    type: 'text',
                    name: 'Main Text',
                    transform: { x: 100, y: 800, width: 880, height: 300, rotation: 0 },
                    opacity: 1,
                    visible: true,
                    locked: false,
                    zIndex: 0,
                    content: 'Your Story\nStarts Here',
                    fontFamily: 'Inter, sans-serif',
                    fontSize: 84,
                    fontWeight: '800',
                    fill: '#ffffff',
                    align: 'center',
                    lineHeight: 1.2,
                    letterSpacing: -2,
                },
                {
                    id: 'cta',
                    type: 'shape',
                    name: 'CTA Button',
                    transform: { x: 290, y: 1200, width: 500, height: 100, rotation: 0 },
                    opacity: 1,
                    visible: true,
                    locked: false,
                    zIndex: 1,
                    shape: 'rect',
                    fill: { kind: 'solid', color: '#ffffff' },
                    cornerRadius: 50,
                },
                {
                    id: 'cta-text',
                    type: 'text',
                    name: 'CTA Text',
                    transform: { x: 290, y: 1220, width: 500, height: 60, rotation: 0 },
                    opacity: 1,
                    visible: true,
                    locked: false,
                    zIndex: 2,
                    content: 'Learn More',
                    fontFamily: 'Inter, sans-serif',
                    fontSize: 32,
                    fontWeight: '600',
                    fill: '#667eea',
                    align: 'center',
                    lineHeight: 1.5,
                },
            ],
        },
    ],
};

const businessCardProfessional = {
    version: 1,
    title: 'Business Card - Professional',
    slug: 'business-card-1',
    category: 'business',
    tags: ['business card', 'professional', 'networking'],
    defaultArtboardId: 'canvas-5',
    artboards: [
        {
            id: 'canvas-5',
            name: 'Business Card',
            size: { width: 1050, height: 600 },
            background: { kind: 'color', value: '#ffffff' },
            layers: [
                {
                    id: 'left-panel',
                    type: 'shape',
                    name: 'Left Panel',
                    transform: { x: 0, y: 0, width: 350, height: 600, rotation: 0 },
                    opacity: 1,
                    visible: true,
                    locked: false,
                    zIndex: 0,
                    shape: 'rect',
                    fill: { kind: 'solid', color: '#1e293b' },
                },
                {
                    id: 'name',
                    type: 'text',
                    name: 'Name',
                    transform: { x: 400, y: 150, width: 600, height: 80, rotation: 0 },
                    opacity: 1,
                    visible: true,
                    locked: false,
                    zIndex: 1,
                    content: 'John Doe',
                    fontFamily: 'Inter, sans-serif',
                    fontSize: 48,
                    fontWeight: '700',
                    fill: '#1e293b',
                    align: 'left',
                    lineHeight: 1.2,
                    letterSpacing: -1,
                },
                {
                    id: 'title',
                    type: 'text',
                    name: 'Title',
                    transform: { x: 400, y: 240, width: 600, height: 50, rotation: 0 },
                    opacity: 1,
                    visible: true,
                    locked: false,
                    zIndex: 2,
                    content: 'CEO & Founder',
                    fontFamily: 'Inter, sans-serif',
                    fontSize: 28,
                    fontWeight: '500',
                    fill: '#64748b',
                    align: 'left',
                    lineHeight: 1.4,
                },
                {
                    id: 'email',
                    type: 'text',
                    name: 'Email',
                    transform: { x: 400, y: 350, width: 600, height: 40, rotation: 0 },
                    opacity: 1,
                    visible: true,
                    locked: false,
                    zIndex: 3,
                    content: 'john@company.com',
                    fontFamily: 'Inter, sans-serif',
                    fontSize: 22,
                    fontWeight: '400',
                    fill: '#475569',
                    align: 'left',
                    lineHeight: 1.5,
                },
                {
                    id: 'phone',
                    type: 'text',
                    name: 'Phone',
                    transform: { x: 400, y: 400, width: 600, height: 40, rotation: 0 },
                    opacity: 1,
                    visible: true,
                    locked: false,
                    zIndex: 4,
                    content: '+1 (555) 123-4567',
                    fontFamily: 'Inter, sans-serif',
                    fontSize: 22,
                    fontWeight: '400',
                    fill: '#475569',
                    align: 'left',
                    lineHeight: 1.5,
                },
            ],
        },
    ],
};

export const CUSTOM_TEMPLATE_DATA: Record<string, Record<string, unknown>> = {
    'social-instagram-post-1': instagramPostMinimal,
    'presentation-slide-1': presentationSlideModern,
    'flyer-modern-1': flyerBoldColorful,
    'social-story-1': instagramStoryGradient,
    'business-card-1': businessCardProfessional,
    ...SOCIAL_TEMPLATE_RECORD,
    ...BUSINESS_TEMPLATE_RECORD,
    ...MARKETING_INVOICES_RECORD,
    ...ECOMMERCE_EDUCATION_RECORD,
    ...REAL_ESTATE_FOOD_RECORD,
    ...MEDICAL_TRAVEL_RECORD,
    ...PHOTOGRAPHY_CAMPAIGNS_TECH_LOGISTICS_RECORD,
    ...FOOD_REALESTATE_FASHION_NATURE_RECORD,
    ...EDUCATION_RESUME_MARKETING_INVOICES_RECORD,
    ...PRESENTATIONS_SOCIAL_POPULAR_RECORD,
    ...TECH_TRANSPORT_STARTUP_RECORD,
    ...TRAVEL_REALESTATE_PHOTOGRAPHY_RECORD,
    ...FOOD_CAMPAIGNS_RECORD,
    ...MEDICAL_HEALTH_RECORD,
    ...ECOMMERCE_MARKETING_RECORD,
    ...BRAND_IDENTITY_RECORD,
    ...CONTENT_CREATOR_RECORD,
    ...EVENTS_INVITATIONS_RECORD,
    ...INFOGRAPHICS_DATA_RECORD,
    ...SEASONAL_HOLIDAY_RECORD,
    ...ABSTRACT_GRADIENT_RECORD,
    ...CULTURAL_HERITAGE_RECORD,
    ...AI_MOCKUP_RECORD,
};
