export const EVENTS_INVITATIONS_TEMPLATES = [
    {
        version: 1,
        title: 'Wedding Invitation – Elegant Floral',
        slug: 'event-wedding-1',
        category: 'marketing',
        tags: ['wedding', 'invitation', 'floral'],
        thumbnail: {
            type: 'css',
            style: {
                background: 'linear-gradient(135deg, #f8fafc, #e2e8f0)',
                borderRadius: '12px',
                boxShadow: '0 4px 18px rgba(148,163,184,0.25)',
            },
        },
        defaultArtboardId: 'canvas-1',
        artboards: [
            {
                id: 'canvas-1',
                name: 'Wedding Invite',
                size: { width: 1080, height: 1528 },
                background: { kind: 'color', value: '#ffffff' },
                layers: [
                    {
                        id: 'background-photo',
                        type: 'image',
                        src: 'https://images.unsplash.com/photo-1519681393784-d120267933ba?w=1600',
                        transform: { x: 0, y: 0, width: 1080, height: 1528, rotation: 0 },
                        fit: 'cover',
                        opacity: 1,
                        flip: { horizontal: false, vertical: false },
                        filters: { contrast: 0, brightness: 0, saturation: 0, blur: 0 },
                    },
                    {
                        id: 'overlay',
                        type: 'shape',
                        shape: 'rect',
                        transform: { x: 0, y: 0, width: 1080, height: 1528, rotation: 0 },
                        fill: { kind: 'solid', color: '#ffffff' },
                        opacity: 0.85,
                    },
                    {
                        id: 'title',
                        type: 'text',
                        content: 'Emma & Lucas',
                        transform: { x: 100, y: 500, width: 880, height: 140, rotation: 0 },
                        fontFamily: 'Inter, serif',
                        fontSize: 96,
                        fontWeight: 700,
                        fill: '#1e293b',
                        align: 'center',
                    },
                    {
                        id: 'subtitle',
                        type: 'text',
                        content: 'Join us to celebrate our love – June 12, 2026',
                        transform: { x: 100, y: 660, width: 880, height: 60, rotation: 0 },
                        fontFamily: 'Inter, sans-serif',
                        fontSize: 28,
                        fontWeight: 400,
                        fill: '#475569',
                        align: 'center',
                    },
                ],
            },
        ],
        editableData: {
            title: 'Emma & Lucas',
            subtitle: 'Join us to celebrate our love – June 12, 2026',
            image: 'https://images.unsplash.com/photo-1519681393784-d120267933ba?w=1600',
        },
    },
    {
        version: 1,
        title: 'Business Conference – Corporate Flyer',
        slug: 'event-conference-1',
        category: 'enterprise',
        tags: ['business', 'conference', 'event'],
        thumbnail: {
            type: 'css',
            style: {
                background: 'linear-gradient(135deg, #0f172a, #1e293b)',
                borderRadius: '12px',
                boxShadow: '0 4px 18px rgba(15,23,42,0.25)',
            },
        },
        defaultArtboardId: 'canvas-1',
        artboards: [
            {
                id: 'canvas-1',
                name: 'Conference Flyer',
                size: { width: 1080, height: 1528 },
                background: { kind: 'color', value: '#0f172a' },
                layers: [
                    {
                        id: 'photo',
                        type: 'image',
                        src: 'https://images.unsplash.com/photo-1581091870636-1a53ffb90f3e?w=1600',
                        transform: { x: 0, y: 0, width: 1080, height: 500, rotation: 0 },
                        fit: 'cover',
                        opacity: 1,
                        flip: { horizontal: false, vertical: false },
                        filters: { contrast: 10, brightness: 0, saturation: 5, blur: 0 },
                    },
                    {
                        id: 'title',
                        type: 'text',
                        content: 'Global Tech Conference 2026',
                        transform: { x: 100, y: 560, width: 880, height: 100, rotation: 0 },
                        fontFamily: 'Inter, sans-serif',
                        fontSize: 48,
                        fontWeight: 800,
                        fill: '#ffffff',
                        align: 'center',
                    },
                    {
                        id: 'details',
                        type: 'text',
                        content: 'August 18–20, 2026 | Berlin, Germany',
                        transform: { x: 100, y: 670, width: 880, height: 60, rotation: 0 },
                        fontFamily: 'Inter, sans-serif',
                        fontSize: 28,
                        fontWeight: 400,
                        fill: '#94a3b8',
                        align: 'center',
                    },
                ],
            },
        ],
        editableData: {
            title: 'Global Tech Conference 2026',
            details: 'August 18–20, 2026 | Berlin, Germany',
            image: 'https://images.unsplash.com/photo-1581091870636-1a53ffb90f3e?w=1600',
        },
    },
    {
        version: 1,
        title: 'Birthday Party – Confetti Theme',
        slug: 'event-birthday-1',
        category: 'marketing',
        tags: ['birthday', 'party', 'celebration'],
        thumbnail: {
            type: 'css',
            style: {
                background: 'linear-gradient(135deg, #f97316, #f59e0b)',
                borderRadius: '12px',
                boxShadow: '0 4px 18px rgba(249,115,22,0.25)',
            },
        },
        defaultArtboardId: 'canvas-1',
        artboards: [
            {
                id: 'canvas-1',
                name: 'Birthday Invite',
                size: { width: 1080, height: 1528 },
                background: {
                    kind: 'gradient',
                    gradient: {
                        type: 'linear',
                        angle: 135,
                        stops: [
                            { at: 0, color: '#f59e0b' },
                            { at: 1, color: '#f97316' },
                        ],
                    },
                },
                layers: [
                    {
                        id: 'title',
                        type: 'text',
                        content: 'You’re Invited!',
                        transform: { x: 100, y: 500, width: 880, height: 100, rotation: 0 },
                        fontFamily: 'Inter, sans-serif',
                        fontSize: 72,
                        fontWeight: 900,
                        fill: '#ffffff',
                        align: 'center',
                    },
                    {
                        id: 'details',
                        type: 'text',
                        content: 'Mia’s 21st Birthday Bash • March 14th @ 7PM',
                        transform: { x: 100, y: 640, width: 880, height: 80, rotation: 0 },
                        fontFamily: 'Inter, sans-serif',
                        fontSize: 28,
                        fontWeight: 500,
                        fill: '#fff7ed',
                        align: 'center',
                    },
                ],
            },
        ],
        editableData: {
            title: 'You’re Invited!',
            details: 'Mia’s 21st Birthday Bash • March 14th @ 7PM',
            gradient: ['#f59e0b', '#f97316'],
        },
    },
    {
        version: 1,
        title: 'Music Festival – Neon Lights',
        slug: 'event-music-1',
        category: 'popular',
        tags: ['music', 'festival', 'poster'],
        thumbnail: {
            type: 'css',
            style: {
                background: 'linear-gradient(135deg, #18181b, #111827)',
                borderRadius: '12px',
                boxShadow: '0 4px 18px rgba(17,24,39,0.25)',
            },
        },
        defaultArtboardId: 'canvas-1',
        artboards: [
            {
                id: 'canvas-1',
                name: 'Music Festival Poster',
                size: { width: 1080, height: 1528 },
                background: { kind: 'color', value: '#000000' },
                layers: [
                    {
                        id: 'photo',
                        type: 'image',
                        src: 'https://images.unsplash.com/photo-1518976024611-28bf4b48222e?w=1600',
                        transform: { x: 0, y: 0, width: 1080, height: 1528, rotation: 0 },
                        fit: 'cover',
                        opacity: 1,
                        flip: { horizontal: false, vertical: false },
                        filters: { contrast: 10, brightness: 0, saturation: 10, blur: 0 },
                    },
                    {
                        id: 'title',
                        type: 'text',
                        content: 'SUMMER BEATS FEST',
                        transform: { x: 100, y: 580, width: 880, height: 120, rotation: 0 },
                        fontFamily: 'Inter, sans-serif',
                        fontSize: 72,
                        fontWeight: 900,
                        fill: '#f59e0b',
                        align: 'center',
                    },
                    {
                        id: 'date',
                        type: 'text',
                        content: 'July 10–12 • Miami Beach',
                        transform: { x: 100, y: 720, width: 880, height: 80, rotation: 0 },
                        fontFamily: 'Inter, sans-serif',
                        fontSize: 32,
                        fontWeight: 500,
                        fill: '#ffffff',
                        align: 'center',
                    },
                ],
            },
        ],
        editableData: {
            title: 'SUMMER BEATS FEST',
            date: 'July 10–12 • Miami Beach',
            image: 'https://images.unsplash.com/photo-1518976024611-28bf4b48222e?w=1600',
        },
    },
    {
        version: 1,
        title: 'Corporate Meetup – Minimal Poster',
        slug: 'event-meetup-1',
        category: 'enterprise',
        tags: ['corporate', 'poster', 'networking'],
        thumbnail: {
            type: 'css',
            style: {
                background: 'linear-gradient(135deg, #1e3a8a, #3b82f6)',
                borderRadius: '12px',
                boxShadow: '0 4px 18px rgba(59,130,246,0.25)',
            },
        },
        defaultArtboardId: 'canvas-1',
        artboards: [
            {
                id: 'canvas-1',
                name: 'Corporate Meetup',
                size: { width: 1080, height: 1528 },
                background: { kind: 'color', value: '#ffffff' },
                layers: [
                    {
                        id: 'shape',
                        type: 'shape',
                        shape: 'ellipse',
                        transform: { x: 340, y: 200, width: 400, height: 400, rotation: 0 },
                        fill: { kind: 'solid', color: '#3b82f6' },
                    },
                    {
                        id: 'title',
                        type: 'text',
                        content: 'Creative Business Meetup',
                        transform: { x: 100, y: 660, width: 880, height: 100, rotation: 0 },
                        fontFamily: 'Inter, sans-serif',
                        fontSize: 48,
                        fontWeight: 800,
                        fill: '#1e293b',
                        align: 'center',
                    },
                    {
                        id: 'date',
                        type: 'text',
                        content: 'Nov 3 • Downtown Convention Center',
                        transform: { x: 100, y: 780, width: 880, height: 60, rotation: 0 },
                        fontFamily: 'Inter, sans-serif',
                        fontSize: 28,
                        fontWeight: 500,
                        fill: '#475569',
                        align: 'center',
                    },
                ],
            },
        ],
        editableData: {
            title: 'Creative Business Meetup',
            date: 'Nov 3 • Downtown Convention Center',
            accentColor: '#3b82f6',
        },
    },
];

export const EVENTS_INVITATIONS_RECORD: Record<string, Record<string, unknown>> =
    EVENTS_INVITATIONS_TEMPLATES.reduce(
        (acc, template) => {
            acc[template.slug] = template;
            return acc;
        },
        {} as Record<string, Record<string, unknown>>
    );

