export const HYBRID_TEMPLATES_BATCH_01 = [
    {
        version: 1,
        title: 'Business – Banking Profile',
        slug: 'biz-banker-ng-1',
        category: 'business',
        tags: ['business', 'banking', 'profile'],
        thumbnailLabel: 'Elevate Your Strategy',
        thumbnail: {
            type: 'hybrid',
            cssStyle: { background: 'linear-gradient(135deg,#1e3a8a,#06b6d4)' },
            image: {
                src: 'https://images.unsplash.com/photo-1521737604893-d14cc237f11d?w=1200',
                alt: 'Nigerian banker in office',
                focalPoint: { x: 0.5, y: 0.3 },
            },
            overlayCss: { background: 'linear-gradient(180deg,rgba(0,0,0,.15),rgba(0,0,0,.45))' },
        },
        defaultArtboardId: 'a1',
        artboards: [
            {
                id: 'a1',
                name: 'Business Card',
                size: { width: 1080, height: 1080 },
                background: { kind: 'color', value: '#ffffff' },
                layers: [
                    {
                        id: 'photo',
                        type: 'image',
                        name: 'Portrait',
                        src: 'https://images.unsplash.com/photo-1521737604893-d14cc237f11d?w=1600',
                        transform: { x: 0, y: 0, width: 1080, height: 1080, rotation: 0 },
                        fit: 'cover',
                        filters: { brightness: 0, contrast: 0, saturation: 0, blur: 0 },
                    },
                    {
                        id: 'overlay',
                        type: 'shape',
                        name: 'Overlay',
                        shape: 'rect',
                        transform: { x: 0, y: 0, width: 1080, height: 1080, rotation: 0 },
                        fill: { kind: 'solid', color: 'rgba(14,165,233,0.35)' },
                        blendMode: 'multiply',
                        opacity: 1,
                    },
                    {
                        id: 'label',
                        type: 'text',
                        name: 'Bold Label',
                        content: 'Elevate Your Strategy',
                        transform: { x: 80, y: 470, width: 920, height: 140, rotation: 0 },
                        fontFamily: 'Inter, sans-serif',
                        fontSize: 64,
                        fontWeight: 900,
                        align: 'center',
                        fill: '#ffffff',
                        letterSpacing: -1,
                    },
                ],
            },
        ],
        editableData: { overlayColor: 'rgba(14,165,233,0.35)' },
    },
    {
        version: 1,
        title: 'Education – Classroom Poster',
        slug: 'edu-teacher-br-1',
        category: 'education',
        tags: ['education', 'teacher'],
        thumbnailLabel: 'Study Guide • Week 1',
        thumbnail: {
            type: 'hybrid',
            cssStyle: { background: 'linear-gradient(135deg,#22c55e,#06b6d4)' },
            image: {
                src: 'https://images.unsplash.com/photo-1600195077909-46b1e6c6e2d4?w=1200',
                alt: 'Brazilian teacher in class',
                focalPoint: { x: 0.5, y: 0.35 },
            },
            overlayCss: { background: 'linear-gradient(180deg,rgba(0,0,0,.10),rgba(0,0,0,.40))' },
        },
        defaultArtboardId: 'a1',
        artboards: [
            {
                id: 'a1',
                size: { width: 1080, height: 1350 },
                background: { kind: 'color', value: '#fff' },
                layers: [
                    {
                        id: 'photo',
                        type: 'image',
                        src: 'https://images.unsplash.com/photo-1600195077909-46b1e6c6e2d4?w=1600',
                        transform: { x: 0, y: 0, width: 1080, height: 900 },
                        fit: 'cover',
                    },
                    {
                        id: 'overlay',
                        type: 'shape',
                        shape: 'rect',
                        transform: { x: 0, y: 0, width: 1080, height: 900 },
                        fill: { kind: 'solid', color: 'rgba(34,197,94,0.35)' },
                        blendMode: 'multiply',
                    },
                    {
                        id: 'label',
                        type: 'text',
                        content: 'Study Guide • Week 1',
                        transform: { x: 100, y: 950, width: 880, height: 120 },
                        fontFamily: 'Inter, sans-serif',
                        fontSize: 64,
                        fontWeight: 900,
                        fill: '#fff',
                        align: 'center',
                    },
                ],
            },
        ],
        editableData: { overlayColor: 'rgba(34,197,94,0.35)' },
    },
    {
        version: 1,
        title: 'Travel – Luxury Stay',
        slug: 'travel-hotel-manager-ae-1',
        category: 'travel',
        tags: ['travel', 'hotel'],
        thumbnailLabel: 'Explore • Book Now',
        thumbnail: {
            type: 'hybrid',
            cssStyle: { background: 'linear-gradient(135deg,#06b6d4,#6366f1)' },
            image: {
                src: 'https://images.unsplash.com/photo-1521782462922-5a2a94f4a0f6?w=1200',
                alt: 'Hotel manager in lobby',
                focalPoint: { x: 0.5, y: 0.4 },
            },
            overlayCss: { background: 'linear-gradient(180deg,rgba(0,0,0,.12),rgba(0,0,0,.45))' },
        },
        defaultArtboardId: 'a1',
        artboards: [
            {
                id: 'a1',
                size: { width: 1080, height: 1350 },
                background: { kind: 'color', value: '#fff' },
                layers: [
                    {
                        id: 'photo',
                        type: 'image',
                        src: 'https://images.unsplash.com/photo-1521782462922-5a2a94f4a0f6?w=1600',
                        transform: { x: 0, y: 0, width: 1080, height: 900 },
                        fit: 'cover',
                    },
                    {
                        id: 'overlay',
                        type: 'shape',
                        shape: 'rect',
                        transform: { x: 0, y: 0, width: 1080, height: 900 },
                        fill: { kind: 'solid', color: 'rgba(99,102,241,0.35)' },
                        blendMode: 'multiply',
                    },
                    {
                        id: 'label',
                        type: 'text',
                        content: 'Explore • Book Now',
                        transform: { x: 100, y: 960, width: 880, height: 100 },
                        fontFamily: 'Inter, sans-serif',
                        fontSize: 64,
                        fontWeight: 900,
                        fill: '#fff',
                        align: 'center',
                    },
                ],
            },
        ],
        editableData: { overlayColor: 'rgba(99,102,241,0.35)' },
    },
    {
        version: 1,
        title: 'Food – Chef’s Special',
        slug: 'food-chef-in-1',
        category: 'food',
        tags: ['food', 'chef'],
        thumbnailLabel: 'Chef’s Special • Today',
        thumbnail: {
            type: 'hybrid',
            cssStyle: { background: 'linear-gradient(135deg,#ef4444,#f59e0b)' },
            image: {
                src: 'https://images.unsplash.com/photo-1504754524776-8f4f37790ca0?w=1200',
                alt: 'Indian chef plating dish',
                focalPoint: { x: 0.5, y: 0.5 },
            },
            overlayCss: { background: 'linear-gradient(180deg,rgba(0,0,0,.10),rgba(0,0,0,.45))' },
        },
        defaultArtboardId: 'a1',
        artboards: [
            {
                id: 'a1',
                size: { width: 1080, height: 1350 },
                background: { kind: 'color', value: '#fff' },
                layers: [
                    {
                        id: 'photo',
                        type: 'image',
                        src: 'https://images.unsplash.com/photo-1504754524776-8f4f37790ca0?w=1600',
                        transform: { x: 0, y: 0, width: 1080, height: 900 },
                        fit: 'cover',
                    },
                    {
                        id: 'overlay',
                        type: 'shape',
                        shape: 'rect',
                        transform: { x: 0, y: 0, width: 1080, height: 900 },
                        fill: { kind: 'solid', color: 'rgba(245,158,11,0.35)' },
                        blendMode: 'multiply',
                    },
                    {
                        id: 'label',
                        type: 'text',
                        content: 'Chef’s Special • Today',
                        transform: { x: 100, y: 960, width: 880, height: 100 },
                        fontFamily: 'Inter, sans-serif',
                        fontSize: 64,
                        fontWeight: 900,
                        fill: '#fff',
                        align: 'center',
                    },
                ],
            },
        ],
        editableData: { overlayColor: 'rgba(245,158,11,0.35)' },
    },
    {
        version: 1,
        title: 'Tech – Launch Pitch',
        slug: 'tech-founder-br-1',
        category: 'tech',
        tags: ['tech', 'startup'],
        thumbnailLabel: 'AI Inside • Try It',
        thumbnail: {
            type: 'hybrid',
            cssStyle: { background: 'linear-gradient(135deg,#0ea5e9,#6366f1)' },
            image: {
                src: 'https://images.unsplash.com/photo-1517245386807-bb43f82c33c4?w=1200',
                alt: 'Brazilian founder pitching',
                focalPoint: { x: 0.5, y: 0.35 },
            },
            overlayCss: { background: 'linear-gradient(180deg,rgba(0,0,0,.12),rgba(0,0,0,.45))' },
        },
        defaultArtboardId: 'a1',
        artboards: [
            {
                id: 'a1',
                size: { width: 1920, height: 1080 },
                background: { kind: 'color', value: '#0b1020' },
                layers: [
                    {
                        id: 'photo',
                        type: 'image',
                        src: 'https://images.unsplash.com/photo-1517245386807-bb43f82c33c4?w=1600',
                        transform: { x: 0, y: 0, width: 1920, height: 1080 },
                        fit: 'cover',
                    },
                    {
                        id: 'overlay',
                        type: 'shape',
                        shape: 'rect',
                        transform: { x: 0, y: 0, width: 1920, height: 1080 },
                        fill: { kind: 'solid', color: 'rgba(14,165,233,0.35)' },
                        blendMode: 'multiply',
                    },
                    {
                        id: 'label',
                        type: 'text',
                        content: 'AI Inside • Try It',
                        transform: { x: 200, y: 460, width: 1520, height: 160 },
                        fontFamily: 'Inter, sans-serif',
                        fontSize: 80,
                        fontWeight: 900,
                        fill: '#fff',
                        align: 'center',
                    },
                ],
            },
        ],
        editableData: { overlayColor: 'rgba(14,165,233,0.35)' },
    },
    {
        version: 1,
        title: 'Real Estate – Open House',
        slug: 're-agent-se-1',
        category: 'realestate',
        tags: ['real estate', 'agent'],
        thumbnailLabel: 'Open House • Sat 11–2',
        thumbnail: {
            type: 'hybrid',
            cssStyle: { background: 'linear-gradient(135deg,#4f46e5,#06b6d4)' },
            image: {
                src: 'https://images.unsplash.com/photo-1523217582562-09d0def993a6?w=1200',
                alt: 'Swedish real estate agent',
                focalPoint: { x: 0.5, y: 0.4 },
            },
            overlayCss: { background: 'linear-gradient(180deg,rgba(0,0,0,.12),rgba(0,0,0,.45))' },
        },
        defaultArtboardId: 'a1',
        artboards: [
            {
                id: 'a1',
                size: { width: 1080, height: 1350 },
                background: { kind: 'color', value: '#fff' },
                layers: [
                    {
                        id: 'photo',
                        type: 'image',
                        src: 'https://images.unsplash.com/photo-1523217582562-09d0def993a6?w=1600',
                        transform: { x: 0, y: 0, width: 1080, height: 900 },
                        fit: 'cover',
                    },
                    {
                        id: 'overlay',
                        type: 'shape',
                        shape: 'rect',
                        transform: { x: 0, y: 0, width: 1080, height: 900 },
                        fill: { kind: 'solid', color: 'rgba(79,70,229,0.32)' },
                        blendMode: 'multiply',
                    },
                    {
                        id: 'label',
                        type: 'text',
                        content: 'Open House • Sat 11–2',
                        transform: { x: 100, y: 960, width: 880, height: 100 },
                        fontFamily: 'Inter, sans-serif',
                        fontSize: 64,
                        fontWeight: 900,
                        fill: '#fff',
                        align: 'center',
                    },
                ],
            },
        ],
        editableData: { overlayColor: 'rgba(79,70,229,0.32)' },
    },
    {
        version: 1,
        title: 'Medical – Wellness Campaign',
        slug: 'med-doctor-jp-1',
        category: 'medical',
        tags: ['medical', 'wellness'],
        thumbnailLabel: 'Stay Healthy • Book Today',
        thumbnail: {
            type: 'hybrid',
            cssStyle: { background: 'linear-gradient(135deg,#06b6d4,#0ea5e9)' },
            image: {
                src: 'https://images.unsplash.com/photo-1550831107-1553da8c8464?w=1200',
                alt: 'Japanese doctor with patient',
                focalPoint: { x: 0.5, y: 0.4 },
            },
            overlayCss: { background: 'linear-gradient(180deg,rgba(0,0,0,.10),rgba(0,0,0,.45))' },
        },
        defaultArtboardId: 'a1',
        artboards: [
            {
                id: 'a1',
                size: { width: 1080, height: 1350 },
                background: { kind: 'color', value: '#fff' },
                layers: [
                    {
                        id: 'photo',
                        type: 'image',
                        src: 'https://images.unsplash.com/photo-1550831107-1553da8c8464?w=1600',
                        transform: { x: 0, y: 0, width: 1080, height: 900 },
                        fit: 'cover',
                    },
                    {
                        id: 'overlay',
                        type: 'shape',
                        shape: 'rect',
                        transform: { x: 0, y: 0, width: 1080, height: 900 },
                        fill: { kind: 'solid', color: 'rgba(14,165,233,0.35)' },
                        blendMode: 'multiply',
                    },
                    {
                        id: 'label',
                        type: 'text',
                        content: 'Stay Healthy • Book Today',
                        transform: { x: 100, y: 960, width: 880, height: 100 },
                        fontFamily: 'Inter, sans-serif',
                        fontSize: 60,
                        fontWeight: 900,
                        fill: '#fff',
                        align: 'center',
                    },
                ],
            },
        ],
        editableData: { overlayColor: 'rgba(14,165,233,0.35)' },
    },
    {
        version: 1,
        title: 'E-commerce – New Arrivals',
        slug: 'ecom-fashion-ke-1',
        category: 'ecommerce',
        tags: ['ecommerce', 'fashion'],
        thumbnailLabel: 'New Arrivals • Shop Now',
        thumbnail: {
            type: 'hybrid',
            cssStyle: { background: 'linear-gradient(135deg,#f59e0b,#ef4444)' },
            image: {
                src: 'https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=1200',
                alt: 'Kenyan fashion model urban',
                focalPoint: { x: 0.5, y: 0.35 },
            },
            overlayCss: { background: 'linear-gradient(180deg,rgba(0,0,0,.12),rgba(0,0,0,.45))' },
        },
        defaultArtboardId: 'a1',
        artboards: [
            {
                id: 'a1',
                size: { width: 1080, height: 1350 },
                background: { kind: 'color', value: '#fff' },
                layers: [
                    {
                        id: 'photo',
                        type: 'image',
                        src: 'https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=1600',
                        transform: { x: 0, y: 0, width: 1080, height: 900 },
                        fit: 'cover',
                    },
                    {
                        id: 'overlay',
                        type: 'shape',
                        shape: 'rect',
                        transform: { x: 0, y: 0, width: 1080, height: 900 },
                        fill: { kind: 'solid', color: 'rgba(239,68,68,0.30)' },
                        blendMode: 'multiply',
                    },
                    {
                        id: 'label',
                        type: 'text',
                        content: 'New Arrivals • Shop Now',
                        transform: { x: 100, y: 960, width: 880, height: 100 },
                        fontFamily: 'Inter, sans-serif',
                        fontSize: 64,
                        fontWeight: 900,
                        fill: '#fff',
                        align: 'center',
                    },
                ],
            },
        ],
        editableData: { overlayColor: 'rgba(239,68,68,0.30)' },
    },
    {
        version: 1,
        title: 'Logistics – Fleet Service',
        slug: 'logistics-driver-ke-1',
        category: 'logistics',
        tags: ['logistics', 'fleet'],
        thumbnailLabel: 'Fast Delivery • Express',
        thumbnail: {
            type: 'hybrid',
            cssStyle: { background: 'linear-gradient(135deg,#111827,#f59e0b)' },
            image: {
                src: 'https://images.unsplash.com/photo-1605902711834-8b11c3c3d3f1?w=1200',
                alt: 'African truck driver',
                focalPoint: { x: 0.5, y: 0.35 },
            },
            overlayCss: { background: 'linear-gradient(180deg,rgba(0,0,0,.15),rgba(0,0,0,.45))' },
        },
        defaultArtboardId: 'a1',
        artboards: [
            {
                id: 'a1',
                size: { width: 1200, height: 628 },
                background: { kind: 'color', value: '#0b0b0b' },
                layers: [
                    {
                        id: 'photo',
                        type: 'image',
                        src: 'https://images.unsplash.com/photo-1605902711834-8b11c3c3d3f1?w=1600',
                        transform: { x: 0, y: 0, width: 1200, height: 628 },
                        fit: 'cover',
                    },
                    {
                        id: 'overlay',
                        type: 'shape',
                        shape: 'rect',
                        transform: { x: 0, y: 0, width: 1200, height: 628 },
                        fill: { kind: 'solid', color: 'rgba(245,158,11,0.30)' },
                        blendMode: 'multiply',
                    },
                    {
                        id: 'label',
                        type: 'text',
                        content: 'Fast Delivery • Express',
                        transform: { x: 120, y: 248, width: 960, height: 120 },
                        fontFamily: 'Inter, sans-serif',
                        fontSize: 64,
                        fontWeight: 900,
                        fill: '#fff',
                        align: 'center',
                    },
                ],
            },
        ],
        editableData: { overlayColor: 'rgba(245,158,11,0.30)' },
    },
    {
        version: 1,
        title: 'Campaign – Community First',
        slug: 'campaign-organizer-us-1',
        category: 'campaigns',
        tags: ['campaign', 'community'],
        thumbnailLabel: 'Be the Change • Join Us',
        thumbnail: {
            type: 'hybrid',
            cssStyle: { background: 'linear-gradient(135deg,#ef4444,#f97316)' },
            image: {
                src: 'https://images.unsplash.com/photo-1520975916090-3105956dac38?w=1200',
                alt: 'Community organizer microphone',
                focalPoint: { x: 0.5, y: 0.45 },
            },
            overlayCss: { background: 'linear-gradient(180deg,rgba(0,0,0,.12),rgba(0,0,0,.45))' },
        },
        defaultArtboardId: 'a1',
        artboards: [
            {
                id: 'a1',
                size: { width: 1080, height: 1350 },
                background: { kind: 'color', value: '#fff' },
                layers: [
                    {
                        id: 'photo',
                        type: 'image',
                        src: 'https://images.unsplash.com/photo-1520975916090-3105956dac38?w=1600',
                        transform: { x: 0, y: 0, width: 1080, height: 900 },
                        fit: 'cover',
                    },
                    {
                        id: 'overlay',
                        type: 'shape',
                        shape: 'rect',
                        transform: { x: 0, y: 0, width: 1080, height: 900 },
                        fill: { kind: 'solid', color: 'rgba(249,115,22,0.32)' },
                        blendMode: 'multiply',
                    },
                    {
                        id: 'label',
                        type: 'text',
                        content: 'Be the Change • Join Us',
                        transform: { x: 100, y: 960, width: 880, height: 100 },
                        fontFamily: 'Inter, sans-serif',
                        fontSize: 64,
                        fontWeight: 900,
                        fill: '#fff',
                        align: 'center',
                    },
                ],
            },
        ],
        editableData: { overlayColor: 'rgba(249,115,22,0.32)' },
    },
];
