export const MARKETING_INVOICES_TEMPLATES = [
    {
        version: 1,
        title: 'Marketing Flyer – Bold Sale',
        slug: 'marketing-flyer-sale-1',
        category: 'marketing',
        tags: ['flyer', 'sale', 'promotion'],
        defaultArtboardId: 'canvas-1',
        artboards: [
            {
                id: 'canvas-1',
                size: { width: 1080, height: 1920 },
                background: { kind: 'color', value: '#ffffff' },
                layers: [
                    {
                        id: 'bg-photo',
                        type: 'image',
                        src: 'https://images.unsplash.com/photo-1616627983451-1e2a7e7dc4c0?w=1200',
                        transform: { x: 0, y: 0, width: 1080, height: 1920, rotation: 0 },
                        fit: 'cover',
                        opacity: 0.6,
                        flip: { horizontal: false, vertical: false },
                        filters: { contrast: 0, brightness: 0, saturation: 0, blur: 0 },
                    },
                    {
                        id: 'headline',
                        type: 'text',
                        content: 'MEGA SALE',
                        transform: { x: 80, y: 700, width: 920, height: 120, rotation: 0 },
                        fontFamily: 'Inter, sans-serif',
                        fontSize: 120,
                        fontWeight: 900,
                        fill: '#ef4444',
                        align: 'center',
                    },
                    {
                        id: 'subtitle',
                        type: 'text',
                        content: 'Up to 70% Off All Items',
                        transform: { x: 80, y: 850, width: 920, height: 80, rotation: 0 },
                        fontFamily: 'Inter, sans-serif',
                        fontSize: 48,
                        fontWeight: 600,
                        fill: '#1e293b',
                        align: 'center',
                    },
                ],
            },
        ],
        editableData: {
            title: 'MEGA SALE',
            subtitle: 'Up to 70% Off All Items',
            accentColor: '#ef4444',
        },
    },
    {
        version: 1,
        title: 'Marketing Poster – Event Promo',
        slug: 'marketing-poster-event-1',
        category: 'marketing',
        tags: ['poster', 'event', 'concert'],
        defaultArtboardId: 'canvas-1',
        artboards: [
            {
                id: 'canvas-1',
                size: { width: 1080, height: 1350 },
                background: {
                    kind: 'gradient',
                    gradient: {
                        type: 'linear',
                        angle: 135,
                        stops: [
                            { at: 0, color: '#f59e0b' },
                            { at: 1, color: '#f43f5e' },
                        ],
                    },
                },
                layers: [
                    {
                        id: 'title',
                        type: 'text',
                        content: 'SUMMER JAM 2025',
                        transform: { x: 100, y: 480, width: 880, height: 120, rotation: 0 },
                        fontFamily: 'Inter, sans-serif',
                        fontSize: 80,
                        fontWeight: 800,
                        fill: '#ffffff',
                        align: 'center',
                    },
                    {
                        id: 'cta',
                        type: 'text',
                        content: 'Tickets Available Now!',
                        transform: { x: 100, y: 620, width: 880, height: 80, rotation: 0 },
                        fontFamily: 'Inter, sans-serif',
                        fontSize: 36,
                        fontWeight: 500,
                        fill: '#ffffff',
                        align: 'center',
                    },
                ],
            },
        ],
        editableData: {
            title: 'SUMMER JAM 2025',
            cta: 'Tickets Available Now!',
        },
    },
    {
        version: 1,
        title: 'Marketing Banner – Product Launch',
        slug: 'marketing-banner-launch-1',
        category: 'marketing',
        tags: ['banner', 'product', 'launch'],
        defaultArtboardId: 'canvas-1',
        artboards: [
            {
                id: 'canvas-1',
                size: { width: 1200, height: 600 },
                background: { kind: 'color', value: '#0f172a' },
                layers: [
                    {
                        id: 'photo',
                        type: 'image',
                        src: 'https://images.unsplash.com/photo-1581091870622-7f7e006cc3c5?w=1200',
                        transform: { x: 0, y: 0, width: 1200, height: 600, rotation: 0 },
                        fit: 'cover',
                        opacity: 0.4,
                        flip: { horizontal: false, vertical: false },
                        filters: { contrast: 0, brightness: 0, saturation: 0, blur: 0 },
                    },
                    {
                        id: 'headline',
                        type: 'text',
                        content: 'Introducing Titan X Phone',
                        transform: { x: 100, y: 200, width: 1000, height: 100, rotation: 0 },
                        fontFamily: 'Inter, sans-serif',
                        fontSize: 60,
                        fontWeight: 800,
                        fill: '#38bdf8',
                        align: 'center',
                    },
                ],
            },
        ],
        editableData: {
            title: 'Introducing Titan X Phone',
            accentColor: '#38bdf8',
        },
    },
    {
        version: 1,
        title: 'Marketing Social Ad – Tech Startup',
        slug: 'marketing-social-ad-tech-1',
        category: 'marketing',
        tags: ['social', 'tech', 'ad'],
        defaultArtboardId: 'canvas-1',
        artboards: [
            {
                id: 'canvas-1',
                size: { width: 1080, height: 1080 },
                background: { kind: 'color', value: '#1e293b' },
                layers: [
                    {
                        id: 'bg-photo',
                        type: 'image',
                        src: 'https://images.unsplash.com/photo-1581090700227-1e37b190418e?w=1200',
                        transform: { x: 0, y: 0, width: 1080, height: 1080, rotation: 0 },
                        fit: 'cover',
                        opacity: 0.5,
                        flip: { horizontal: false, vertical: false },
                        filters: { contrast: 0, brightness: 0, saturation: 0, blur: 0 },
                    },
                    {
                        id: 'text',
                        type: 'text',
                        content: 'Join the Future of Tech',
                        transform: { x: 100, y: 460, width: 880, height: 100, rotation: 0 },
                        fontFamily: 'Inter, sans-serif',
                        fontSize: 60,
                        fontWeight: 800,
                        fill: '#3b82f6',
                        align: 'center',
                    },
                ],
            },
        ],
        editableData: {
            title: 'Join the Future of Tech',
            accentColor: '#3b82f6',
        },
    },
    {
        version: 1,
        title: 'Marketing Brochure – Corporate',
        slug: 'marketing-brochure-corporate-1',
        category: 'marketing',
        tags: ['brochure', 'corporate', 'print'],
        defaultArtboardId: 'canvas-1',
        artboards: [
            {
                id: 'canvas-1',
                size: { width: 1080, height: 1528 },
                background: { kind: 'color', value: '#ffffff' },
                layers: [
                    {
                        id: 'header',
                        type: 'shape',
                        shape: 'rect',
                        transform: { x: 0, y: 0, width: 1080, height: 220, rotation: 0 },
                        fill: { kind: 'solid', color: '#0ea5e9' },
                    },
                    {
                        id: 'title',
                        type: 'text',
                        content: 'Our Services & Solutions',
                        transform: { x: 80, y: 80, width: 920, height: 100, rotation: 0 },
                        fontFamily: 'Inter, sans-serif',
                        fontSize: 52,
                        fontWeight: 700,
                        fill: '#ffffff',
                    },
                    {
                        id: 'photo',
                        type: 'image',
                        src: 'https://images.unsplash.com/photo-1593642533144-3d62aaabcbb1?w=1200',
                        transform: { x: 0, y: 300, width: 1080, height: 700, rotation: 0 },
                        fit: 'cover',
                        flip: { horizontal: false, vertical: false },
                        filters: { contrast: 0, brightness: 0, saturation: 0, blur: 0 },
                        opacity: 0.6,
                    },
                ],
            },
        ],
        editableData: {
            title: 'Our Services & Solutions',
            accentColor: '#0ea5e9',
        },
    },
    {
        version: 1,
        title: 'Invoice – Gradient Header',
        slug: 'invoice-gradient-1',
        category: 'invoice',
        tags: ['invoice', 'finance', 'document'],
        defaultArtboardId: 'canvas-1',
        artboards: [
            {
                id: 'canvas-1',
                size: { width: 1080, height: 1528 },
                background: { kind: 'color', value: '#ffffff' },
                layers: [
                    {
                        id: 'header-bg',
                        type: 'shape',
                        shape: 'rect',
                        transform: { x: 0, y: 0, width: 1080, height: 200, rotation: 0 },
                        fill: {
                            kind: 'gradient',
                            gradient: {
                                type: 'linear',
                                angle: 135,
                                stops: [
                                    { at: 0, color: '#6366f1' },
                                    { at: 1, color: '#3b82f6' },
                                ],
                            },
                        },
                    },
                    {
                        id: 'title',
                        type: 'text',
                        content: 'INVOICE',
                        transform: { x: 100, y: 80, width: 880, height: 60, rotation: 0 },
                        fontFamily: 'Inter, sans-serif',
                        fontSize: 48,
                        fontWeight: 800,
                        fill: '#ffffff',
                        align: 'center',
                    },
                ],
            },
        ],
        editableData: {
            title: 'INVOICE',
            accentColor: '#6366f1',
        },
    },
    {
        version: 1,
        title: 'Invoice – Clean Blue',
        slug: 'invoice-clean-blue-1',
        category: 'invoice',
        tags: ['invoice', 'simple', 'blue'],
        defaultArtboardId: 'canvas-1',
        artboards: [
            {
                id: 'canvas-1',
                size: { width: 1080, height: 1528 },
                background: { kind: 'color', value: '#f8fafc' },
                layers: [
                    {
                        id: 'logo',
                        type: 'image',
                        src: 'https://images.unsplash.com/photo-1629904853698-eef7db4b8a6a?w=600',
                        transform: { x: 80, y: 60, width: 120, height: 120, rotation: 0 },
                        fit: 'cover',
                        flip: { horizontal: false, vertical: false },
                        filters: { contrast: 0, brightness: 0, saturation: 0, blur: 0 },
                    },
                    {
                        id: 'title',
                        type: 'text',
                        content: 'Invoice #0001',
                        transform: { x: 300, y: 100, width: 700, height: 80, rotation: 0 },
                        fontFamily: 'Inter, sans-serif',
                        fontSize: 42,
                        fontWeight: 600,
                        fill: '#1e293b',
                    },
                ],
            },
        ],
        editableData: {
            title: 'Invoice #0001',
            accentColor: '#1e293b',
        },
    },
    {
        version: 1,
        title: 'Invoice – Modern Teal',
        slug: 'invoice-modern-teal-1',
        category: 'invoice',
        tags: ['invoice', 'modern', 'teal'],
        defaultArtboardId: 'canvas-1',
        artboards: [
            {
                id: 'canvas-1',
                size: { width: 1080, height: 1528 },
                background: { kind: 'color', value: '#ffffff' },
                layers: [
                    {
                        id: 'header',
                        type: 'shape',
                        shape: 'rect',
                        transform: { x: 0, y: 0, width: 1080, height: 180, rotation: 0 },
                        fill: { kind: 'solid', color: '#14b8a6' },
                    },
                    {
                        id: 'title',
                        type: 'text',
                        content: 'INVOICE',
                        transform: { x: 100, y: 60, width: 880, height: 60, rotation: 0 },
                        fontFamily: 'Inter, sans-serif',
                        fontSize: 42,
                        fontWeight: 700,
                        fill: '#ffffff',
                        align: 'center',
                    },
                ],
            },
        ],
        editableData: {
            title: 'INVOICE',
            accentColor: '#14b8a6',
        },
    },
    {
        version: 1,
        title: 'Invoice – Simple Minimal Gray',
        slug: 'invoice-minimal-gray-1',
        category: 'invoice',
        tags: ['invoice', 'minimal', 'gray'],
        defaultArtboardId: 'canvas-1',
        artboards: [
            {
                id: 'canvas-1',
                size: { width: 1080, height: 1528 },
                background: { kind: 'color', value: '#f9fafb' },
                layers: [
                    {
                        id: 'title',
                        type: 'text',
                        content: 'INVOICE',
                        transform: { x: 100, y: 100, width: 880, height: 80, rotation: 0 },
                        fontFamily: 'Inter, sans-serif',
                        fontSize: 42,
                        fontWeight: 700,
                        fill: '#111827',
                    },
                ],
            },
        ],
        editableData: {
            title: 'INVOICE',
            accentColor: '#111827',
        },
    },
    {
        version: 1,
        title: 'Invoice – Creative Gradient',
        slug: 'invoice-gradient-creative-1',
        category: 'invoice',
        tags: ['invoice', 'creative', 'gradient'],
        defaultArtboardId: 'canvas-1',
        artboards: [
            {
                id: 'canvas-1',
                size: { width: 1080, height: 1528 },
                background: {
                    kind: 'gradient',
                    gradient: {
                        type: 'linear',
                        angle: 120,
                        stops: [
                            { at: 0, color: '#ec4899' },
                            { at: 1, color: '#8b5cf6' },
                        ],
                    },
                },
                layers: [
                    {
                        id: 'title',
                        type: 'text',
                        content: 'INVOICE',
                        transform: { x: 100, y: 120, width: 880, height: 80, rotation: 0 },
                        fontFamily: 'Inter, sans-serif',
                        fontSize: 46,
                        fontWeight: 800,
                        fill: '#ffffff',
                        align: 'center',
                    },
                ],
            },
        ],
        editableData: {
            title: 'INVOICE',
            accentColor: '#ec4899',
        },
    },
];

export const MARKETING_INVOICES_RECORD: Record<string, Record<string, unknown>> = MARKETING_INVOICES_TEMPLATES.reduce(
    (acc, template) => {
        acc[template.slug] = template;
        return acc;
    },
    {} as Record<string, Record<string, unknown>>
);
