export const MEDICAL_TRAVEL_TEMPLATES = [
    {
        version: 1,
        title: 'Medical Poster – Health Awareness',
        slug: 'medical-awareness-1',
        category: 'medical',
        tags: ['poster', 'health', 'awareness'],
        thumbnail: {
            type: 'css',
            style: {
                background: 'linear-gradient(135deg, #22d3ee, #0ea5e9)',
                borderRadius: '12px',
                boxShadow: '0 4px 18px rgba(14,165,233,0.25)',
            },
        },
        defaultArtboardId: 'canvas-1',
        artboards: [
            {
                id: 'canvas-1',
                name: 'Medical Awareness',
                size: { width: 1080, height: 1350 },
                background: {
                    kind: 'gradient',
                    gradient: {
                        type: 'linear',
                        angle: 135,
                        stops: [
                            { at: 0, color: '#22d3ee' },
                            { at: 1, color: '#0ea5e9' },
                        ],
                    },
                },
                layers: [
                    {
                        id: 'photo',
                        type: 'image',
                        name: 'Hero Photo',
                        src: 'https://images.unsplash.com/photo-1588776814546-ec8df98d8b13?w=1600',
                        transform: { x: 0, y: 0, width: 1080, height: 720, rotation: 0 },
                        fit: 'cover',
                        opacity: 0.55,
                        flip: { horizontal: false, vertical: false },
                        filters: { contrast: 0, brightness: 0, saturation: 0, blur: 0 },
                        zIndex: 0,
                        locked: false,
                        visible: true,
                    },
                    {
                        id: 'title',
                        type: 'text',
                        name: 'Title',
                        content: 'Stay Safe, Stay Healthy',
                        transform: { x: 100, y: 800, width: 880, height: 120, rotation: 0 },
                        fontFamily: 'Inter, sans-serif',
                        fontSize: 68,
                        fontWeight: 800,
                        fill: '#ffffff',
                        align: 'center',
                        lineHeight: 1.15,
                        zIndex: 1,
                        visible: true,
                    },
                    {
                        id: 'subtitle',
                        type: 'text',
                        name: 'Subtitle',
                        content: 'Regular Checkups Save Lives',
                        transform: { x: 100, y: 920, width: 880, height: 70, rotation: 0 },
                        fontFamily: 'Inter, sans-serif',
                        fontSize: 34,
                        fontWeight: 600,
                        fill: '#e0f2fe',
                        align: 'center',
                        zIndex: 2,
                        visible: true,
                    },
                ],
            },
        ],
        editableData: {
            title: 'Stay Safe, Stay Healthy',
            subtitle: 'Regular Checkups Save Lives',
            gradient: ['#22d3ee', '#0ea5e9'],
            image: 'https://images.unsplash.com/photo-1588776814546-ec8df98d8b13?w=1600',
        },
    },
    {
        version: 1,
        title: 'Medical Flyer – Clinic Services',
        slug: 'medical-clinic-flyer-1',
        category: 'medical',
        tags: ['flyer', 'clinic', 'services'],
        thumbnail: {
            type: 'css',
            style: {
                background: 'linear-gradient(135deg, #1e40af, #3b82f6)',
                borderRadius: '12px',
                boxShadow: '0 4px 18px rgba(30,64,175,0.25)',
            },
        },
        defaultArtboardId: 'canvas-1',
        artboards: [
            {
                id: 'canvas-1',
                name: 'Clinic Flyer',
                size: { width: 1080, height: 1528 },
                background: { kind: 'color', value: '#ffffff' },
                layers: [
                    {
                        id: 'header',
                        type: 'shape',
                        name: 'Header Bar',
                        shape: 'rect',
                        transform: { x: 0, y: 0, width: 1080, height: 200, rotation: 0 },
                        fill: { kind: 'solid', color: '#3b82f6' },
                        zIndex: 0,
                    },
                    {
                        id: 'title',
                        type: 'text',
                        name: 'Clinic Name',
                        content: 'CityCare Medical Center',
                        transform: { x: 100, y: 70, width: 880, height: 80, rotation: 0 },
                        fontFamily: 'Inter, sans-serif',
                        fontSize: 48,
                        fontWeight: 800,
                        fill: '#ffffff',
                        align: 'center',
                        zIndex: 1,
                    },
                    {
                        id: 'photo',
                        type: 'image',
                        name: 'Clinic Photo',
                        src: 'https://images.unsplash.com/photo-1579154204601-01588f351e86?w=1600',
                        transform: { x: 0, y: 200, width: 1080, height: 620, rotation: 0 },
                        fit: 'cover',
                        opacity: 0.8,
                        flip: { horizontal: false, vertical: false },
                        filters: { contrast: 0, brightness: 0, saturation: 0, blur: 0 },
                        zIndex: 2,
                    },
                    {
                        id: 'services',
                        type: 'text',
                        name: 'Services List',
                        content: '• General Practice • Pediatrics • Cardiology • Pharmacy',
                        transform: { x: 120, y: 880, width: 840, height: 200, rotation: 0 },
                        fontFamily: 'Inter, sans-serif',
                        fontSize: 28,
                        fontWeight: 500,
                        fill: '#0f172a',
                        align: 'left',
                        lineLength: undefined,
                        lineHeight: 1.6,
                        zIndex: 3,
                    },
                ],
            },
        ],
        editableData: {
            title: 'CityCare Medical Center',
            services: '• General Practice • Pediatrics • Cardiology • Pharmacy',
            accentColor: '#3b82f6',
            image: 'https://images.unsplash.com/photo-1579154204601-01588f351e86?w=1600',
        },
    },
    {
        version: 1,
        title: 'Medical Social – Doctor Profile',
        slug: 'medical-doctor-profile-1',
        category: 'medical',
        tags: ['profile', 'social', 'doctor'],
        thumbnail: {
            type: 'css',
            style: {
                background: 'linear-gradient(135deg, #10b981, #22d3ee)',
                borderRadius: '12px',
                boxShadow: '0 4px 18px rgba(16,185,129,0.25)',
            },
        },
        defaultArtboardId: 'canvas-1',
        artboards: [
            {
                id: 'canvas-1',
                name: 'Doctor Profile',
                size: { width: 1080, height: 1080 },
                background: { kind: 'color', value: '#f0f9ff' },
                layers: [
                    {
                        id: 'photo',
                        type: 'image',
                        name: 'Doctor Photo',
                        src: 'https://images.unsplash.com/photo-1607746882042-944635dfe10e?w=1400',
                        transform: { x: 340, y: 120, width: 400, height: 400, rotation: 0 },
                        fit: 'cover',
                        opacity: 1,
                        flip: { horizontal: false, vertical: false },
                        filters: { contrast: 0, brightness: 0, saturation: 0, blur: 0 },
                        zIndex: 0,
                    },
                    {
                        id: 'name',
                        type: 'text',
                        name: 'Name',
                        content: 'Dr. Emily Johnson',
                        transform: { x: 80, y: 580, width: 920, height: 60, rotation: 0 },
                        fontFamily: 'Inter, sans-serif',
                        fontSize: 44,
                        fontWeight: 800,
                        fill: '#1e3a8a',
                        align: 'center',
                        zIndex: 1,
                    },
                    {
                        id: 'specialty',
                        type: 'text',
                        name: 'Specialty',
                        content: 'Cardiologist',
                        transform: { x: 80, y: 645, width: 920, height: 40, rotation: 0 },
                        fontFamily: 'Inter, sans-serif',
                        fontSize: 28,
                        fontWeight: 600,
                        fill: '#475569',
                        align: 'center',
                        zIndex: 2,
                    },
                ],
            },
        ],
        editableData: {
            name: 'Dr. Emily Johnson',
            specialty: 'Cardiologist',
            image: 'https://images.unsplash.com/photo-1607746882042-944635dfe10e?w=1400',
        },
    },
    {
        version: 1,
        title: 'Medical Appointment Card – Minimal Blue',
        slug: 'medical-appointment-card-1',
        category: 'medical',
        tags: ['appointment', 'card', 'reminder'],
        thumbnail: {
            type: 'css',
            style: {
                background: 'linear-gradient(135deg, #2563eb, #1d4ed8)',
                borderRadius: '12px',
                boxShadow: '0 4px 18px rgba(37,99,235,0.25)',
            },
        },
        defaultArtboardId: 'canvas-1',
        artboards: [
            {
                id: 'canvas-1',
                name: 'Appointment Card',
                size: { width: 1050, height: 600 },
                background: { kind: 'color', value: '#ffffff' },
                layers: [
                    {
                        id: 'header',
                        type: 'shape',
                        name: 'Header Bar',
                        shape: 'rect',
                        transform: { x: 0, y: 0, width: 1050, height: 140, rotation: 0 },
                        fill: { kind: 'solid', color: '#2563eb' },
                        zIndex: 0,
                    },
                    {
                        id: 'title',
                        type: 'text',
                        name: 'Title',
                        content: 'Appointment Reminder',
                        transform: { x: 100, y: 50, width: 850, height: 60, rotation: 0 },
                        fontFamily: 'Inter, sans-serif',
                        fontSize: 36,
                        fontWeight: 700,
                        fill: '#ffffff',
                        align: 'center',
                        zIndex: 1,
                    },
                    {
                        id: 'content',
                        type: 'text',
                        name: 'Body',
                        content: 'Your appointment is on Oct 15 at 2:30 PM',
                        transform: { x: 100, y: 230, width: 850, height: 80, rotation: 0 },
                        fontFamily: 'Inter, sans-serif',
                        fontSize: 28,
                        fontWeight: 500,
                        fill: '#0f172a',
                        align: 'center',
                        zIndex: 2,
                    },
                ],
            },
        ],
        editableData: {
            title: 'Appointment Reminder',
            content: 'Your appointment is on Oct 15 at 2:30 PM',
            accentColor: '#2563eb',
        },
    },
    {
        version: 1,
        title: 'Medical Newsletter – Gradient',
        slug: 'medical-newsletter-1',
        category: 'medical',
        tags: ['newsletter', 'email', 'health'],
        thumbnail: {
            type: 'css',
            style: {
                background: 'linear-gradient(120deg, #3b82f6, #22d3ee)',
                borderRadius: '12px',
                boxShadow: '0 4px 18px rgba(34,211,238,0.25)',
            },
        },
        defaultArtboardId: 'canvas-1',
        artboards: [
            {
                id: 'canvas-1',
                name: 'Health Digest',
                size: { width: 800, height: 1000 },
                background: {
                    kind: 'gradient',
                    gradient: {
                        type: 'linear',
                        angle: 120,
                        stops: [
                            { at: 0, color: '#3b82f6' },
                            { at: 1, color: '#22d3ee' },
                        ],
                    },
                },
                layers: [
                    {
                        id: 'headline',
                        type: 'text',
                        name: 'Headline',
                        content: 'Weekly Health Digest',
                        transform: { x: 80, y: 120, width: 640, height: 100, rotation: 0 },
                        fontFamily: 'Inter, sans-serif',
                        fontSize: 44,
                        fontWeight: 800,
                        fill: '#ffffff',
                        align: 'center',
                        zIndex: 1,
                    },
                    {
                        id: 'body',
                        type: 'text',
                        name: 'Intro',
                        content: 'Latest tips, research, and clinic updates delivered to you.',
                        transform: { x: 80, y: 240, width: 640, height: 200, rotation: 0 },
                        fontFamily: 'Inter, sans-serif',
                        fontSize: 22,
                        fontWeight: 500,
                        fill: '#f0fdfa',
                        align: 'center',
                        lineHeight: 1.6,
                        zIndex: 2,
                    },
                ],
            },
        ],
        editableData: {
            title: 'Weekly Health Digest',
            intro: 'Latest tips, research, and clinic updates delivered to you.',
            gradient: ['#3b82f6', '#22d3ee'],
        },
    },
    {
        version: 1,
        title: 'Travel Poster – Explore Paradise',
        slug: 'travel-paradise-1',
        category: 'travel',
        tags: ['poster', 'destination', 'tropical'],
        thumbnail: {
            type: 'css',
            style: {
                background: 'linear-gradient(135deg, #22c55e, #0ea5e9)',
                borderRadius: '12px',
                boxShadow: '0 4px 18px rgba(14,165,233,0.25)',
            },
        },
        defaultArtboardId: 'canvas-1',
        artboards: [
            {
                id: 'canvas-1',
                name: 'Tropical Poster',
                size: { width: 1080, height: 1350 },
                background: { kind: 'color', value: '#fef3c7' },
                layers: [
                    {
                        id: 'photo',
                        type: 'image',
                        name: 'Beach Photo',
                        src: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=1600',
                        transform: { x: 0, y: 0, width: 1080, height: 900, rotation: 0 },
                        fit: 'cover',
                        opacity: 0.85,
                        flip: { horizontal: false, vertical: false },
                        filters: { contrast: 0, brightness: 0, saturation: 0, blur: 0 },
                        zIndex: 0,
                    },
                    {
                        id: 'title',
                        type: 'text',
                        name: 'Title',
                        content: 'Explore Bali',
                        transform: { x: 100, y: 960, width: 880, height: 110, rotation: 0 },
                        fontFamily: 'Inter, sans-serif',
                        fontSize: 82,
                        fontWeight: 900,
                        fill: '#ea580c',
                        align: 'center',
                        zIndex: 1,
                    },
                ],
            },
        ],
        editableData: {
            title: 'Explore Bali',
            accentColor: '#ea580c',
            image: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=1600',
        },
    },
    {
        version: 1,
        title: 'Travel Story – Gradient Adventure',
        slug: 'travel-story-1',
        category: 'travel',
        tags: ['story', 'gradient', 'travel'],
        thumbnail: {
            type: 'css',
            style: {
                background: 'linear-gradient(135deg, #14b8a6, #0ea5e9)',
                borderRadius: '12px',
                boxShadow: '0 4px 18px rgba(20,184,166,0.25)',
            },
        },
        defaultArtboardId: 'canvas-1',
        artboards: [
            {
                id: 'canvas-1',
                name: 'Travel Story',
                size: { width: 1080, height: 1920 },
                background: {
                    kind: 'gradient',
                    gradient: {
                        type: 'linear',
                        angle: 135,
                        stops: [
                            { at: 0, color: '#14b8a6' },
                            { at: 1, color: '#0ea5e9' },
                        ],
                    },
                },
                layers: [
                    {
                        id: 'title',
                        type: 'text',
                        name: 'Title',
                        content: 'Adventure Awaits!',
                        transform: { x: 100, y: 840, width: 880, height: 120, rotation: 0 },
                        fontFamily: 'Inter, sans-serif',
                        fontSize: 84,
                        fontWeight: 900,
                        fill: '#ffffff',
                        align: 'center',
                        zIndex: 1,
                    },
                    {
                        id: 'cta',
                        type: 'shape',
                        name: 'CTA Button',
                        shape: 'rect',
                        transform: { x: 290, y: 1220, width: 500, height: 100, rotation: 0 },
                        fill: { kind: 'solid', color: '#ffffff' },
                        cornerRadius: 50,
                        zIndex: 2,
                    },
                    {
                        id: 'cta-text',
                        type: 'text',
                        name: 'CTA Text',
                        content: 'Book Now',
                        transform: { x: 290, y: 1240, width: 500, height: 60, rotation: 0 },
                        fontFamily: 'Inter, sans-serif',
                        fontSize: 30,
                        fontWeight: 700,
                        fill: '#0ea5e9',
                        align: 'center',
                        zIndex: 3,
                    },
                ],
            },
        ],
        editableData: {
            title: 'Adventure Awaits!',
            button: 'Book Now',
            gradient: ['#14b8a6', '#0ea5e9'],
        },
    },
    {
        version: 1,
        title: 'Travel Ad – Airline Promo',
        slug: 'travel-airline-promo-1',
        category: 'travel',
        tags: ['airline', 'ad', 'promo'],
        thumbnail: {
            type: 'css',
            style: {
                background: 'linear-gradient(135deg, #1e3a8a, #2563eb)',
                borderRadius: '12px',
                boxShadow: '0 4px 18px rgba(37,99,235,0.25)',
            },
        },
        defaultArtboardId: 'canvas-1',
        artboards: [
            {
                id: 'canvas-1',
                name: 'Airline Promo',
                size: { width: 1200, height: 628 },
                background: { kind: 'color', value: '#ffffff' },
                layers: [
                    {
                        id: 'photo',
                        type: 'image',
                        name: 'Plane Photo',
                        src: 'https://images.unsplash.com/photo-1529078155058-5d716f45d604?w=1600',
                        transform: { x: 0, y: 0, width: 1200, height: 628, rotation: 0 },
                        fit: 'cover',
                        opacity: 0.78,
                        flip: { horizontal: false, vertical: false },
                        filters: { contrast: 0, brightness: 0, saturation: 0, blur: 0 },
                        zIndex: 0,
                    },
                    {
                        id: 'title',
                        type: 'text',
                        name: 'Title',
                        content: 'Fly Pelican Airlines',
                        transform: { x: 100, y: 240, width: 1000, height: 110, rotation: 0 },
                        fontFamily: 'Inter, sans-serif',
                        fontSize: 64,
                        fontWeight: 900,
                        fill: '#1e3a8a',
                        align: 'center',
                        zIndex: 1,
                    },
                    {
                        id: 'subtitle',
                        type: 'text',
                        name: 'Subtitle',
                        content: 'Save up to 35% on winter routes',
                        transform: { x: 100, y: 340, width: 1000, height: 60, rotation: 0 },
                        fontFamily: 'Inter, sans-serif',
                        fontSize: 28,
                        fontWeight: 600,
                        fill: '#0f172a',
                        align: 'center',
                        zIndex: 2,
                    },
                ],
            },
        ],
        editableData: {
            title: 'Fly Pelican Airlines',
            subtitle: 'Save up to 35% on winter routes',
            accentColor: '#1e3a8a',
            image: 'https://images.unsplash.com/photo-1529078155058-5d716f45d604?w=1600',
        },
    },
    {
        version: 1,
        title: 'Travel – City Guide Card',
        slug: 'travel-city-guide-1',
        category: 'travel',
        tags: ['guide', 'city', 'map'],
        thumbnail: {
            type: 'css',
            style: {
                background: 'linear-gradient(135deg, #0ea5e9, #0369a1)',
                borderRadius: '12px',
                boxShadow: '0 4px 18px rgba(3,105,161,0.25)',
            },
        },
        defaultArtboardId: 'canvas-1',
        artboards: [
            {
                id: 'canvas-1',
                name: 'City Guide',
                size: { width: 1080, height: 1080 },
                background: { kind: 'color', value: '#f8fafc' },
                layers: [
                    {
                        id: 'photo',
                        type: 'image',
                        name: 'City Photo',
                        src: 'https://images.unsplash.com/photo-1505761671935-60b3a7427bad?w=1600',
                        transform: { x: 0, y: 0, width: 1080, height: 720, rotation: 0 },
                        fit: 'cover',
                        opacity: 1,
                        flip: { horizontal: false, vertical: false },
                        filters: { contrast: 0, brightness: 0, saturation: 0, blur: 0 },
                        zIndex: 0,
                    },
                    {
                        id: 'title',
                        type: 'text',
                        name: 'City Title',
                        content: 'Paris City Guide',
                        transform: { x: 100, y: 780, width: 880, height: 80, rotation: 0 },
                        fontFamily: 'Inter, sans-serif',
                        fontSize: 48,
                        fontWeight: 800,
                        fill: '#0f172a',
                        align: 'center',
                        zIndex: 1,
                    },
                ],
            },
        ],
        editableData: {
            title: 'Paris City Guide',
            image: 'https://images.unsplash.com/photo-1505761671935-60b3a7427bad?w=1600',
        },
    },
    {
        version: 1,
        title: 'Travel – Blog Header',
        slug: 'travel-blog-header-1',
        category: 'travel',
        tags: ['blog', 'header', 'wide'],
        thumbnail: {
            type: 'css',
            style: {
                background: 'linear-gradient(135deg, #22d3ee, #38bdf8)',
                borderRadius: '12px',
                boxShadow: '0 4px 18px rgba(34,211,238,0.25)',
            },
        },
        defaultArtboardId: 'canvas-1',
        artboards: [
            {
                id: 'canvas-1',
                name: 'Blog Header',
                size: { width: 1920, height: 720 },
                background: { kind: 'color', value: '#ffffff' },
                layers: [
                    {
                        id: 'hero',
                        type: 'image',
                        name: 'Hero Image',
                        src: 'https://images.unsplash.com/photo-1511735111819-9a3f7709049c?w=1920',
                        transform: { x: 0, y: 0, width: 1920, height: 720, rotation: 0 },
                        fit: 'cover',
                        opacity: 0.85,
                        flip: { horizontal: false, vertical: false },
                        filters: { contrast: 0, brightness: 0, saturation: 0, blur: 0 },
                        zIndex: 0,
                    },
                    {
                        id: 'title',
                        type: 'text',
                        name: 'Blog Title',
                        content: 'Wander More · Travel Stories & Guides',
                        transform: { x: 140, y: 480, width: 1640, height: 120, rotation: 0 },
                        fontFamily: 'Inter, sans-serif',
                        fontSize: 64,
                        fontWeight: 900,
                        fill: '#ffffff',
                        align: 'left',
                        zIndex: 1,
                    },
                ],
            },
        ],
        editableData: {
            title: 'Wander More · Travel Stories & Guides',
            image: 'https://images.unsplash.com/photo-1511735111819-9a3f7709049c?w=1920',
        },
    },
    {
        version: 1,
        title: 'Travel Itinerary – Minimal',
        slug: 'travel-itinerary-1',
        category: 'travel',
        tags: ['itinerary', 'schedule', 'trip'],
        thumbnail: {
            type: 'css',
            style: {
                background: 'linear-gradient(135deg, #0ea5e9, #22c55e)',
                borderRadius: '12px',
                boxShadow: '0 4px 18px rgba(34,197,94,0.25)',
            },
        },
        defaultArtboardId: 'canvas-1',
        artboards: [
            {
                id: 'canvas-1',
                name: 'Itinerary',
                size: { width: 1080, height: 1350 },
                background: { kind: 'color', value: '#ffffff' },
                layers: [
                    {
                        id: 'title',
                        type: 'text',
                        name: 'Title',
                        content: 'Weekend in Lisbon',
                        transform: { x: 100, y: 120, width: 880, height: 80, rotation: 0 },
                        fontFamily: 'Inter, sans-serif',
                        fontSize: 56,
                        fontWeight: 800,
                        fill: '#0f172a',
                        align: 'center',
                        zIndex: 1,
                    },
                    {
                        id: 'list',
                        type: 'text',
                        name: 'Plan',
                        content: 'Day 1: Alfama • Day 2: Belém • Day 3: Sintra',
                        transform: { x: 120, y: 240, width: 840, height: 200, rotation: 0 },
                        fontFamily: 'Inter, sans-serif',
                        fontSize: 28,
                        fontWeight: 500,
                        fill: '#334155',
                        align: 'left',
                        lineHeight: 1.6,
                        zIndex: 2,
                    },
                ],
            },
        ],
        editableData: {
            title: 'Weekend in Lisbon',
            plan: 'Day 1: Alfama • Day 2: Belém • Day 3: Sintra',
        },
    },
];

export const MEDICAL_TRAVEL_RECORD: Record<string, Record<string, unknown>> = MEDICAL_TRAVEL_TEMPLATES.reduce(
    (acc, template) => {
        acc[template.slug] = template;
        return acc;
    },
    {} as Record<string, Record<string, unknown>>
);
