export const PHOTOGRAPHY_CAMPAIGNS_TECH_LOGISTICS_TEMPLATES = [
    {
        version: 1,
        title: 'Photography Portfolio – Minimal Grid',
        slug: 'photo-portfolio-1',
        category: 'photography',
        tags: ['portfolio', 'grid', 'gallery'],
        thumbnail: {
            type: 'css',
            style: {
                background: 'linear-gradient(135deg, #f97316, #ec4899)',
                borderRadius: '12px',
                boxShadow: '0 4px 18px rgba(249,115,22,0.25)',
            },
        },
        defaultArtboardId: 'canvas-1',
        artboards: [
            {
                id: 'canvas-1',
                name: 'Portfolio Grid',
                size: { width: 1080, height: 1350 },
                background: { kind: 'color', value: '#ffffff' },
                layers: [
                    {
                        id: 'photo1',
                        type: 'image',
                        src: 'https://images.unsplash.com/photo-1504208434309-cb69f4fe52b0?w=1200',
                        transform: { x: 40, y: 60, width: 480, height: 480, rotation: 0 },
                        fit: 'cover',
                        opacity: 1,
                        flip: { horizontal: false, vertical: false },
                        filters: { contrast: 0, brightness: 0, saturation: 0, blur: 0 },
                    },
                    {
                        id: 'photo2',
                        type: 'image',
                        src: 'https://images.unsplash.com/photo-1526170375885-4d8ecf77b99f?w=1200',
                        transform: { x: 560, y: 60, width: 480, height: 480, rotation: 0 },
                        fit: 'cover',
                        opacity: 1,
                        flip: { horizontal: false, vertical: false },
                        filters: { contrast: 0, brightness: 0, saturation: 0, blur: 0 },
                    },
                    {
                        id: 'title',
                        type: 'text',
                        content: 'My Photography Portfolio',
                        transform: { x: 100, y: 1100, width: 880, height: 80, rotation: 0 },
                        fontFamily: 'Inter, sans-serif',
                        fontSize: 46,
                        fontWeight: 700,
                        fill: '#0f172a',
                        align: 'center',
                    },
                ],
            },
        ],
        editableData: {
            title: 'My Photography Portfolio',
        },
    },
    {
        version: 1,
        title: 'Photography Ad – Gradient Overlay',
        slug: 'photo-ad-gradient-1',
        category: 'photography',
        tags: ['ad', 'promo', 'gradient'],
        thumbnail: {
            type: 'css',
            style: {
                background: 'linear-gradient(135deg, #8b5cf6, #ec4899)',
                borderRadius: '12px',
                boxShadow: '0 4px 18px rgba(139,92,246,0.25)',
            },
        },
        defaultArtboardId: 'canvas-1',
        artboards: [
            {
                id: 'canvas-1',
                name: 'Photo Ad',
                size: { width: 1080, height: 1080 },
                background: {
                    kind: 'gradient',
                    gradient: {
                        type: 'linear',
                        angle: 135,
                        stops: [
                            { at: 0, color: '#8b5cf6' },
                            { at: 1, color: '#ec4899' },
                        ],
                    },
                },
                layers: [
                    {
                        id: 'photo',
                        type: 'image',
                        src: 'https://images.unsplash.com/photo-1526170375885-4d8ecf77b99f?w=1200',
                        transform: { x: 0, y: 0, width: 1080, height: 1080, rotation: 0 },
                        fit: 'cover',
                        opacity: 0.5,
                        flip: { horizontal: false, vertical: false },
                        filters: { contrast: 0, brightness: 0, saturation: 0, blur: 0 },
                    },
                    {
                        id: 'title',
                        type: 'text',
                        content: 'Capturing Moments that Matter',
                        transform: { x: 100, y: 480, width: 880, height: 100, rotation: 0 },
                        fontFamily: 'Inter, sans-serif',
                        fontSize: 60,
                        fontWeight: 800,
                        fill: '#ffffff',
                        align: 'center',
                    },
                ],
            },
        ],
        editableData: {
            title: 'Capturing Moments that Matter',
        },
    },
    {
        version: 1,
        title: 'Campaign Poster – Social Awareness',
        slug: 'campaign-awareness-1',
        category: 'campaigns',
        tags: ['poster', 'social', 'awareness'],
        thumbnail: {
            type: 'css',
            style: {
                background: 'linear-gradient(135deg, #ef4444, #f97316)',
                borderRadius: '12px',
                boxShadow: '0 4px 18px rgba(249,115,22,0.25)',
            },
        },
        defaultArtboardId: 'canvas-1',
        artboards: [
            {
                id: 'canvas-1',
                name: 'Awareness Poster',
                size: { width: 1080, height: 1350 },
                background: { kind: 'color', value: '#fef2f2' },
                layers: [
                    {
                        id: 'title',
                        type: 'text',
                        content: 'Stop Pollution • Save Earth',
                        transform: { x: 100, y: 520, width: 880, height: 120, rotation: 0 },
                        fontFamily: 'Inter, sans-serif',
                        fontSize: 64,
                        fontWeight: 900,
                        fill: '#dc2626',
                        align: 'center',
                    },
                    {
                        id: 'subtitle',
                        type: 'text',
                        content: 'Join our global movement today',
                        transform: { x: 100, y: 650, width: 880, height: 80, rotation: 0 },
                        fontFamily: 'Inter, sans-serif',
                        fontSize: 36,
                        fontWeight: 600,
                        fill: '#1e293b',
                        align: 'center',
                    },
                ],
            },
        ],
        editableData: {
            title: 'Stop Pollution • Save Earth',
            subtitle: 'Join our global movement today',
            accentColor: '#dc2626',
        },
    },
    {
        version: 1,
        title: 'Campaign Story – Inspire Change',
        slug: 'campaign-story-1',
        category: 'campaigns',
        tags: ['story', 'activism', 'movement'],
        thumbnail: {
            type: 'css',
            style: {
                background: 'linear-gradient(135deg, #ef4444, #f59e0b)',
                borderRadius: '12px',
                boxShadow: '0 4px 18px rgba(245,158,11,0.25)',
            },
        },
        defaultArtboardId: 'canvas-1',
        artboards: [
            {
                id: 'canvas-1',
                name: 'Campaign Story',
                size: { width: 1080, height: 1920 },
                background: {
                    kind: 'gradient',
                    gradient: {
                        type: 'linear',
                        angle: 135,
                        stops: [
                            { at: 0, color: '#ef4444' },
                            { at: 1, color: '#f97316' },
                        ],
                    },
                },
                layers: [
                    {
                        id: 'title',
                        type: 'text',
                        content: 'Be the Voice of Change',
                        transform: { x: 100, y: 860, width: 880, height: 120, rotation: 0 },
                        fontFamily: 'Inter, sans-serif',
                        fontSize: 80,
                        fontWeight: 900,
                        fill: '#ffffff',
                        align: 'center',
                    },
                ],
            },
        ],
        editableData: {
            title: 'Be the Voice of Change',
            gradient: ['#ef4444', '#f97316'],
        },
    },
    {
        version: 1,
        title: 'Tech Banner – App Launch',
        slug: 'tech-banner-1',
        category: 'tech',
        tags: ['tech', 'banner', 'app'],
        thumbnail: {
            type: 'css',
            style: {
                background: 'linear-gradient(135deg, #2563eb, #0ea5e9)',
                borderRadius: '12px',
                boxShadow: '0 4px 18px rgba(37,99,235,0.25)',
            },
        },
        defaultArtboardId: 'canvas-1',
        artboards: [
            {
                id: 'canvas-1',
                name: 'Tech Banner',
                size: { width: 1200, height: 600 },
                background: { kind: 'color', value: '#0f172a' },
                layers: [
                    {
                        id: 'photo',
                        type: 'image',
                        src: 'https://images.unsplash.com/photo-1556741533-f6acd647a2c9?w=1600',
                        transform: { x: 0, y: 0, width: 1200, height: 600, rotation: 0 },
                        fit: 'cover',
                        opacity: 0.3,
                        flip: { horizontal: false, vertical: false },
                        filters: { contrast: 0, brightness: 0, saturation: 0, blur: 0 },
                    },
                    {
                        id: 'title',
                        type: 'text',
                        content: 'Introducing Dropple AI Tools',
                        transform: { x: 100, y: 240, width: 1000, height: 120, rotation: 0 },
                        fontFamily: 'Inter, sans-serif',
                        fontSize: 56,
                        fontWeight: 800,
                        fill: '#38bdf8',
                        align: 'center',
                    },
                ],
            },
        ],
        editableData: {
            title: 'Introducing Dropple AI Tools',
            accentColor: '#38bdf8',
        },
    },
    {
        version: 1,
        title: 'Tech Presentation – Data Visualization',
        slug: 'tech-presentation-1',
        category: 'tech',
        tags: ['presentation', 'data', 'slides'],
        thumbnail: {
            type: 'css',
            style: {
                background: 'linear-gradient(135deg, #0ea5e9, #22d3ee)',
                borderRadius: '12px',
                boxShadow: '0 4px 18px rgba(34,211,238,0.25)',
            },
        },
        defaultArtboardId: 'canvas-1',
        artboards: [
            {
                id: 'canvas-1',
                name: 'Presentation Slide',
                size: { width: 1920, height: 1080 },
                background: { kind: 'color', value: '#ffffff' },
                layers: [
                    {
                        id: 'header',
                        type: 'shape',
                        shape: 'rect',
                        transform: { x: 0, y: 0, width: 1920, height: 200, rotation: 0 },
                        fill: { kind: 'solid', color: '#2563eb' },
                    },
                    {
                        id: 'title',
                        type: 'text',
                        content: 'Tech Trends 2025',
                        transform: { x: 160, y: 60, width: 1600, height: 100, rotation: 0 },
                        fontFamily: 'Inter, sans-serif',
                        fontSize: 72,
                        fontWeight: 800,
                        fill: '#ffffff',
                        align: 'center',
                    },
                ],
            },
        ],
        editableData: {
            title: 'Tech Trends 2025',
            accentColor: '#2563eb',
        },
    },
    {
        version: 1,
        title: 'Logistics Banner – Transport Company',
        slug: 'logistics-banner-1',
        category: 'logistics',
        tags: ['banner', 'transport', 'cargo'],
        thumbnail: {
            type: 'css',
            style: {
                background: 'linear-gradient(135deg, #facc15, #f59e0b)',
                borderRadius: '12px',
                boxShadow: '0 4px 18px rgba(250,204,21,0.25)',
            },
        },
        defaultArtboardId: 'canvas-1',
        artboards: [
            {
                id: 'canvas-1',
                name: 'Transport Banner',
                size: { width: 1200, height: 628 },
                background: { kind: 'color', value: '#111827' },
                layers: [
                    {
                        id: 'photo',
                        type: 'image',
                        src: 'https://images.unsplash.com/photo-1616091093708-5b1b5c80e1c7?w=1600',
                        transform: { x: 0, y: 0, width: 1200, height: 628, rotation: 0 },
                        fit: 'cover',
                        opacity: 0.7,
                        flip: { horizontal: false, vertical: false },
                        filters: { contrast: 0, brightness: 0, saturation: 0, blur: 0 },
                    },
                    {
                        id: 'title',
                        type: 'text',
                        content: 'Pelican Express Logistics',
                        transform: { x: 100, y: 240, width: 1000, height: 100, rotation: 0 },
                        fontFamily: 'Inter, sans-serif',
                        fontSize: 64,
                        fontWeight: 800,
                        fill: '#facc15',
                        align: 'center',
                    },
                ],
            },
        ],
        editableData: {
            title: 'Pelican Express Logistics',
            accentColor: '#facc15',
            image: 'https://images.unsplash.com/photo-1616091093708-5b1b5c80e1c7?w=1600',
        },
    },
    {
        version: 1,
        title: 'Logistics Poster – Fleet Promotion',
        slug: 'logistics-fleet-1',
        category: 'logistics',
        tags: ['fleet', 'poster', 'promotion'],
        thumbnail: {
            type: 'css',
            style: {
                background: 'linear-gradient(135deg, #facc15, #fde68a)',
                borderRadius: '12px',
                boxShadow: '0 4px 18px rgba(253,230,138,0.25)',
            },
        },
        defaultArtboardId: 'canvas-1',
        artboards: [
            {
                id: 'canvas-1',
                name: 'Fleet Poster',
                size: { width: 1080, height: 1350 },
                background: { kind: 'color', value: '#f8fafc' },
                layers: [
                    {
                        id: 'photo',
                        type: 'image',
                        src: 'https://images.unsplash.com/photo-1597006290913-5c35c6f7a658?w=1600',
                        transform: { x: 0, y: 0, width: 1080, height: 720, rotation: 0 },
                        fit: 'cover',
                        opacity: 1,
                        flip: { horizontal: false, vertical: false },
                        filters: { contrast: 0, brightness: 0, saturation: 0, blur: 0 },
                    },
                    {
                        id: 'title',
                        type: 'text',
                        content: 'Fast • Reliable • Global',
                        transform: { x: 80, y: 800, width: 920, height: 80, rotation: 0 },
                        fontFamily: 'Inter, sans-serif',
                        fontSize: 60,
                        fontWeight: 800,
                        fill: '#0f172a',
                        align: 'center',
                    },
                ],
            },
        ],
        editableData: {
            title: 'Fast • Reliable • Global',
            image: 'https://images.unsplash.com/photo-1597006290913-5c35c6f7a658?w=1600',
        },
    },
    {
        version: 1,
        title: 'Logistics Business Card – Professional',
        slug: 'logistics-card-1',
        category: 'logistics',
        tags: ['business card', 'fleet'],
        thumbnail: {
            type: 'css',
            style: {
                background: 'linear-gradient(135deg, #facc15, #fcd34d)',
                borderRadius: '12px',
                boxShadow: '0 4px 18px rgba(252,211,77,0.25)',
            },
        },
        defaultArtboardId: 'canvas-1',
        artboards: [
            {
                id: 'canvas-1',
                name: 'Business Card',
                size: { width: 1050, height: 600 },
                background: { kind: 'color', value: '#ffffff' },
                layers: [
                    {
                        id: 'panel',
                        type: 'shape',
                        shape: 'rect',
                        transform: { x: 0, y: 0, width: 300, height: 600, rotation: 0 },
                        fill: { kind: 'solid', color: '#facc15' },
                    },
                    {
                        id: 'name',
                        type: 'text',
                        content: 'Samuel Endeley',
                        transform: { x: 360, y: 160, width: 640, height: 80, rotation: 0 },
                        fontFamily: 'Inter, sans-serif',
                        fontSize: 40,
                        fontWeight: 800,
                        fill: '#0f172a',
                    },
                    {
                        id: 'role',
                        type: 'text',
                        content: 'Fleet Operations Manager',
                        transform: { x: 360, y: 240, width: 640, height: 60, rotation: 0 },
                        fontFamily: 'Inter, sans-serif',
                        fontSize: 26,
                        fontWeight: 500,
                        fill: '#475569',
                    },
                ],
            },
        ],
        editableData: {
            name: 'Samuel Endeley',
            role: 'Fleet Operations Manager',
            accentColor: '#facc15',
        },
    },
    {
        version: 1,
        title: 'Logistics – Truck Livery Preview',
        slug: 'logistics-truck-livery-1',
        category: 'logistics',
        tags: ['truck', 'design', 'preview'],
        thumbnail: {
            type: 'css',
            style: {
                background: 'linear-gradient(135deg, #1e293b, #334155)',
                borderRadius: '12px',
                boxShadow: '0 4px 18px rgba(30,41,59,0.25)',
            },
        },
        defaultArtboardId: 'canvas-1',
        artboards: [
            {
                id: 'canvas-1',
                name: 'Truck Preview',
                size: { width: 1920, height: 1080 },
                background: { kind: 'color', value: '#1e293b' },
                layers: [
                    {
                        id: 'truck',
                        type: 'image',
                        src: 'https://images.unsplash.com/photo-1578575437130-527eed3abbec?w=1600',
                        transform: { x: 0, y: 200, width: 1920, height: 680, rotation: 0 },
                        fit: 'contain',
                        opacity: 1,
                        flip: { horizontal: false, vertical: false },
                        filters: { contrast: 0, brightness: 0, saturation: 0, blur: 0 },
                    },
                    {
                        id: 'brand',
                        type: 'text',
                        content: 'Pelican Express Fleet',
                        transform: { x: 160, y: 80, width: 1600, height: 100, rotation: 0 },
                        fontFamily: 'Inter, sans-serif',
                        fontSize: 72,
                        fontWeight: 800,
                        fill: '#facc15',
                        align: 'center',
                    },
                ],
            },
        ],
        editableData: {
            title: 'Pelican Express Fleet',
            accentColor: '#facc15',
            image: 'https://images.unsplash.com/photo-1578575437130-527eed3abbec?w=1600',
        },
    },
    {
        version: 1,
        title: 'Tech Startup – Product Launch',
        slug: 'tech-launch-1',
        category: 'tech',
        tags: ['startup', 'launch', 'innovation'],
        thumbnail: {
            type: 'css',
            style: {
                background: 'linear-gradient(135deg, #0ea5e9, #7c3aed)',
                borderRadius: '12px',
                boxShadow: '0 4px 18px rgba(14,165,233,0.25)',
            },
        },
        defaultArtboardId: 'canvas-1',
        artboards: [
            {
                id: 'canvas-1',
                name: 'Launch Page',
                size: { width: 1920, height: 1080 },
                background: {
                    kind: 'gradient',
                    gradient: {
                        type: 'linear',
                        angle: 135,
                        stops: [
                            { at: 0, color: '#0ea5e9' },
                            { at: 1, color: '#7c3aed' },
                        ],
                    },
                },
                layers: [
                    {
                        id: 'title',
                        type: 'text',
                        content: 'Introducing Dropple Workspace',
                        transform: { x: 160, y: 420, width: 1600, height: 120, rotation: 0 },
                        fontFamily: 'Inter, sans-serif',
                        fontSize: 84,
                        fontWeight: 800,
                        fill: '#ffffff',
                        align: 'center',
                    },
                    {
                        id: 'subtitle',
                        type: 'text',
                        content: 'Create, collaborate, and launch faster than ever',
                        transform: { x: 160, y: 560, width: 1600, height: 80, rotation: 0 },
                        fontFamily: 'Inter, sans-serif',
                        fontSize: 36,
                        fontWeight: 500,
                        fill: '#e0e7ff',
                        align: 'center',
                    },
                ],
            },
        ],
        editableData: {
            title: 'Introducing Dropple Workspace',
            subtitle: 'Create, collaborate, and launch faster than ever',
            gradient: ['#0ea5e9', '#7c3aed'],
        },
    },
    {
        version: 1,
        title: 'Transport Analytics Dashboard',
        slug: 'logistics-dashboard-1',
        category: 'logistics',
        tags: ['dashboard', 'analytics', 'enterprise'],
        thumbnail: {
            type: 'css',
            style: {
                background: 'linear-gradient(135deg, #1e293b, #0f172a)',
                borderRadius: '12px',
                boxShadow: '0 4px 18px rgba(15,23,42,0.25)',
            },
        },
        defaultArtboardId: 'canvas-1',
        artboards: [
            {
                id: 'canvas-1',
                name: 'Analytics Dashboard',
                size: { width: 1920, height: 1080 },
                background: { kind: 'color', value: '#ffffff' },
                layers: [
                    {
                        id: 'header',
                        type: 'shape',
                        shape: 'rect',
                        transform: { x: 0, y: 0, width: 1920, height: 120, rotation: 0 },
                        fill: { kind: 'solid', color: '#1e293b' },
                    },
                    {
                        id: 'title',
                        type: 'text',
                        content: 'Fleet Performance Overview',
                        transform: { x: 100, y: 40, width: 1720, height: 60, rotation: 0 },
                        fontFamily: 'Inter, sans-serif',
                        fontSize: 40,
                        fontWeight: 700,
                        fill: '#facc15',
                        align: 'center',
                    },
                    {
                        id: 'chart-placeholder',
                        type: 'shape',
                        shape: 'rect',
                        transform: { x: 200, y: 200, width: 1520, height: 600, rotation: 0 },
                        fill: { kind: 'solid', color: '#f1f5f9' },
                    },
                ],
            },
        ],
        editableData: {
            title: 'Fleet Performance Overview',
            accentColor: '#facc15',
        },
    },
    {
        version: 1,
        title: 'Photography Moodboard – Creative Layout',
        slug: 'photo-moodboard-1',
        category: 'photography',
        tags: ['moodboard', 'layout', 'creative'],
        thumbnail: {
            type: 'css',
            style: {
                background: 'linear-gradient(135deg, #f97316, #0ea5e9)',
                borderRadius: '12px',
                boxShadow: '0 4px 18px rgba(14,165,233,0.25)',
            },
        },
        defaultArtboardId: 'canvas-1',
        artboards: [
            {
                id: 'canvas-1',
                name: 'Moodboard Layout',
                size: { width: 1920, height: 1080 },
                background: { kind: 'color', value: '#f8fafc' },
                layers: [
                    {
                        id: 'photo1',
                        type: 'image',
                        src: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=800',
                        transform: { x: 120, y: 160, width: 400, height: 400, rotation: -5 },
                        fit: 'cover',
                        opacity: 1,
                        flip: { horizontal: false, vertical: false },
                        filters: { contrast: 0, brightness: 0, saturation: 0, blur: 0 },
                    },
                    {
                        id: 'photo2',
                        type: 'image',
                        src: 'https://images.unsplash.com/photo-1526170375885-4d8ecf77b99f?w=800',
                        transform: { x: 600, y: 240, width: 400, height: 400, rotation: 3 },
                        fit: 'cover',
                        opacity: 1,
                        flip: { horizontal: false, vertical: false },
                        filters: { contrast: 0, brightness: 0, saturation: 0, blur: 0 },
                    },
                    {
                        id: 'title',
                        type: 'text',
                        content: 'Creative Moodboard',
                        transform: { x: 1100, y: 460, width: 720, height: 100, rotation: 0 },
                        fontFamily: 'Inter, sans-serif',
                        fontSize: 72,
                        fontWeight: 800,
                        fill: '#0f172a',
                    },
                ],
            },
        ],
        editableData: {
            title: 'Creative Moodboard',
        },
    },
];

export const PHOTOGRAPHY_CAMPAIGNS_TECH_LOGISTICS_RECORD: Record<string, Record<string, unknown>> =
    PHOTOGRAPHY_CAMPAIGNS_TECH_LOGISTICS_TEMPLATES.reduce(
        (acc, template) => {
            acc[template.slug] = template;
            return acc;
        },
        {} as Record<string, Record<string, unknown>>
    );
