export const REAL_ESTATE_FOOD_TEMPLATES = [
    {
        version: 1,
        title: 'Real Estate Listing – Modern Home',
        slug: 'realestate-listing-modern-1',
        category: 'realestate',
        tags: ['listing', 'property', 'sale'],
        defaultArtboardId: 'canvas-1',
        artboards: [
            {
                id: 'canvas-1',
                size: { width: 1080, height: 1080 },
                background: { kind: 'color', value: '#ffffff' },
                layers: [
                    {
                        id: 'photo',
                        type: 'image',
                        src: 'https://images.unsplash.com/photo-1600585154526-990dced4db0d?w=1600',
                        transform: { x: 0, y: 0, width: 1080, height: 720, rotation: 0 },
                        fit: 'cover',
                        flip: { horizontal: false, vertical: false },
                        filters: { contrast: 0, brightness: 0, saturation: 0, blur: 0 },
                        opacity: 1,
                        zIndex: 0,
                    },
                    {
                        id: 'title',
                        type: 'text',
                        content: '3 Bed • 2 Bath • 1,850 sqft',
                        transform: { x: 80, y: 760, width: 920, height: 60, rotation: 0 },
                        fontFamily: 'Inter, sans-serif',
                        fontSize: 36,
                        fontWeight: 700,
                        fill: '#0f172a',
                        align: 'center',
                        zIndex: 1,
                    },
                    {
                        id: 'price',
                        type: 'text',
                        content: '$549,000',
                        transform: { x: 80, y: 820, width: 920, height: 60, rotation: 0 },
                        fontFamily: 'Inter, sans-serif',
                        fontSize: 48,
                        fontWeight: 800,
                        fill: '#22c55e',
                        align: 'center',
                        zIndex: 2,
                    },
                    {
                        id: 'location',
                        type: 'text',
                        content: 'Maple Street, Austin TX',
                        transform: { x: 80, y: 890, width: 920, height: 50, rotation: 0 },
                        fontFamily: 'Inter, sans-serif',
                        fontSize: 28,
                        fontWeight: 500,
                        fill: '#475569',
                        align: 'center',
                        zIndex: 3,
                    },
                ],
            },
        ],
        editableData: {
            features: '3 Bed • 2 Bath • 1,850 sqft',
            price: '$549,000',
            location: 'Maple Street, Austin TX',
            image: 'https://images.unsplash.com/photo-1600585154526-990dced4db0d?w=1600',
            accentColor: '#22c55e',
        },
    },
    {
        version: 1,
        title: 'Real Estate Flyer – Open House',
        slug: 'realestate-open-house-1',
        category: 'realestate',
        tags: ['flyer', 'open house', 'event'],
        defaultArtboardId: 'canvas-1',
        artboards: [
            {
                id: 'canvas-1',
                size: { width: 1080, height: 1350 },
                background: { kind: 'color', value: '#f8fafc' },
                layers: [
                    {
                        id: 'photo',
                        type: 'image',
                        src: 'https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=1600',
                        transform: { x: 0, y: 0, width: 1080, height: 700, rotation: 0 },
                        fit: 'cover',
                        flip: { horizontal: false, vertical: false },
                        filters: { contrast: 0, brightness: 0, saturation: 0, blur: 0 },
                        zIndex: 0,
                    },
                    {
                        id: 'bar',
                        type: 'shape',
                        shape: 'rect',
                        transform: { x: 0, y: 700, width: 1080, height: 80, rotation: 0 },
                        fill: { kind: 'solid', color: '#3b82f6' },
                        zIndex: 1,
                    },
                    {
                        id: 'headline',
                        type: 'text',
                        content: 'OPEN HOUSE • SAT 2–5 PM',
                        transform: { x: 80, y: 710, width: 920, height: 60, rotation: 0 },
                        fontFamily: 'Inter, sans-serif',
                        fontSize: 32,
                        fontWeight: 800,
                        fill: '#ffffff',
                        align: 'center',
                        zIndex: 2,
                    },
                    {
                        id: 'address',
                        type: 'text',
                        content: '1249 Cedar Ave, Seattle WA',
                        transform: { x: 80, y: 820, width: 920, height: 60, rotation: 0 },
                        fontFamily: 'Inter, sans-serif',
                        fontSize: 34,
                        fontWeight: 700,
                        fill: '#0f172a',
                        align: 'center',
                        zIndex: 3,
                    },
                ],
            },
        ],
        editableData: {
            headline: 'OPEN HOUSE • SAT 2–5 PM',
            address: '1249 Cedar Ave, Seattle WA',
            accentColor: '#3b82f6',
            image: 'https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=1600',
        },
    },
    {
        version: 1,
        title: 'Real Estate – Agent Business Card',
        slug: 'realestate-agent-card-1',
        category: 'realestate',
        tags: ['business card', 'agent', 'identity'],
        defaultArtboardId: 'canvas-1',
        artboards: [
            {
                id: 'canvas-1',
                size: { width: 1050, height: 600 },
                background: { kind: 'color', value: '#ffffff' },
                layers: [
                    {
                        id: 'panel',
                        type: 'shape',
                        shape: 'rect',
                        transform: { x: 0, y: 0, width: 360, height: 600, rotation: 0 },
                        fill: { kind: 'solid', color: '#0ea5e9' },
                    },
                    {
                        id: 'photo',
                        type: 'image',
                        src: 'https://images.unsplash.com/photo-1527980965255-d3b416303d12?w=600',
                        transform: { x: 110, y: 220, width: 140, height: 140, rotation: 0 },
                        fit: 'cover',
                        flip: { horizontal: false, vertical: false },
                        filters: { contrast: 0, brightness: 0, saturation: 0, blur: 0 },
                    },
                    {
                        id: 'name',
                        type: 'text',
                        content: 'Alex Morgan',
                        transform: { x: 420, y: 160, width: 560, height: 60, rotation: 0 },
                        fontFamily: 'Inter, sans-serif',
                        fontSize: 40,
                        fontWeight: 800,
                        fill: '#0f172a',
                        align: 'left',
                    },
                    {
                        id: 'role',
                        type: 'text',
                        content: 'Licensed Realtor®',
                        transform: { x: 420, y: 220, width: 560, height: 40, rotation: 0 },
                        fontFamily: 'Inter, sans-serif',
                        fontSize: 22,
                        fontWeight: 500,
                        fill: '#475569',
                        align: 'left',
                    },
                    {
                        id: 'contact',
                        type: 'text',
                        content: 'alex@estate.com • (555) 123-4567',
                        transform: { x: 420, y: 280, width: 560, height: 40, rotation: 0 },
                        fontFamily: 'Inter, sans-serif',
                        fontSize: 20,
                        fontWeight: 500,
                        fill: '#334155',
                        align: 'left',
                    },
                ],
            },
        ],
        editableData: {
            name: 'Alex Morgan',
            role: 'Licensed Realtor®',
            contact: 'alex@estate.com • (555) 123-4567',
            panelColor: '#0ea5e9',
            photo: 'https://images.unsplash.com/photo-1527980965255-d3b416303d12?w=600',
        },
    },
    {
        version: 1,
        title: 'Real Estate – Property Carousel',
        slug: 'realestate-carousel-1',
        category: 'realestate',
        tags: ['carousel', 'listing', 'wide'],
        defaultArtboardId: 'canvas-1',
        artboards: [
            {
                id: 'canvas-1',
                size: { width: 1920, height: 1080 },
                background: { kind: 'color', value: '#0f172a' },
                layers: [
                    {
                        id: 'photo',
                        type: 'image',
                        src: 'https://images.unsplash.com/photo-1502005229762-cf1b2da7c549?w=2000',
                        transform: { x: 0, y: 0, width: 1920, height: 1080, rotation: 0 },
                        fit: 'cover',
                        opacity: 0.5,
                        flip: { horizontal: false, vertical: false },
                        filters: { contrast: 0, brightness: 0, saturation: 0, blur: 0 },
                        zIndex: 0,
                    },
                    {
                        id: 'title',
                        type: 'text',
                        content: 'Luxury Downtown Condo',
                        transform: { x: 160, y: 420, width: 1600, height: 100, rotation: 0 },
                        fontFamily: 'Inter, sans-serif',
                        fontSize: 72,
                        fontWeight: 800,
                        fill: '#38bdf8',
                        align: 'center',
                        zIndex: 1,
                    },
                    {
                        id: 'price',
                        type: 'text',
                        content: '$1,250,000',
                        transform: { x: 160, y: 510, width: 1600, height: 80, rotation: 0 },
                        fontFamily: 'Inter, sans-serif',
                        fontSize: 56,
                        fontWeight: 700,
                        fill: '#e2e8f0',
                        align: 'center',
                        zIndex: 2,
                    },
                ],
            },
        ],
        editableData: {
            title: 'Luxury Downtown Condo',
            price: '$1,250,000',
            accentColor: '#38bdf8',
            image: 'https://images.unsplash.com/photo-1502005229762-cf1b2da7c549?w=2000',
        },
    },
    {
        version: 1,
        title: 'Real Estate – Agent Profile Banner',
        slug: 'realestate-agent-banner-1',
        category: 'realestate',
        tags: ['banner', 'linkedin', 'profile'],
        defaultArtboardId: 'canvas-1',
        artboards: [
            {
                id: 'canvas-1',
                size: { width: 1584, height: 396 },
                background: { kind: 'color', value: '#1e293b' },
                layers: [
                    {
                        id: 'bg',
                        type: 'image',
                        src: 'https://images.unsplash.com/photo-1501183638710-841dd1904471?w=2000',
                        transform: { x: 0, y: 0, width: 1584, height: 396, rotation: 0 },
                        fit: 'cover',
                        opacity: 0.45,
                        flip: { horizontal: false, vertical: false },
                        filters: { contrast: 0, brightness: 0, saturation: 0, blur: 0 },
                    },
                    {
                        id: 'text',
                        type: 'text',
                        content: 'Your Trusted Real Estate Partner',
                        transform: { x: 120, y: 140, width: 1344, height: 100, rotation: 0 },
                        fontFamily: 'Inter, sans-serif',
                        fontSize: 56,
                        fontWeight: 800,
                        fill: '#ffffff',
                        align: 'center',
                    },
                ],
            },
        ],
        editableData: {
            title: 'Your Trusted Real Estate Partner',
            image: 'https://images.unsplash.com/photo-1501183638710-841dd1904471?w=2000',
            bgColor: '#1e293b',
        },
    },
    {
        version: 1,
        title: 'Food Promo – Restaurant Ad',
        slug: 'food-restaurant-ad-1',
        category: 'food',
        tags: ['restaurant', 'promo', 'ad'],
        defaultArtboardId: 'canvas-1',
        artboards: [
            {
                id: 'canvas-1',
                size: { width: 1080, height: 1080 },
                background: { kind: 'color', value: '#111827' },
                layers: [
                    {
                        id: 'photo',
                        type: 'image',
                        src: 'https://images.unsplash.com/photo-1540189549336-e6e99c3679fe?w=1600',
                        transform: { x: 0, y: 0, width: 1080, height: 1080, rotation: 0 },
                        fit: 'cover',
                        opacity: 0.6,
                        flip: { horizontal: false, vertical: false },
                        filters: { contrast: 0, brightness: 0, saturation: 0, blur: 0 },
                        zIndex: 0,
                    },
                    {
                        id: 'title',
                        type: 'text',
                        content: 'Chef’s Special Tonight',
                        transform: { x: 100, y: 420, width: 880, height: 100, rotation: 0 },
                        fontFamily: 'Inter, sans-serif',
                        fontSize: 68,
                        fontWeight: 900,
                        fill: '#fbbf24',
                        align: 'center',
                        zIndex: 1,
                    },
                    {
                        id: 'subtitle',
                        type: 'text',
                        content: 'Reserve your table now',
                        transform: { x: 100, y: 510, width: 880, height: 70, rotation: 0 },
                        fontFamily: 'Inter, sans-serif',
                        fontSize: 36,
                        fontWeight: 600,
                        fill: '#ffffff',
                        align: 'center',
                        zIndex: 2,
                    },
                ],
            },
        ],
        editableData: {
            title: 'Chef’s Special Tonight',
            subtitle: 'Reserve your table now',
            accentColor: '#fbbf24',
            image: 'https://images.unsplash.com/photo-1540189549336-e6e99c3679fe?w=1600',
        },
    },
    {
        version: 1,
        title: 'Food Menu – Minimal Chalk',
        slug: 'food-menu-minimal-1',
        category: 'food',
        tags: ['menu', 'restaurant', 'list'],
        defaultArtboardId: 'canvas-1',
        artboards: [
            {
                id: 'canvas-1',
                size: { width: 1080, height: 1350 },
                background: { kind: 'color', value: '#111827' },
                layers: [
                    {
                        id: 'title',
                        type: 'text',
                        content: 'Today’s Menu',
                        transform: { x: 100, y: 120, width: 880, height: 80, rotation: 0 },
                        fontFamily: 'Inter, sans-serif',
                        fontSize: 56,
                        fontWeight: 800,
                        fill: '#ffffff',
                        align: 'center',
                    },
                    {
                        id: 'section',
                        type: 'text',
                        content: '• Truffle Pasta — $18\n• Grilled Salmon — $23\n• Caesar Salad — $12',
                        transform: { x: 160, y: 260, width: 760, height: 400, rotation: 0 },
                        fontFamily: 'Inter, sans-serif',
                        fontSize: 32,
                        fontWeight: 500,
                        fill: '#e5e7eb',
                        align: 'left',
                    },
                ],
            },
        ],
        editableData: {
            title: 'Today’s Menu',
            items: '• Truffle Pasta — $18\n• Grilled Salmon — $23\n• Caesar Salad — $12',
            accentColor: '#ffffff',
        },
    },
    {
        version: 1,
        title: 'Food Story – Gradient Promo',
        slug: 'food-story-gradient-1',
        category: 'food',
        tags: ['story', 'promo', 'gradient'],
        defaultArtboardId: 'canvas-1',
        artboards: [
            {
                id: 'canvas-1',
                size: { width: 1080, height: 1920 },
                background: {
                    kind: 'gradient',
                    gradient: {
                        type: 'linear',
                        angle: 120,
                        stops: [
                            { at: 0, color: '#ef4444' },
                            { at: 1, color: '#f59e0b' },
                        ],
                    },
                },
                layers: [
                    {
                        id: 'title',
                        type: 'text',
                        content: 'Weekend Brunch Deals',
                        transform: { x: 100, y: 820, width: 880, height: 120, rotation: 0 },
                        fontFamily: 'Inter, sans-serif',
                        fontSize: 80,
                        fontWeight: 900,
                        fill: '#ffffff',
                        align: 'center',
                    },
                    {
                        id: 'subtitle',
                        type: 'text',
                        content: 'Buy 1 Get 1 Free • 10–2',
                        transform: { x: 100, y: 950, width: 880, height: 80, rotation: 0 },
                        fontFamily: 'Inter, sans-serif',
                        fontSize: 40,
                        fontWeight: 700,
                        fill: '#fff7ed',
                        align: 'center',
                    },
                ],
            },
        ],
        editableData: {
            title: 'Weekend Brunch Deals',
            subtitle: 'Buy 1 Get 1 Free • 10–2',
            gradient: ['#ef4444', '#f59e0b'],
        },
    },
    {
        version: 1,
        title: 'Food Ad – Delivery Promo',
        slug: 'food-delivery-promo-1',
        category: 'food',
        tags: ['delivery', 'banner', 'ad'],
        defaultArtboardId: 'canvas-1',
        artboards: [
            {
                id: 'canvas-1',
                size: { width: 1200, height: 628 },
                background: { kind: 'color', value: '#ffffff' },
                layers: [
                    {
                        id: 'photo',
                        type: 'image',
                        src: 'https://images.unsplash.com/photo-1544025162-d76694265947?w=1600',
                        transform: { x: 0, y: 0, width: 1200, height: 628, rotation: 0 },
                        fit: 'cover',
                        opacity: 0.8,
                        flip: { horizontal: false, vertical: false },
                        filters: { contrast: 0, brightness: 0, saturation: 0, blur: 0 },
                    },
                    {
                        id: 'title',
                        type: 'text',
                        content: 'Free Delivery Over $25',
                        transform: { x: 60, y: 240, width: 1080, height: 120, rotation: 0 },
                        fontFamily: 'Inter, sans-serif',
                        fontSize: 64,
                        fontWeight: 900,
                        fill: '#dc2626',
                        align: 'center',
                    },
                ],
            },
        ],
        editableData: {
            title: 'Free Delivery Over $25',
            accentColor: '#dc2626',
            image: 'https://images.unsplash.com/photo-1544025162-d76694265947?w=1600',
        },
    },
    {
        version: 1,
        title: 'Food – Recipe Card',
        slug: 'food-recipe-card-1',
        category: 'food',
        tags: ['recipe', 'card', 'kitchen'],
        defaultArtboardId: 'canvas-1',
        artboards: [
            {
                id: 'canvas-1',
                size: { width: 1080, height: 1350 },
                background: { kind: 'color', value: '#fff7ed' },
                layers: [
                    {
                        id: 'photo',
                        type: 'image',
                        src: 'https://images.unsplash.com/photo-1512058564366-18510be2db19?w=1600',
                        transform: { x: 0, y: 0, width: 1080, height: 540, rotation: 0 },
                        fit: 'cover',
                        flip: { horizontal: false, vertical: false },
                        filters: { contrast: 0, brightness: 0, saturation: 0, blur: 0 },
                        zIndex: 0,
                    },
                    {
                        id: 'title',
                        type: 'text',
                        content: 'Creamy Garlic Pasta',
                        transform: { x: 100, y: 580, width: 880, height: 80, rotation: 0 },
                        fontFamily: 'Inter, sans-serif',
                        fontSize: 48,
                        fontWeight: 800,
                        fill: '#0f172a',
                        align: 'center',
                        zIndex: 1,
                    },
                    {
                        id: 'ingredients',
                        type: 'text',
                        content: 'Ingredients:\n• Pasta • Garlic • Cream • Parmesan',
                        transform: { x: 160, y: 680, width: 760, height: 300, rotation: 0 },
                        fontFamily: 'Inter, sans-serif',
                        fontSize: 28,
                        fontWeight: 500,
                        fill: '#334155',
                        align: 'left',
                        zIndex: 2,
                    },
                ],
            },
        ],
        editableData: {
            title: 'Creamy Garlic Pasta',
            ingredients: 'Ingredients:\n• Pasta • Garlic • Cream • Parmesan',
            image: 'https://images.unsplash.com/photo-1512058564366-18510be2db19?w=1600',
        },
    },
];

export const REAL_ESTATE_FOOD_RECORD: Record<string, Record<string, unknown>> = REAL_ESTATE_FOOD_TEMPLATES.reduce(
    (acc, template) => {
        acc[template.slug] = template;
        return acc;
    },
    {} as Record<string, Record<string, unknown>>
);
