export const SOCIAL_TEMPLATES = [
    {
        version: 1,
        title: 'Instagram Post – Food Promo',
        slug: 'social-instagram-food-1',
        category: 'social',
        tags: ['instagram', 'food', 'promo'],
        defaultArtboardId: 'canvas-1',
        artboards: [
            {
                id: 'canvas-1',
                name: 'Instagram Food Promo',
                size: { width: 1080, height: 1080 },
                background: { kind: 'color', value: '#ffffff' },
                layers: [
                    {
                        id: 'bg-photo',
                        type: 'image',
                        src: 'https://images.unsplash.com/photo-1600891963938-7e36c07d1e0a?w=1200',
                        transform: { x: 0, y: 0, width: 1080, height: 1080 },
                        fit: 'cover',
                    },
                    {
                        id: 'overlay',
                        type: 'shape',
                        shape: 'rect',
                        transform: { x: 0, y: 0, width: 1080, height: 1080 },
                        fill: { kind: 'solid', color: '#00000080' },
                    },
                    {
                        id: 'title',
                        type: 'text',
                        content: 'Delicious Meals Await',
                        transform: { x: 80, y: 400, width: 920, height: 100 },
                        fontFamily: 'Inter, sans-serif',
                        fontSize: 72,
                        fontWeight: 700,
                        fill: '#ffffff',
                        align: 'center',
                    },
                    {
                        id: 'cta',
                        type: 'text',
                        content: 'Order Now 🍽️',
                        transform: { x: 80, y: 520, width: 920, height: 60 },
                        fontFamily: 'Inter, sans-serif',
                        fontSize: 36,
                        fontWeight: 600,
                        fill: '#facc15',
                        align: 'center',
                    },
                ],
            },
        ],
        editableData: {
            title: 'Delicious Meals Await',
            cta: 'Order Now 🍽️',
            image: 'https://images.unsplash.com/photo-1600891963938-7e36c07d1e0a?w=1200',
            accentColor: '#facc15',
        },
    },
    {
        version: 1,
        title: 'Instagram Story – Gradient Fashion',
        slug: 'social-instagram-fashion-1',
        category: 'social',
        tags: ['instagram', 'story', 'fashion'],
        defaultArtboardId: 'canvas-1',
        artboards: [
            {
                id: 'canvas-1',
                size: { width: 1080, height: 1920 },
                background: {
                    kind: 'gradient',
                    gradient: {
                        type: 'linear',
                        angle: 120,
                        stops: [
                            { at: 0, color: '#ec4899' },
                            { at: 1, color: '#8b5cf6' },
                        ],
                    },
                },
                layers: [
                    {
                        id: 'photo',
                        type: 'image',
                        src: 'https://images.unsplash.com/photo-1490481651871-ab68de25d43d?w=1200',
                        transform: { x: 0, y: 200, width: 1080, height: 1520 },
                        fit: 'cover',
                        opacity: 0.3,
                    },
                    {
                        id: 'headline',
                        type: 'text',
                        content: 'New Collection',
                        transform: { x: 100, y: 800, width: 880, height: 120 },
                        fontFamily: 'Inter, sans-serif',
                        fontSize: 96,
                        fontWeight: 800,
                        fill: '#ffffff',
                        align: 'center',
                    },
                    {
                        id: 'cta',
                        type: 'text',
                        content: 'Shop Now',
                        transform: { x: 100, y: 960, width: 880, height: 80 },
                        fontFamily: 'Inter, sans-serif',
                        fontSize: 48,
                        fontWeight: 600,
                        fill: '#f9fafb',
                        align: 'center',
                    },
                ],
            },
        ],
        editableData: {
            title: 'New Collection',
            cta: 'Shop Now',
            image: 'https://images.unsplash.com/photo-1490481651871-ab68de25d43d?w=1200',
        },
    },
    {
        version: 1,
        title: 'YouTube Thumbnail – Tech Review',
        slug: 'social-youtube-tech-1',
        category: 'social',
        tags: ['youtube', 'tech', 'thumbnail'],
        defaultArtboardId: 'canvas-1',
        artboards: [
            {
                id: 'canvas-1',
                size: { width: 1280, height: 720 },
                background: { kind: 'color', value: '#111827' },
                layers: [
                    {
                        id: 'bg-photo',
                        type: 'image',
                        src: 'https://images.unsplash.com/photo-1519389950473-47ba0277781c?w=1200',
                        transform: { x: 0, y: 0, width: 1280, height: 720 },
                        fit: 'cover',
                        opacity: 0.4,
                    },
                    {
                        id: 'title',
                        type: 'text',
                        content: 'Top 5 Gadgets of 2025',
                        transform: { x: 80, y: 280, width: 1120, height: 100 },
                        fontFamily: 'Inter, sans-serif',
                        fontSize: 84,
                        fontWeight: 800,
                        fill: '#38bdf8',
                        align: 'center',
                    },
                ],
            },
        ],
        editableData: {
            title: 'Top 5 Gadgets of 2025',
            image: 'https://images.unsplash.com/photo-1519389950473-47ba0277781c?w=1200',
            accentColor: '#38bdf8',
        },
    },
    {
        version: 1,
        title: 'Twitter Post – Quote',
        slug: 'social-twitter-quote-1',
        category: 'social',
        tags: ['twitter', 'quote', 'motivational'],
        defaultArtboardId: 'canvas-1',
        artboards: [
            {
                id: 'canvas-1',
                size: { width: 1200, height: 675 },
                background: { kind: 'color', value: '#f1f5f9' },
                layers: [
                    {
                        id: 'text',
                        type: 'text',
                        content: '“Discipline beats motivation.”',
                        transform: { x: 120, y: 260, width: 960, height: 120 },
                        fontFamily: 'Inter, sans-serif',
                        fontSize: 48,
                        fontWeight: 600,
                        fill: '#111827',
                        align: 'center',
                    },
                ],
            },
        ],
        editableData: {
            title: '“Discipline beats motivation.”',
            bgColor: '#f1f5f9',
            textColor: '#111827',
        },
    },
    {
        version: 1,
        title: 'LinkedIn Banner – Business Growth',
        slug: 'social-linkedin-growth-1',
        category: 'social',
        tags: ['linkedin', 'business', 'growth'],
        defaultArtboardId: 'canvas-1',
        artboards: [
            {
                id: 'canvas-1',
                size: { width: 1584, height: 396 },
                background: { kind: 'color', value: '#1e293b' },
                layers: [
                    {
                        id: 'bg-photo',
                        type: 'image',
                        src: 'https://images.unsplash.com/photo-1556761175-4b46a572b786?w=1200',
                        transform: { x: 0, y: 0, width: 1584, height: 396 },
                        fit: 'cover',
                        opacity: 0.3,
                    },
                    {
                        id: 'headline',
                        type: 'text',
                        content: 'Accelerate Your Business Growth 🚀',
                        transform: { x: 100, y: 140, width: 1380, height: 100 },
                        fontFamily: 'Inter, sans-serif',
                        fontSize: 60,
                        fontWeight: 800,
                        fill: '#ffffff',
                        align: 'center',
                    },
                ],
            },
        ],
        editableData: {
            title: 'Accelerate Your Business Growth 🚀',
            image: 'https://images.unsplash.com/photo-1556761175-4b46a572b786?w=1200',
            bgColor: '#1e293b',
        },
    },
    {
        version: 1,
        title: 'TikTok Cover – Music Artist',
        slug: 'social-tiktok-music-1',
        category: 'social',
        tags: ['tiktok', 'music', 'cover'],
        defaultArtboardId: 'canvas-1',
        artboards: [
            {
                id: 'canvas-1',
                size: { width: 1080, height: 1920 },
                background: { kind: 'color', value: '#000000' },
                layers: [
                    {
                        id: 'bg-photo',
                        type: 'image',
                        src: 'https://images.unsplash.com/photo-1601933470928-c8b3a3f81f4f?w=1200',
                        transform: { x: 0, y: 0, width: 1080, height: 1920 },
                        fit: 'cover',
                        opacity: 0.6,
                    },
                    {
                        id: 'title',
                        type: 'text',
                        content: 'New Single Out Now',
                        transform: { x: 100, y: 800, width: 880, height: 120 },
                        fontFamily: 'Inter, sans-serif',
                        fontSize: 72,
                        fontWeight: 800,
                        fill: '#f43f5e',
                        align: 'center',
                    },
                ],
            },
        ],
        editableData: {
            title: 'New Single Out Now',
            image: 'https://images.unsplash.com/photo-1601933470928-c8b3a3f81f4f?w=1200',
            accentColor: '#f43f5e',
        },
    },
    {
        version: 1,
        title: 'Facebook Ad – Restaurant',
        slug: 'social-facebook-restaurant-1',
        category: 'social',
        tags: ['facebook', 'restaurant', 'ad'],
        defaultArtboardId: 'canvas-1',
        artboards: [
            {
                id: 'canvas-1',
                size: { width: 1200, height: 628 },
                background: { kind: 'color', value: '#ffffff' },
                layers: [
                    {
                        id: 'bg-photo',
                        type: 'image',
                        src: 'https://images.unsplash.com/photo-1551218808-94e220e084d2?w=1200',
                        transform: { x: 0, y: 0, width: 1200, height: 628 },
                        fit: 'cover',
                        opacity: 0.8,
                    },
                    {
                        id: 'headline',
                        type: 'text',
                        content: 'Try Our New Italian Dishes 🍝',
                        transform: { x: 60, y: 250, width: 1080, height: 100 },
                        fontFamily: 'Inter, sans-serif',
                        fontSize: 60,
                        fontWeight: 800,
                        fill: '#ffffff',
                        align: 'center',
                    },
                ],
            },
        ],
        editableData: {
            title: 'Try Our New Italian Dishes 🍝',
            image: 'https://images.unsplash.com/photo-1551218808-94e220e084d2?w=1200',
        },
    },
    {
        version: 1,
        title: 'Pinterest Graphic – Home Decor Tips',
        slug: 'social-pinterest-home-1',
        category: 'social',
        tags: ['pinterest', 'home', 'decor'],
        defaultArtboardId: 'canvas-1',
        artboards: [
            {
                id: 'canvas-1',
                size: { width: 1000, height: 1500 },
                background: { kind: 'color', value: '#fafaf9' },
                layers: [
                    {
                        id: 'photo',
                        type: 'image',
                        src: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=1200',
                        transform: { x: 0, y: 0, width: 1000, height: 900 },
                        fit: 'cover',
                    },
                    {
                        id: 'title',
                        type: 'text',
                        content: '10 Minimal Home Decor Ideas',
                        transform: { x: 80, y: 950, width: 840, height: 100 },
                        fontFamily: 'Inter, sans-serif',
                        fontSize: 64,
                        fontWeight: 800,
                        fill: '#1e293b',
                        align: 'center',
                    },
                ],
            },
        ],
        editableData: {
            title: '10 Minimal Home Decor Ideas',
            image: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=1200',
        },
    },
    {
        version: 1,
        title: 'Instagram Carousel – Product Teaser',
        slug: 'social-instagram-carousel-1',
        category: 'social',
        tags: ['instagram', 'carousel', 'product'],
        defaultArtboardId: 'canvas-1',
        artboards: [
            {
                id: 'canvas-1',
                size: { width: 1080, height: 1080 },
                background: { kind: 'color', value: '#0f172a' },
                layers: [
                    {
                        id: 'photo',
                        type: 'image',
                        src: 'https://images.unsplash.com/photo-1581090700227-1e37b190418e?w=1200',
                        transform: { x: 0, y: 0, width: 1080, height: 1080 },
                        fit: 'cover',
                        opacity: 0.4,
                    },
                    {
                        id: 'title',
                        type: 'text',
                        content: 'Introducing Our New Gadget',
                        transform: { x: 100, y: 420, width: 880, height: 100 },
                        fontFamily: 'Inter, sans-serif',
                        fontSize: 60,
                        fontWeight: 700,
                        fill: '#38bdf8',
                        align: 'center',
                    },
                ],
            },
        ],
        editableData: {
            title: 'Introducing Our New Gadget',
            image: 'https://images.unsplash.com/photo-1581090700227-1e37b190418e?w=1200',
            accentColor: '#38bdf8',
        },
    },
    {
        version: 1,
        title: 'Instagram Post – Fitness Motivation',
        slug: 'social-instagram-fitness-1',
        category: 'social',
        tags: ['instagram', 'fitness', 'motivation'],
        defaultArtboardId: 'canvas-1',
        artboards: [
            {
                id: 'canvas-1',
                size: { width: 1080, height: 1080 },
                background: { kind: 'color', value: '#111827' },
                layers: [
                    {
                        id: 'bg-photo',
                        type: 'image',
                        src: 'https://images.unsplash.com/photo-1579758629938-03607ccdbaba?w=1200',
                        transform: { x: 0, y: 0, width: 1080, height: 1080 },
                        fit: 'cover',
                        opacity: 0.5,
                    },
                    {
                        id: 'quote',
                        type: 'text',
                        content: 'Push Harder Than Yesterday 💪',
                        transform: { x: 80, y: 440, width: 920, height: 100 },
                        fontFamily: 'Inter, sans-serif',
                        fontSize: 60,
                        fontWeight: 800,
                        fill: '#22c55e',
                        align: 'center',
                    },
                ],
            },
        ],
        editableData: {
            title: 'Push Harder Than Yesterday 💪',
            image: 'https://images.unsplash.com/photo-1579758629938-03607ccdbaba?w=1200',
            accentColor: '#22c55e',
        },
    },
];

export const SOCIAL_TEMPLATE_RECORD: Record<string, Record<string, unknown>> = SOCIAL_TEMPLATES.reduce(
    (acc, template) => {
        acc[template.slug] = template;
        return acc;
    },
    {} as Record<string, Record<string, unknown>>
);
