export const TECH_TRANSPORT_STARTUP_TEMPLATES = [
    {
        version: 1,
        title: 'Tech Startup – Landing Mockup',
        slug: 'tech-landing-1',
        category: 'enterprise',
        tags: ['tech', 'startup', 'landing page'],
        thumbnail: {
            type: 'css',
            style: {
                background: 'linear-gradient(120deg, #1e3a8a, #3b82f6)',
                borderRadius: '12px',
                boxShadow: '0 4px 18px rgba(30,58,138,0.25)',
            },
        },
        defaultArtboardId: 'canvas-1',
        artboards: [
            {
                id: 'canvas-1',
                name: 'Startup Landing',
                size: { width: 1920, height: 1080 },
                background: {
                    kind: 'gradient',
                    gradient: {
                        type: 'linear',
                        angle: 120,
                        stops: [
                            { at: 0, color: '#1e3a8a' },
                            { at: 1, color: '#3b82f6' },
                        ],
                    },
                },
                layers: [
                    {
                        id: 'header',
                        type: 'text',
                        content: 'Welcome to NovaTech AI',
                        transform: { x: 200, y: 200, width: 1520, height: 100, rotation: 0 },
                        fontFamily: 'Inter, sans-serif',
                        fontSize: 64,
                        fontWeight: 800,
                        fill: '#ffffff',
                        align: 'center',
                    },
                    {
                        id: 'subtitle',
                        type: 'text',
                        content: 'Innovating your digital world.',
                        transform: { x: 200, y: 320, width: 1520, height: 80, rotation: 0 },
                        fontFamily: 'Inter, sans-serif',
                        fontSize: 36,
                        fontWeight: 400,
                        fill: '#e0f2fe',
                        align: 'center',
                    },
                    {
                        id: 'hero-image',
                        type: 'image',
                        src: 'https://images.unsplash.com/photo-1526378722484-cc6cdd4a97e9?w=1600',
                        transform: { x: 460, y: 440, width: 1000, height: 540, rotation: 0 },
                        fit: 'cover',
                        opacity: 0.9,
                        flip: { horizontal: false, vertical: false },
                        filters: { contrast: 10, brightness: 0, saturation: 0, blur: 0 },
                    },
                ],
            },
        ],
        editableData: {
            title: 'Welcome to NovaTech AI',
            subtitle: 'Innovating your digital world.',
            gradient: ['#1e3a8a', '#3b82f6'],
            image: 'https://images.unsplash.com/photo-1526378722484-cc6cdd4a97e9?w=1600',
        },
    },
    {
        version: 1,
        title: 'Tech Email Template – Update',
        slug: 'tech-email-1',
        category: 'business',
        tags: ['email', 'tech', 'newsletter'],
        thumbnail: {
            type: 'css',
            style: {
                background: 'linear-gradient(135deg, #0ea5e9, #38bdf8)',
                borderRadius: '12px',
                boxShadow: '0 4px 18px rgba(14,165,233,0.25)',
            },
        },
        defaultArtboardId: 'canvas-1',
        artboards: [
            {
                id: 'canvas-1',
                name: 'Tech Email',
                size: { width: 800, height: 1200 },
                background: { kind: 'color', value: '#ffffff' },
                layers: [
                    {
                        id: 'header',
                        type: 'shape',
                        shape: 'rect',
                        transform: { x: 0, y: 0, width: 800, height: 160, rotation: 0 },
                        fill: { kind: 'solid', color: '#0ea5e9' },
                    },
                    {
                        id: 'logo',
                        type: 'text',
                        content: 'Dropple Tech',
                        transform: { x: 100, y: 60, width: 600, height: 60, rotation: 0 },
                        fontFamily: 'Inter, sans-serif',
                        fontSize: 36,
                        fontWeight: 800,
                        fill: '#ffffff',
                        align: 'center',
                    },
                    {
                        id: 'hero-img',
                        type: 'image',
                        src: 'https://images.unsplash.com/photo-1533750349088-cd871a92f312?w=1600',
                        transform: { x: 100, y: 240, width: 600, height: 360, rotation: 0 },
                        fit: 'cover',
                        opacity: 1,
                        flip: { horizontal: false, vertical: false },
                        filters: { contrast: 10, brightness: 0, saturation: 0, blur: 0 },
                    },
                    {
                        id: 'body',
                        type: 'text',
                        content: 'Introducing new AI features for smarter collaboration.',
                        transform: { x: 100, y: 640, width: 600, height: 120, rotation: 0 },
                        fontFamily: 'Inter, sans-serif',
                        fontSize: 28,
                        fontWeight: 400,
                        fill: '#1e293b',
                        align: 'center',
                    },
                ],
            },
        ],
        editableData: {
            title: 'Dropple Tech',
            body: 'Introducing new AI features for smarter collaboration.',
            accentColor: '#0ea5e9',
            image: 'https://images.unsplash.com/photo-1533750349088-cd871a92f312?w=1600',
        },
    },
    {
        version: 1,
        title: 'Transportation – Fleet Services',
        slug: 'transport-fleet-1',
        category: 'business',
        tags: ['transport', 'logistics', 'fleet'],
        thumbnail: {
            type: 'css',
            style: {
                background: 'linear-gradient(135deg, #0f172a, #1e3a8a)',
                borderRadius: '12px',
                boxShadow: '0 4px 18px rgba(30,64,175,0.25)',
            },
        },
        defaultArtboardId: 'canvas-1',
        artboards: [
            {
                id: 'canvas-1',
                name: 'Fleet Poster',
                size: { width: 1080, height: 1350 },
                background: { kind: 'color', value: '#f8fafc' },
                layers: [
                    {
                        id: 'truck-image',
                        type: 'image',
                        src: 'https://images.unsplash.com/photo-1600359756076-0d26d2d6c6b1?w=1600',
                        transform: { x: 100, y: 180, width: 880, height: 500, rotation: 0 },
                        fit: 'cover',
                        opacity: 1,
                        flip: { horizontal: false, vertical: false },
                        filters: { contrast: 10, brightness: 0, saturation: 0, blur: 0 },
                    },
                    {
                        id: 'title',
                        type: 'text',
                        content: 'Reliable Freight Solutions',
                        transform: { x: 100, y: 760, width: 880, height: 100, rotation: 0 },
                        fontFamily: 'Inter, sans-serif',
                        fontSize: 56,
                        fontWeight: 800,
                        fill: '#1e293b',
                        align: 'center',
                    },
                    {
                        id: 'subtitle',
                        type: 'text',
                        content: 'Nationwide logistics and transport services',
                        transform: { x: 100, y: 860, width: 880, height: 60, rotation: 0 },
                        fontFamily: 'Inter, sans-serif',
                        fontSize: 32,
                        fontWeight: 400,
                        fill: '#475569',
                        align: 'center',
                    },
                ],
            },
        ],
        editableData: {
            title: 'Reliable Freight Solutions',
            subtitle: 'Nationwide logistics and transport services',
            image: 'https://images.unsplash.com/photo-1600359756076-0d26d2d6c6b1?w=1600',
        },
    },
    {
        version: 1,
        title: 'Logistics – Express Delivery',
        slug: 'logistics-banner-1',
        category: 'enterprise',
        tags: ['logistics', 'delivery', 'express'],
        thumbnail: {
            type: 'css',
            style: {
                background: 'linear-gradient(135deg, #0f172a, #38bdf8)',
                borderRadius: '12px',
                boxShadow: '0 4px 18px rgba(56,189,248,0.25)',
            },
        },
        defaultArtboardId: 'canvas-1',
        artboards: [
            {
                id: 'canvas-1',
                name: 'Delivery Banner',
                size: { width: 1920, height: 800 },
                background: { kind: 'color', value: '#f1f5f9' },
                layers: [
                    {
                        id: 'hero-img',
                        type: 'image',
                        src: 'https://images.unsplash.com/photo-1542228262-3d663b306a9a?w=1600',
                        transform: { x: 0, y: 0, width: 960, height: 800, rotation: 0 },
                        fit: 'cover',
                        opacity: 1,
                        flip: { horizontal: false, vertical: false },
                        filters: { contrast: 0, brightness: 0, saturation: 0, blur: 0 },
                    },
                    {
                        id: 'title',
                        type: 'text',
                        content: 'Express Delivery Worldwide',
                        transform: { x: 1040, y: 260, width: 800, height: 100, rotation: 0 },
                        fontFamily: 'Inter, sans-serif',
                        fontSize: 56,
                        fontWeight: 800,
                        fill: '#0f172a',
                    },
                    {
                        id: 'subtitle',
                        type: 'text',
                        content: 'Fast. Reliable. Global reach.',
                        transform: { x: 1040, y: 360, width: 800, height: 80, rotation: 0 },
                        fontFamily: 'Inter, sans-serif',
                        fontSize: 28,
                        fontWeight: 400,
                        fill: '#475569',
                    },
                ],
            },
        ],
        editableData: {
            title: 'Express Delivery Worldwide',
            subtitle: 'Fast. Reliable. Global reach.',
            image: 'https://images.unsplash.com/photo-1542228262-3d663b306a9a?w=1600',
        },
    },
    {
        version: 1,
        title: 'Startup – Business Proposal',
        slug: 'startup-proposal-1',
        category: 'business',
        tags: ['proposal', 'startup', 'document'],
        thumbnail: {
            type: 'css',
            style: {
                background: 'linear-gradient(135deg, #1e40af, #60a5fa)',
                borderRadius: '12px',
                boxShadow: '0 4px 18px rgba(96,165,250,0.25)',
            },
        },
        defaultArtboardId: 'canvas-1',
        artboards: [
            {
                id: 'canvas-1',
                name: 'Business Proposal',
                size: { width: 1200, height: 1600 },
                background: { kind: 'color', value: '#ffffff' },
                layers: [
                    {
                        id: 'header-shape',
                        type: 'shape',
                        shape: 'rect',
                        transform: { x: 0, y: 0, width: 1200, height: 240, rotation: 0 },
                        fill: { kind: 'solid', color: '#1e40af' },
                    },
                    {
                        id: 'title',
                        type: 'text',
                        content: 'Business Proposal 2025',
                        transform: { x: 100, y: 80, width: 1000, height: 80, rotation: 0 },
                        fontFamily: 'Inter, sans-serif',
                        fontSize: 52,
                        fontWeight: 800,
                        fill: '#ffffff',
                        align: 'center',
                    },
                    {
                        id: 'body',
                        type: 'text',
                        content: 'We aim to revolutionize B2B tech for logistics operations worldwide.',
                        transform: { x: 100, y: 400, width: 1000, height: 400, rotation: 0 },
                        fontFamily: 'Inter, sans-serif',
                        fontSize: 28,
                        fontWeight: 400,
                        fill: '#1e293b',
                        align: 'center',
                    },
                ],
            },
        ],
        editableData: {
            title: 'Business Proposal 2025',
            body: 'We aim to revolutionize B2B tech for logistics operations worldwide.',
            accentColor: '#1e40af',
        },
    },
];

export const TECH_TRANSPORT_STARTUP_RECORD: Record<string, Record<string, unknown>> =
    TECH_TRANSPORT_STARTUP_TEMPLATES.reduce(
        (acc, template) => {
            acc[template.slug] = template;
            return acc;
        },
        {} as Record<string, Record<string, unknown>>
    );

