import { Geist, Geist_Mono } from "next/font/google";
import { StackProvider, StackTheme } from "@stackframe/stack";
import { stackClientApp } from "../stack/client";
import { ConvexProvider } from "../providers/ConvexProvider";
import { UserProvider } from "../providers/UserProvider";
import "./globals.css";

import AIDock from "@/ui/ai-dock/AI_Dock";

const geistSans = Geist({
    variable: '--font-geist-sans',
    subsets: ['latin'],
});

const geistMono = Geist_Mono({
    variable: '--font-geist-mono',
    subsets: ['latin'],
});

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <StackProvider app={stackClientApp}>
          <StackTheme>
            <ConvexProvider>
              <UserProvider>
                {children}
                <AIDock />
              </UserProvider>
            </ConvexProvider>
          </StackTheme>
        </StackProvider>
      </body>
    </html>
  );
}
