import { Geist, Geist_Mono } from 'next/font/google';
import { StackProvider, StackTheme } from '@stackframe/stack';
import { stackServerApp } from '../stack';
import './globals.css';
import ConvexClientProvider from './ConvexClientProvider';

const geistSans = Geist({
    variable: '--font-geist-sans',
    subsets: ['latin'],
});

const geistMono = Geist_Mono({
    variable: '--font-geist-mono',
    subsets: ['latin'],
});

export const metadata = {
    title: 'Dropple',
    description: 'Generated by create next app',
    icons: {
        icon: '/favicon.ico',
        shortcut: '/favicon.ico',
        apple: '/apple-touch-icon.png',
        other: [
            {
                rel: 'icon',
                url: '/favicon-32x32.png',
                type: 'image/png',
                sizes: '32x32',
            },
        ],
    },
};

export default function RootLayout({ children }) {
    return (
        <html lang='en'>
            <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
                <StackProvider app={stackServerApp}>
                    <StackTheme>
                        <ConvexClientProvider>{children}</ConvexClientProvider>
                    </StackTheme>
                </StackProvider>
            </body>
        </html>
    );
}
