export const nodeDefaults = {
  text: () => ({
    type: "text",
    name: "Text",
    visible: true,
    locked: false,
    x: 100,
    y: 100,
    width: 200,
    height: 40,
    rotation: 0,
    content: "New Text",
    fontSize: 16,
    fontWeight: 600,
    color: "#000000",
    alignment: "left",
  }),
  image: () => ({
    type: "image",
    name: "Image",
    visible: true,
    locked: false,
    x: 120,
    y: 120,
    width: 240,
    height: 160,
    rotation: 0,
    src: "https://placehold.co/600x400",
    fit: "cover",
  }),
  shape: (shape = "rectangle") => ({
    type: "shape",
    name: "Shape",
    visible: true,
    locked: false,
    shape,
    x: 140,
    y: 140,
    width: 160,
    height: 160,
    rotation: 0,
    fill: "#e5e5e5",
    stroke: "#000000",
    strokeWidth: 1,
  }),
  frame: () => ({
    type: "frame",
    name: "Frame",
    visible: true,
    locked: false,
    x: 160,
    y: 160,
    width: 320,
    height: 240,
    rotation: 0,
    fill: "#ffffff",
    stroke: "#d1d5db",
    strokeWidth: 1,
    radius: 8,
    layout: {
      enabled: true,
      direction: "vertical",
      alignment: "start",
      gap: 12,
      padding: 16,
    },
    children: [],
  }),
  component: (componentId) => ({
    type: "component-node",
    name: "Component",
    visible: true,
    locked: false,
    componentId,
    overrides: {},
    x: 180,
    y: 180,
    width: 200,
    height: 60,
    variant: {},
  }),
};
