// Default diversified briefs across industries/tags/styles/layouts
export const defaultTemplateBriefs = [
  {
    prompt: "Fashion editorial poster with bold type and studio portrait",
    category: "fashion",
    tags: ["fashion", "editorial", "promo"],
    styleId: "fashionEditorial",
    componentId: "promoBanner",
  },
  {
    prompt: "Black Friday sale hero with dramatic contrast and product highlight",
    category: "ecommerce",
    tags: ["black_friday", "sale", "promo"],
    styleId: "gradientLuxe",
    componentId: "promoBanner",
  },
  {
    prompt: "Tech startup launch hero with clean gradients and CTA",
    category: "tech",
    tags: ["tech", "launch", "saas"],
    styleId: "techMinimal",
    componentId: "heroStory",
  },
  {
    prompt: "Music event flyer with neon lighting and performer portrait",
    category: "music",
    tags: ["music", "event", "flyer"],
    styleId: "neonPop",
    componentId: "eventFlyer",
  },
  {
    prompt: "Fitness promo with energetic gradient and bold CTA",
    category: "fitness",
    tags: ["fitness", "promo", "cta"],
    styleId: "darkCinematic",
    componentId: "promoBanner",
  },
  {
    prompt: "Business webinar banner with corporate blue palette",
    category: "business",
    tags: ["webinar", "business", "banner"],
    styleId: "corporateBlue",
    componentId: "heroStory",
  },
  {
    prompt: "Travel story card with landscape photo and overlay text",
    category: "travel",
    tags: ["travel", "story", "photo"],
    styleId: "gradientLuxe",
    componentId: "heroStory",
  },
  {
    prompt: "Quote card with gradient background and accent icon",
    category: "quotes",
    tags: ["quote", "inspiration", "social"],
    styleId: "neonPop",
    componentId: "gradientQuote",
  },
  {
    prompt: "Podcast cover with portrait and bold title",
    category: "podcast",
    tags: ["podcast", "cover", "audio"],
    styleId: "fashionEditorial",
    componentId: "podcastCover",
  },
  {
    prompt: "Event ticket/poster with date/time and CTA",
    category: "events",
    tags: ["event", "ticket", "poster"],
    styleId: "darkCinematic",
    componentId: "eventFlyer",
  },
];
