import OpenAI from "openai";
import { templateStyleMap, templateStyles } from "./templateStyles";
import { templateComponentPresetMap } from "./templateComponents";
import { pickPackImage } from "./assetPacks";
import { fetchPexelsImage } from "./pexelsClient";

const client =
  process.env.OPENAI_API_KEY || process.env.OPENAI_KEY
    ? new OpenAI({ apiKey: process.env.OPENAI_API_KEY || process.env.OPENAI_KEY })
    : null;

export async function assembleTemplate({
  prompt,
  styleId,
  componentId,
  model = "gpt-4o-mini",
  brand = null,
  imageUrl = null,
  category = null,
}) {
  const style =
    (styleId && templateStyleMap[styleId]) || templateStyles[0] || null;
  const layout =
    (componentId && templateComponentPresetMap[componentId]) ||
    templateComponentPresetMap.heroStory;

  const content = await fetchContent(prompt, layout, style, model, brand);
  if (imageUrl) {
    content.imageUrl = imageUrl;
  }

  const base = {
    width: 1080,
    height: 1350,
    background: style?.palette?.background || "#0f172a",
    colors: [
      style?.palette?.primary,
      style?.palette?.accent,
      style?.palette?.text,
      style?.palette?.surface,
    ].filter(Boolean),
    fonts: style?.fonts || ["Inter"],
    pageTransitions: {
      default: { type: "slide", direction: "right", duration: 0.6, ease: "easeOut" },
    },
  };

  if (brand?.name && !content.author) content.author = brand.name;

  const { nodes, animations, images } = await buildLayout(layout.id, style, content, brand, category);

  return {
    ...base,
    name: content?.title || "AI Template",
    description: content?.subtitle || "Generated by Dropple",
    nodes,
    animations,
    images,
    styleId: style?.id,
    componentId: layout.id,
    brand,
  };
}

async function fetchContent(prompt, layout, style, model, brand) {
  if (!client) {
    return fallbackContent(prompt);
  }
  const system = `You are a concise content filler for design templates. Return JSON only. Fields: title, subtitle, body, badge, kicker, ctaPrimary, ctaSecondary, author, price, quote, imagePrompt, icon (short identifier). Keep it specific to the user prompt and the layout "${layout.label}". If a brand is provided, respect its name, tagline, colors, and tone.`;
  const brandHint = brand
    ? `Brand: ${brand.name || ""}. Tagline: ${brand.tagline || ""}. Primary color: ${
        brand.colors?.primary?.[0] || brand.theme?.tokens?.colors?.primary || ""
      }. Tone: ${Array.isArray(brand.personality) ? brand.personality.join(", ") : ""}.`
    : "";
  const user = `${prompt || "Create a promo poster"}\nStyle: ${style?.label || "Modern"}\nLayout: ${
    layout.label
  }\n${brandHint}`;
  try {
    const completion = await client.chat.completions.create({
      model,
      messages: [
        { role: "system", content: system },
        { role: "user", content: user },
      ],
      response_format: { type: "json_object" },
      temperature: 0.6,
    });
    const msg = completion.choices?.[0]?.message?.content || "{}";
    return JSON.parse(msg);
  } catch (err) {
    console.warn("Content generation fallback:", err?.message || err);
    return fallbackContent(prompt);
  }
}

function fallbackContent(prompt) {
  return {
    title: prompt?.slice(0, 48) || "Explore the World",
    subtitle: "High-impact visual with bold CTA and motion.",
    badge: "New",
    kicker: "Featured",
    ctaPrimary: "Start Now",
    ctaSecondary: "Learn More",
    author: "@dropple",
    imagePrompt: "cinematic photo, dramatic lighting, depth, ultra-detailed",
    price: "$49",
  };
}

async function buildLayout(layoutId, style, content, brand, category) {
  switch (layoutId) {
    case "promoBanner":
      return await buildPromoBanner(style, content, brand, category);
    case "youtubeThumbnail":
      return await buildYouTubeThumb(style, content, brand, category);
    case "gradientQuote":
      return await buildGradientQuote(style, content, brand, category);
    case "materialCard":
      return await buildMaterialCard(style, content, brand, category);
    case "eventFlyer":
      return await buildEventFlyer(style, content, brand, category);
    case "businessCard":
      return await buildBusinessCard(style, content, brand, category);
    case "podcastCover":
      return await buildPodcastCover(style, content, brand, category);
    default:
      return await buildHeroStory(style, content, brand, category);
  }
}

async function buildHeroStory(style, content, brand, category) {
  const palette = style?.palette || {};
  const primary = palette.primary || "#8B5CF6";
  const accent = palette.accent || "#F97316";
  const text = palette.text || "#FFFFFF";
  const surface = palette.surface || "rgba(255,255,255,0.08)";
  const radius = style?.radius || 20;

  const heroUrl = await pickImage(content, brand, style, category);
  const nodes = [
    { id: "hero_image", type: "image", imageId: "img1", x: 0, y: 0, width: 1080, height: 840, fit: "cover", url: heroUrl },
    {
      id: "overlay",
      type: "shape",
      shape: "rectangle",
      x: 0,
      y: 0,
      width: 1080,
      height: 840,
      fill: palette.background || "linear-gradient(180deg, rgba(0,0,0,0.5), rgba(0,0,0,0.15))",
    },
    {
      id: "badge",
      type: "shape",
      shape: "rectangle",
      x: 80,
      y: 120,
      width: 160,
      height: 44,
      radius,
      fill: surface,
    },
    {
      id: "badge_text",
      type: "text",
      content: content.badge || content.kicker || "Featured",
      x: 96,
      y: 128,
      width: 200,
      height: 28,
      fontSize: 16,
      fontWeight: 700,
      color: text,
    },
    {
      id: "headline",
      type: "text",
      content: content.title || "Transform Your Body",
      x: 80,
      y: 190,
      width: 860,
      height: 220,
      fontSize: 86,
      fontWeight: 800,
      color: text,
    },
    {
      id: "subhead",
      type: "text",
      content: content.subtitle || "High-energy program with cinematic visuals.",
      x: 80,
      y: 360,
      width: 720,
      height: 80,
      fontSize: 22,
      fontWeight: 500,
      color: "rgba(255,255,255,0.85)",
    },
    {
      id: "cta",
      type: "shape",
      shape: "rectangle",
      x: 80,
      y: 470,
      width: 220,
      height: 64,
      radius,
      fill: `linear-gradient(135deg, ${primary}, ${accent})`,
    },
    ...(iconUrl
      ? [
          {
            id: "cta_icon",
            type: "image",
            imageId: "brand_icon_img",
            x: 90,
            y: 482,
            width: 32,
            height: 32,
            fit: "contain",
            url: iconUrl,
          },
        ]
      : []),
    {
      id: "cta_label",
      type: "text",
      content: content.ctaPrimary || "Start Now",
      x: iconUrl ? 128 : 110,
      y: 490,
      width: 180,
      height: 30,
      fontSize: 18,
      fontWeight: 700,
      color: "#ffffff",
    },
    {
      id: "cta_secondary",
      type: "text",
      content: content.ctaSecondary || "Learn More",
      x: 320,
      y: 490,
      width: 200,
      height: 30,
      fontSize: 16,
      fontWeight: 600,
      color: text,
    },
    {
      id: "logo_chip",
      type: "shape",
      shape: "rectangle",
      x: 80,
      y: 580,
      width: 160,
      height: 54,
      radius,
      fill: surface,
    },
    {
      id: "logo_text",
      type: "text",
      content: content.author || "@brand",
      x: 104,
      y: 595,
      width: 150,
      height: 28,
      fontSize: 16,
      fontWeight: 600,
      color: text,
    },
  ];
  const iconUrl = brandIconUrl(brand);
  if (iconUrl) {
    nodes.push({
      id: "brand_icon",
      type: "image",
      imageId: "brand_icon_img",
      x: 920,
      y: 120,
      width: 80,
      height: 80,
      fit: "contain",
      url: iconUrl,
    });
  }

  const animations = [
    {
      id: "anim_overlay",
      nodeId: "overlay",
      variants: {
        initial: { opacity: 0, y: 20 },
        animate: { opacity: 1, y: 0, transition: { duration: 0.65, ease: "easeOut", staggerChildren: 0.08 } },
      },
      triggers: ["onLoad", "onView"],
    },
    staggerAnim("badge", 0),
    staggerAnim("headline", 0.08),
    staggerAnim("subhead", 0.12),
    staggerAnim("cta", 0.16),
    staggerAnim("cta_label", 0.16),
    brandIconAnim(iconUrl ? "cta_icon" : null, 0.16),
    staggerAnim("cta_secondary", 0.2),
    staggerAnim("logo_chip", 0.24),
    staggerAnim("logo_text", 0.24),
    brandIconAnim(iconUrl ? "brand_icon" : null, 0.2),
    imageAnim("hero_image"),
  ].filter(Boolean);

  const images = [
    {
      id: "img1",
      prompt: content.imagePrompt || "cinematic portrait, dramatic lighting, neon glow, ultra-detailed",
      url: heroUrl,
      source: classifySource(heroUrl),
      license: classifyLicense(heroUrl),
    },
  ];

  return { nodes, animations, images };
}

async function buildPromoBanner(style, content, brand, category) {
  const palette = style?.palette || {};
  const primary = palette.primary || "#2563EB";
  const accent = palette.accent || "#0EA5E9";
  const surface = palette.surface || "#ffffff";
  const text = palette.text || "#ffffff";
  const radius = style?.radius || 18;

  const heroUrl = await pickImage(content, brand, style, category);
  const nodes = [
    { id: "bg", type: "shape", shape: "rectangle", x: 0, y: 0, width: 1080, height: 520, fill: surface, radius },
    {
      id: "image",
      type: "image",
      imageId: "img1",
      x: 560,
      y: 40,
      width: 480,
      height: 440,
      fit: "cover",
      url: heroUrl,
    },
    { id: "tag", type: "shape", shape: "rectangle", x: 80, y: 60, width: 140, height: 36, radius, fill: accent },
    {
      id: "tag_text",
      type: "text",
      content: content.badge || content.kicker || "Limited",
      x: 96,
      y: 68,
      width: 200,
      height: 24,
      fontSize: 14,
      fontWeight: 700,
      color: "#ffffff",
    },
    {
      id: "title",
      type: "text",
      content: content.title || "50% OFF New Drop",
      x: 80,
      y: 120,
      width: 420,
      height: 120,
      fontSize: 48,
      fontWeight: 800,
      color: text,
    },
    {
      id: "subtitle",
      type: "text",
      content: content.subtitle || "Fresh arrivals with bold design and motion.",
      x: 80,
      y: 220,
      width: 420,
      height: 70,
      fontSize: 18,
      fontWeight: 500,
      color: "rgba(15,23,42,0.75)",
    },
    {
      id: "price",
      type: "text",
      content: content.price || "$49",
      x: 80,
      y: 300,
      width: 200,
      height: 60,
      fontSize: 36,
      fontWeight: 800,
      color: primary,
    },
    {
      id: "cta",
      type: "shape",
      shape: "rectangle",
      x: 80,
      y: 370,
      width: 200,
      height: 56,
      radius,
      fill: primary,
    },
    {
      id: "cta_text",
      type: "text",
      content: content.ctaPrimary || "Shop Now",
      x: 112,
      y: 385,
      width: 160,
      height: 30,
      fontSize: 16,
      fontWeight: 700,
      color: "#ffffff",
    },
  ];
  const iconUrl = brandIconUrl(brand);
  if (iconUrl) {
    nodes.push({
      id: "brand_icon",
      type: "image",
      imageId: "brand_icon_img",
      x: 480,
      y: 60,
      width: 52,
      height: 52,
      fit: "contain",
      url: iconUrl,
    });
    nodes.push({
      id: "tag_icon",
      type: "image",
      imageId: "brand_icon_img",
      x: 88,
      y: 66,
      width: 16,
      height: 16,
      fit: "contain",
      url: iconUrl,
    });
    nodes.push({
      id: "cta_icon",
      type: "image",
      imageId: "brand_icon_img",
      x: 90,
      y: 382,
      width: 24,
      height: 24,
      fit: "contain",
      url: iconUrl,
    });
    nodes.push({
      id: "price_icon",
      type: "image",
      imageId: "brand_icon_img",
      x: 50,
      y: 300,
      width: 24,
      height: 24,
      fit: "contain",
      url: iconUrl,
    });
  }

  const animations = [
    staggerAnim("tag", 0),
    staggerAnim("title", 0.06),
    staggerAnim("subtitle", 0.1),
    staggerAnim("price", 0.14),
    staggerAnim("cta", 0.18),
    staggerAnim("cta_text", 0.18),
    brandIconAnim(iconUrl ? "brand_icon" : null, 0.18),
    brandIconAnim(iconUrl ? "tag_icon" : null, 0.12),
    brandIconAnim(iconUrl ? "cta_icon" : null, 0.18),
    brandIconAnim(iconUrl ? "price_icon" : null, 0.14),
    imageAnim("image"),
  ].filter(Boolean);

  const images = [
    {
      id: "img1",
      prompt: content.imagePrompt || "product hero, dramatic studio lighting, soft shadows",
      url: heroUrl,
      source: classifySource(heroUrl),
      license: classifyLicense(heroUrl),
    },
  ];

  return { nodes, animations, images };
}

async function buildYouTubeThumb(style, content, brand, category) {
  const palette = style?.palette || {};
  const primary = palette.primary || "#EF4444";
  const accent = palette.accent || "#F97316";
  const text = palette.text || "#F8FAFC";
  const radius = style?.radius || 18;

  const heroUrl = await pickImage(content, brand, style, category);
  const nodes = [
    { id: "bg", type: "image", imageId: "img1", x: 0, y: 0, width: 1080, height: 600, fit: "cover", url: heroUrl },
    {
      id: "overlay",
      type: "shape",
      shape: "rectangle",
      x: 0,
      y: 0,
      width: 1080,
      height: 600,
      fill: "linear-gradient(110deg, rgba(0,0,0,0.65), rgba(0,0,0,0.15))",
    },
    { id: "kicker", type: "shape", shape: "rectangle", x: 70, y: 60, width: 150, height: 38, radius, fill: primary },
    {
      id: "kicker_text",
      type: "text",
      content: content.kicker || "TUTORIAL",
      x: 90,
      y: 68,
      width: 200,
      height: 26,
      fontSize: 14,
      fontWeight: 800,
      color: "#ffffff",
    },
    {
      id: "title",
      type: "text",
      content: content.title || "Build Animated Thumbnails",
      x: 70,
      y: 130,
      width: 720,
      height: 160,
      fontSize: 60,
      fontWeight: 900,
      color: text,
    },
    {
      id: "subtitle",
      type: "text",
      content: content.subtitle || "Pro tips for motion-rich visuals.",
      x: 70,
      y: 300,
      width: 540,
      height: 60,
      fontSize: 20,
      fontWeight: 600,
      color: "rgba(255,255,255,0.85)",
    },
    { id: "play", type: "shape", shape: "rectangle", x: 860, y: 440, width: 140, height: 140, radius: 999, fill: `linear-gradient(135deg, ${primary}, ${accent})` },
    { id: "play_icon", type: "text", content: "▶", x: 910, y: 480, width: 60, height: 60, fontSize: 38, fontWeight: 800, color: "#ffffff" },
    {
      id: "author",
      type: "text",
      content: content.author || "@creator",
      x: 70,
      y: 380,
      width: 280,
      height: 30,
      fontSize: 18,
      fontWeight: 600,
      color: text,
    },
  ];

  const iconUrl = brandIconUrl(brand);
  if (iconUrl) {
    nodes.push({
      id: "brand_icon",
      type: "image",
      imageId: "brand_icon_img",
      x: 940,
      y: 60,
      width: 64,
      height: 64,
      fit: "contain",
      url: iconUrl,
    });
  }

  const animations = [
    staggerAnim("kicker", 0),
    staggerAnim("title", 0.08),
    staggerAnim("subtitle", 0.12),
    staggerAnim("author", 0.16),
    bounceAnim("play", 0.18),
    staggerAnim("play_icon", 0.18),
    brandIconAnim(iconUrl ? "brand_icon" : null, 0.2),
    imageAnim("bg"),
  ].filter(Boolean);

  const images = [
    {
      id: "img1",
      prompt: content.imagePrompt || "cinematic tech scene, neon, depth of field",
      url: heroUrl,
      source: classifySource(heroUrl),
      license: classifyLicense(heroUrl),
    },
  ];
  return { nodes, animations, images };
}

async function buildGradientQuote(style, content, brand, category) {
  const palette = style?.palette || {};
  const primary = palette.primary || "#8B5CF6";
  const accent = palette.accent || "#22D3EE";
  const text = palette.text || "#FFFFFF";
  const radius = style?.radius || 22;

  const nodes = [
    {
      id: "bg",
      type: "shape",
      shape: "rectangle",
      x: 0,
      y: 0,
      width: 1080,
      height: 600,
      radius,
      fill: `linear-gradient(135deg, ${primary}, ${accent})`,
    },
    {
      id: "quote",
      type: "text",
      content: content.quote || content.title || "“Success is not final.”",
      x: 120,
      y: 120,
      width: 840,
      height: 220,
      fontSize: 54,
      fontWeight: 800,
      color: text,
    },
    {
      id: "author",
      type: "text",
      content: content.author || "— Winston Churchill",
      x: 120,
      y: 340,
      width: 540,
      height: 40,
      fontSize: 22,
      fontWeight: 600,
      color: "rgba(255,255,255,0.86)",
    },
    {
      id: "accent",
      type: "shape",
      shape: "rectangle",
      x: 120,
      y: 420,
      width: 120,
      height: 6,
      radius: 3,
      fill: "#ffffff",
    },
  ];

  const iconUrl = brandIconUrl(brand);
  if (iconUrl) {
    nodes.push({
      id: "brand_icon",
      type: "image",
      imageId: "brand_icon_img",
      x: 920,
      y: 420,
      width: 72,
      height: 72,
      fit: "contain",
      url: iconUrl,
    });
    nodes.push({
      id: "accent_icon",
      type: "image",
      imageId: "brand_icon_img",
      x: 250,
      y: 412,
      width: 24,
      height: 24,
      fit: "contain",
      url: iconUrl,
    });
  }

  const animations = [
    staggerAnim("quote", 0),
    staggerAnim("author", 0.1),
    pulseAnim("accent", 0.2),
    brandIconAnim(iconUrl ? "brand_icon" : null, 0.2),
    brandIconAnim(iconUrl ? "accent_icon" : null, 0.2),
  ].filter(Boolean);
  const images = [];
  return { nodes, animations, images };
}

async function buildMaterialCard(style, content, brand, category) {
  const palette = style?.palette || {};
  const surface = palette.surface || "#ffffff";
  const primary = palette.primary || "#2563EB";
  const text = palette.text || "#0f172a";
  const radius = style?.radius || 16;

  const nodes = [
    { id: "card", type: "shape", shape: "rectangle", x: 120, y: 120, width: 840, height: 320, radius, fill: surface },
    { id: "avatar", type: "shape", shape: "rectangle", x: 160, y: 160, width: 64, height: 64, radius: 999, fill: primary },
    {
      id: "title",
      type: "text",
      content: content.title || "Product Manager",
      x: 240,
      y: 162,
      width: 520,
      height: 40,
      fontSize: 28,
      fontWeight: 800,
      color: text,
    },
    {
      id: "subtitle",
      type: "text",
      content: content.subtitle || "Building great products",
      x: 240,
      y: 206,
      width: 520,
      height: 32,
      fontSize: 18,
      fontWeight: 500,
      color: "rgba(15,23,42,0.7)",
    },
    {
      id: "body",
      type: "text",
      content: content.body || "Share your expertise with your network.",
      x: 160,
      y: 260,
      width: 640,
      height: 60,
      fontSize: 16,
      fontWeight: 500,
      color: "rgba(15,23,42,0.75)",
    },
    { id: "chip", type: "shape", shape: "rectangle", x: 160, y: 340, width: 120, height: 38, radius, fill: primary },
    { id: "chip_text", type: "text", content: content.badge || "Pro", x: 188, y: 348, width: 100, height: 24, fontSize: 14, fontWeight: 700, color: "#ffffff" },
    { id: "cta", type: "text", content: content.ctaPrimary || "View Profile →", x: 320, y: 348, width: 200, height: 24, fontSize: 15, fontWeight: 700, color: primary },
  ];

  const iconUrl = brandIconUrl(brand);
  if (iconUrl) {
    nodes.push({
      id: "brand_icon",
      type: "image",
      imageId: "brand_icon_img",
      x: 700,
      y: 160,
      width: 72,
      height: 72,
      fit: "contain",
      url: iconUrl,
    });
  }

  const animations = [
    hoverLift("card"),
    staggerAnim("avatar", 0),
    staggerAnim("title", 0.06),
    staggerAnim("subtitle", 0.1),
    staggerAnim("body", 0.14),
    staggerAnim("chip", 0.18),
    staggerAnim("chip_text", 0.18),
    staggerAnim("cta", 0.2),
    brandIconAnim(iconUrl ? "brand_icon" : null, 0.2),
  ].filter(Boolean);
  const images = [];
  return { nodes, animations, images };
}

async function buildEventFlyer(style, content, brand, category) {
  const palette = style?.palette || {};
  const primary = palette.primary || "#EF4444";
  const accent = palette.accent || "#F97316";
  const text = palette.text || "#F8FAFC";
  const radius = style?.radius || 20;

  const heroUrl = await pickImage(content, brand, style, category);
  const nodes = [
    { id: "bg", type: "image", imageId: "img1", x: 0, y: 0, width: 1080, height: 1350, fit: "cover", url: heroUrl },
    { id: "overlay", type: "shape", shape: "rectangle", x: 0, y: 0, width: 1080, height: 1350, fill: "linear-gradient(180deg, rgba(0,0,0,0.6), rgba(0,0,0,0.15))" },
    { id: "kicker", type: "shape", shape: "rectangle", x: 80, y: 120, width: 200, height: 40, radius, fill: primary },
    { id: "kicker_text", type: "text", content: content.kicker || "Live Event", x: 102, y: 128, width: 200, height: 26, fontSize: 14, fontWeight: 800, color: "#ffffff" },
    { id: "title", type: "text", content: content.title || "Empire of Shadows", x: 80, y: 180, width: 880, height: 200, fontSize: 82, fontWeight: 900, color: text },
    { id: "subtitle", type: "text", content: content.subtitle || "Coming Soon • April", x: 80, y: 360, width: 540, height: 60, fontSize: 26, fontWeight: 700, color: "rgba(255,255,255,0.9)" },
    { id: "datetime", type: "text", content: content.date || "Fri 7pm • Central Hall", x: 80, y: 430, width: 520, height: 40, fontSize: 20, fontWeight: 600, color: "rgba(255,255,255,0.82)" },
    { id: "cta", type: "shape", shape: "rectangle", x: 80, y: 500, width: 220, height: 60, radius, fill: `linear-gradient(135deg, ${primary}, ${accent})` },
    { id: "cta_text", type: "text", content: content.ctaPrimary || "Get Tickets", x: 112, y: 518, width: 180, height: 26, fontSize: 18, fontWeight: 800, color: "#ffffff" },
    { id: "footer", type: "shape", shape: "rectangle", x: 0, y: 1180, width: 1080, height: 170, radius: 0, fill: "rgba(0,0,0,0.55)" },
    { id: "footer_text", type: "text", content: content.author || "Presented by Dropple", x: 80, y: 1220, width: 720, height: 40, fontSize: 22, fontWeight: 700, color: "#ffffff" },
  ];

  const iconUrl = brandIconUrl(brand);
  if (iconUrl) {
    nodes.push({
      id: "brand_icon",
      type: "image",
      imageId: "brand_icon_img",
      x: 880,
      y: 118,
      width: 90,
      height: 90,
      fit: "contain",
      url: iconUrl,
    });
  }

  const animations = [
    staggerAnim("kicker", 0),
    staggerAnim("title", 0.08),
    staggerAnim("subtitle", 0.12),
    staggerAnim("datetime", 0.16),
    staggerAnim("cta", 0.18),
    staggerAnim("cta_text", 0.18),
    brandIconAnim(iconUrl ? "brand_icon" : null, 0.2),
    imageAnim("bg"),
  ].filter(Boolean);

  const images = [
    {
      id: "img1",
      prompt: content.imagePrompt || "cinematic portrait, dramatic lighting, moody atmosphere",
      url: heroUrl,
      source: classifySource(heroUrl),
      license: classifyLicense(heroUrl),
    },
  ];
  return { nodes, animations, images };
}

async function buildBusinessCard(style, content, brand, category) {
  const palette = style?.palette || {};
  const surface = palette.surface || "#ffffff";
  const primary = palette.primary || "#2563EB";
  const accent = palette.accent || "#0EA5E9";
  const text = palette.text || "#0f172a";
  const radius = style?.radius || 16;

  const nodes = [
    { id: "card", type: "shape", shape: "rectangle", x: 160, y: 320, width: 760, height: 420, radius, fill: surface },
    { id: "band", type: "shape", shape: "rectangle", x: 160, y: 320, width: 180, height: 420, radius, fill: `linear-gradient(135deg, ${primary}, ${accent})` },
    { id: "name", type: "text", content: content.title || "Juliana Silva", x: 380, y: 360, width: 460, height: 40, fontSize: 28, fontWeight: 800, color: text },
    { id: "role", type: "text", content: content.subtitle || "Business Consultant", x: 380, y: 400, width: 460, height: 30, fontSize: 18, fontWeight: 600, color: "rgba(15,23,42,0.72)" },
    { id: "contact1", type: "text", content: content.email || "hello@example.com", x: 380, y: 450, width: 420, height: 26, fontSize: 15, fontWeight: 500, color: "rgba(15,23,42,0.75)" },
    { id: "contact2", type: "text", content: content.phone || "+1 (202) 555-0123", x: 380, y: 480, width: 420, height: 26, fontSize: 15, fontWeight: 500, color: "rgba(15,23,42,0.75)" },
    { id: "logo", type: "text", content: content.author || "Brand", x: 200, y: 500, width: 120, height: 40, fontSize: 18, fontWeight: 800, color: "#ffffff" },
  ];

  const iconUrl = brandIconUrl(brand);
  if (iconUrl) {
    nodes.push({
      id: "brand_icon",
      type: "image",
      imageId: "brand_icon_img",
      x: 210,
      y: 360,
      width: 90,
      height: 90,
      fit: "contain",
      url: iconUrl,
    });
  }

  const animations = [
    hoverLift("card"),
    staggerAnim("band", 0),
    staggerAnim("name", 0.06),
    staggerAnim("role", 0.1),
    staggerAnim("contact1", 0.14),
    staggerAnim("contact2", 0.16),
    staggerAnim("logo", 0.2),
    brandIconAnim(iconUrl ? "brand_icon" : null, 0.2),
  ].filter(Boolean);
  const images = [];
  return { nodes, animations, images };
}

async function buildPodcastCover(style, content, brand, category) {
  const palette = style?.palette || {};
  const primary = palette.primary || "#A855F7";
  const accent = palette.accent || "#22D3EE";
  const text = palette.text || "#F8FAFC";
  const radius = style?.radius || 18;

  const heroUrl = await pickImage(content, brand, style, category);
  const nodes = [
    { id: "bg", type: "shape", shape: "rectangle", x: 0, y: 0, width: 1080, height: 1080, radius, fill: `linear-gradient(145deg, ${primary}, ${accent})` },
    { id: "cover", type: "image", imageId: "img1", x: 80, y: 140, width: 360, height: 360, fit: "cover", url: heroUrl },
    { id: "title", type: "text", content: content.title || "New One", x: 480, y: 170, width: 520, height: 140, fontSize: 96, fontWeight: 900, color: text },
    { id: "host", type: "text", content: content.author || "Adora Montminy", x: 480, y: 320, width: 520, height: 40, fontSize: 22, fontWeight: 700, color: "rgba(248,250,252,0.86)" },
    { id: "tag", type: "shape", shape: "rectangle", x: 480, y: 380, width: 180, height: 40, radius, fill: "rgba(255,255,255,0.2)" },
    { id: "tag_text", type: "text", content: content.kicker || "New Episode", x: 500, y: 388, width: 200, height: 26, fontSize: 15, fontWeight: 800, color: text },
    { id: "cta", type: "shape", shape: "rectangle", x: 480, y: 450, width: 220, height: 56, radius, fill: "rgba(255,255,255,0.16)" },
    { id: "cta_text", type: "text", content: content.ctaPrimary || "Listen Now ▶", x: 506, y: 466, width: 200, height: 26, fontSize: 16, fontWeight: 800, color: text },
  ];

  const iconUrl = brandIconUrl(brand);
  if (iconUrl) {
    nodes.push({
      id: "brand_icon",
      type: "image",
      imageId: "brand_icon_img",
      x: 860,
      y: 60,
      width: 80,
      height: 80,
      fit: "contain",
      url: iconUrl,
    });
  }

  const animations = [
    imageAnim("cover"),
    staggerAnim("title", 0),
    staggerAnim("host", 0.08),
    staggerAnim("tag", 0.12),
    staggerAnim("tag_text", 0.12),
    bounceAnim("cta", 0.16),
    staggerAnim("cta_text", 0.16),
    brandIconAnim(iconUrl ? "brand_icon" : null, 0.18),
  ].filter(Boolean);
  const images = [
    {
      id: "img1",
      prompt: content.imagePrompt || "music performer portrait, neon lighting, textured background",
      url: heroUrl,
      source: classifySource(heroUrl),
      license: classifyLicense(heroUrl),
    },
  ];
  return { nodes, animations, images };
}

function staggerAnim(nodeId, delay = 0) {
  return {
    id: `anim_${nodeId}`,
    nodeId,
    variants: {
      initial: { opacity: 0, y: 24 },
      animate: { opacity: 1, y: 0, transition: { duration: 0.6, ease: "easeOut", delay } },
      hover: { scale: 1.02 },
      tap: { scale: 0.98 },
    },
    triggers: ["onLoad", "onHover", "onClick", "onView"],
  };
}

function imageAnim(nodeId) {
  return {
    id: `anim_${nodeId}`,
    nodeId,
    variants: {
      initial: { opacity: 0.9, scale: 1.04 },
      animate: { opacity: 1, scale: 1, transition: { duration: 0.9, ease: "easeOut" } },
      hover: { scale: 1.02 },
      tap: { scale: 0.985 },
    },
    scroll: {
      inputRange: [0, 420],
      outputRange: { y: [0, -32], opacity: [1, 0.92] },
    },
    triggers: ["onLoad", "onHover", "onScroll"],
    tracks: [
      { property: "y", keyframes: [{ time: 0, value: 0 }, { time: 1200, value: -8, easing: "easeInOut" }] },
    ],
    playTimelineOnLoad: true,
    timelineLoop: true,
    timelineLoopCount: 0,
  };
}

function bounceAnim(nodeId, delay = 0) {
  return {
    id: `anim_${nodeId}`,
    nodeId,
    variants: {
      initial: { opacity: 0, scale: 0.8 },
      animate: { opacity: 1, scale: 1, transition: { duration: 0.5, ease: "easeOutBack", delay } },
      hover: { scale: 1.08 },
      tap: { scale: 0.94 },
    },
    triggers: ["onLoad", "onHover", "onClick"],
  };
}

function pulseAnim(nodeId, delay = 0) {
  return {
    id: `anim_${nodeId}`,
    nodeId,
    variants: {
      initial: { opacity: 0 },
      animate: { opacity: 1, transition: { duration: 0.6, delay } },
      hover: { scale: 1.05 },
    },
    tracks: [
      { property: "scale", keyframes: [{ time: 0, value: 1 }, { time: 1200, value: 1.04, easing: "easeInOut" }] },
    ],
    playTimelineOnLoad: true,
    timelineLoop: true,
    triggers: ["onLoad", "onHover"],
  };
}

function hoverLift(nodeId) {
  return {
    id: `anim_${nodeId}`,
    nodeId,
    variants: {
      initial: { opacity: 0, y: 16 },
      animate: { opacity: 1, y: 0, transition: { duration: 0.6, ease: "easeOut" } },
      hover: { y: -6, scale: 1.01, boxShadow: "0 18px 60px -32px rgba(0,0,0,0.25)" },
      tap: { scale: 0.99 },
    },
    triggers: ["onLoad", "onHover", "onClick"],
  };
}

async function pickImage(content = {}, brand = null, style = null, category = null) {
  if (content.imageUrl) return content.imageUrl;
  if (brand?.logos?.length) return brand.logos[0];
  const packImage = pickPackImage(category);
  if (packImage) return packImage;
  // Try Pexels if key present
  const pexels = await fetchPexelsImage(category || content.imagePrompt || style?.label || "design");
  if (pexels) return pexels;
  const styleKey = style?.id || "default";
  const map = {
    cinematic:
      "data:image/svg+xml;utf8,<svg xmlns='http://www.w3.org/2000/svg' width='1600' height='900'><defs><linearGradient id='g' x1='0%' y1='0%' x2='100%' y2='100%'><stop offset='0%' stop-color='%230b1224'/><stop offset='100%' stop-color='%230f172a'/></linearGradient></defs><rect width='1600' height='900' fill='url(%23g)'/></svg>",
    neonPop:
      "data:image/svg+xml;utf8,<svg xmlns='http://www.w3.org/2000/svg' width='1600' height='900'><defs><linearGradient id='g' x1='0%' y1='0%' x2='100%' y2='100%'><stop offset='0%' stop-color='%231e1b4b'/><stop offset='100%' stop-color='%238b5cf6'/></linearGradient></defs><rect width='1600' height='900' fill='url(%23g)'/></svg>",
    gradientLuxe:
      "data:image/svg+xml;utf8,<svg xmlns='http://www.w3.org/2000/svg' width='1600' height='900'><defs><linearGradient id='g' x1='0%' y1='0%' x2='100%' y2='100%'><stop offset='0%' stop-color='%230f172a'/><stop offset='100%' stop-color='%231f2937'/></linearGradient></defs><rect width='1600' height='900' fill='url(%23g)'/></svg>",
    corporateBlue:
      "data:image/svg+xml;utf8,<svg xmlns='http://www.w3.org/2000/svg' width='1600' height='900'><defs><linearGradient id='g' x1='0%' y1='0%' x2='100%' y2='100%'><stop offset='0%' stop-color='%23e5f1ff'/><stop offset='100%' stop-color='%23cbdaf5'/></linearGradient></defs><rect width='1600' height='900' fill='url(%23g)'/></svg>",
    fashionEditorial:
      "data:image/svg+xml;utf8,<svg xmlns='http://www.w3.org/2000/svg' width='1600' height='900'><defs><linearGradient id='g' x1='0%' y1='0%' x2='100%' y2='100%'><stop offset='0%' stop-color='%23111827'/><stop offset='100%' stop-color='%230b1224'/></linearGradient></defs><rect width='1600' height='900' fill='url(%23g)'/></svg>",
    techMinimal:
      "data:image/svg+xml;utf8,<svg xmlns='http://www.w3.org/2000/svg' width='1600' height='900'><defs><linearGradient id='g' x1='0%' y1='0%' x2='100%' y2='100%'><stop offset='0%' stop-color='%230f172a'/><stop offset='100%' stop-color='%23020617'/></linearGradient></defs><rect width='1600' height='900' fill='url(%23g)'/></svg>",
    default:
      "data:image/svg+xml;utf8,<svg xmlns='http://www.w3.org/2000/svg' width='1600' height='900'><defs><linearGradient id='g' x1='0%' y1='0%' x2='100%' y2='100%'><stop offset='0%' stop-color='%23256ad8'/><stop offset='100%' stop-color='%237354e8'/></linearGradient></defs><rect width='1600' height='900' fill='url(%23g)'/></svg>",
  };
  return map[styleKey] || map.default;
}

function brandIconUrl(brand) {
  if (!brand) return null;
  return brand.icon || brand.iconUrl || (Array.isArray(brand.logos) ? brand.logos[0] : null) || null;
}

function brandIconAnim(nodeId, delay = 0) {
  if (!nodeId) return null;
  return {
    id: `anim_${nodeId}`,
    nodeId,
    variants: {
      initial: { opacity: 0, scale: 0.9 },
      animate: { opacity: 1, scale: 1, transition: { duration: 0.55, ease: "easeOutBack", delay } },
      hover: { scale: 1.05 },
      tap: { scale: 0.95 },
    },
    triggers: ["onLoad", "onHover", "onClick"],
  };
}

function classifySource(url = "") {
  if (!url) return undefined;
  if (url.startsWith("/packs/") || url.startsWith("data:image")) return "pack";
  if (url.includes("unsplash.com") || url.includes("pexels.com")) return "stock";
  if (url.includes("openai") || url.includes("ai-") || url.includes("generated")) return "ai";
  if (url.startsWith("http")) return "external";
  return "upload";
}

function classifyLicense(url = "") {
  if (!url) return undefined;
  if (url.includes("unsplash.com") || url.includes("pexels.com")) return "cc0";
  if (url.startsWith("/packs/") || url.startsWith("data:image")) return "internal";
  return "unknown";
}
