export const templateCategories = [
  {
    id: "business_marketing",
    label: "Business & Marketing",
    children: [
      { id: "business_cards", label: "Business Cards" },
      { id: "flyers", label: "Flyers" },
      { id: "posters", label: "Posters" },
      { id: "brochures", label: "Brochures" },
      { id: "presentations", label: "Presentations" },
      { id: "pitch_decks", label: "Pitch Decks" },
      { id: "infographics", label: "Infographics" },
      { id: "case_studies", label: "Case Studies" },
      { id: "annual_reports", label: "Annual Reports" },
    ],
  },
  {
    id: "branding_identity",
    label: "Branding & Identity",
    children: [
      { id: "logos", label: "Logos" },
      { id: "brand_kits", label: "Brand Kits" },
      { id: "style_guides", label: "Style Guides" },
      { id: "packaging_mockups", label: "Packaging Mockups" },
    ],
  },
  {
    id: "social_media",
    label: "Social Media",
    children: [
      { id: "insta_posts", label: "Instagram Posts" },
      { id: "insta_stories", label: "Instagram Stories" },
      { id: "youtube_thumbnails", label: "YouTube Thumbnails" },
      { id: "tiktok_templates", label: "TikTok Templates" },
      { id: "carousel_posts", label: "Carousel Posts" },
      { id: "social_ads", label: "Social Ads" },
    ],
  },
  {
    id: "creator",
    label: "Creator & Influencer",
    children: [
      { id: "podcast_covers", label: "Podcast Covers" },
      { id: "youtube_kits", label: "YouTube Kits" },
      { id: "stream_overlays", label: "Stream Overlays" },
      { id: "vlog_titles", label: "Vlog Titles" },
    ],
  },
  {
    id: "ui_ux",
    label: "UI/UX Design",
    children: [
      { id: "web_pages", label: "Website Pages" },
      { id: "mobile_screens", label: "Mobile Screens" },
      { id: "dashboards", label: "Dashboards" },
      { id: "admin_panels", label: "Admin Panels" },
      { id: "components", label: "UI Components" },
      { id: "wireframes", label: "Wireframes" },
      { id: "motion_ui_kits", label: "Motion UI Kits" },
    ],
  },
  {
    id: "websites",
    label: "Websites",
    children: [
      { id: "saas_landing_pages", label: "SaaS Landing Pages" },
      { id: "portfolio_websites", label: "Portfolio Websites" },
      { id: "agency_websites", label: "Agency Websites" },
      { id: "ecommerce_landing_pages", label: "E-commerce Landing Pages" },
      { id: "coming_soon", label: "Coming Soon Pages" },
    ],
  },
  {
    id: "video",
    label: "Video Templates",
    children: [
      { id: "intros", label: "Intro Templates" },
      { id: "lower_thirds", label: "Lower Thirds" },
      { id: "transitions", label: "Transitions" },
      { id: "promo_videos", label: "Promo Videos" },
      { id: "title_animations", label: "Title Animations" },
    ],
  },
  {
    id: "animation",
    label: "Cartoon & Animation",
    children: [
      { id: "character_animations", label: "Character Animations" },
      { id: "animated_scenes", label: "Animated Scenes" },
      { id: "explainer_templates", label: "Explainer Templates" },
    ],
  },
  {
    id: "education",
    label: "Education",
    children: [
      { id: "worksheets", label: "Worksheets" },
      { id: "lesson_plans", label: "Lesson Plans" },
      { id: "certificates", label: "Certificates" },
      { id: "class_presentations", label: "Class Presentations" },
    ],
  },
  {
    id: "documents",
    label: "Documents",
    children: [
      { id: "resumes", label: "Resumes" },
      { id: "invoices", label: "Invoices" },
      { id: "checklists", label: "Checklists" },
      { id: "forms", label: "Forms" },
      { id: "calendars", label: "Calendars" },
    ],
  },
  {
    id: "events_lifestyle",
    label: "Events & Lifestyle",
    children: [
      { id: "weddings", label: "Weddings" },
      { id: "party_flyers", label: "Party Flyers" },
      { id: "menus", label: "Menus" },
      { id: "greeting_cards", label: "Greeting Cards" },
    ],
  },
  {
    id: "real_estate",
    label: "Real Estate",
    children: [
      { id: "property_flyers", label: "Property Flyers" },
      { id: "real_estate_presentations", label: "Listing Presentations" },
    ],
  },
  {
    id: "health_wellness",
    label: "Health & Wellness",
    children: [
      { id: "fitness_posters", label: "Fitness Posters" },
      { id: "meal_plans", label: "Meal Plans" },
      { id: "medical_brochures", label: "Medical Brochures" },
    ],
  },
  {
    id: "ecommerce",
    label: "E-commerce",
    children: [
      { id: "product_promos", label: "Product Promos" },
      { id: "amazon_images", label: "Amazon Listing Images" },
      { id: "shopify_banners", label: "Shopify Banners" },
    ],
  },
  {
    id: "ai_templates",
    label: "AI Templates",
    children: [
      { id: "ai_generated", label: "AI-Generated Templates" },
      { id: "ai_branding_kits", label: "AI Branding Kits" },
      { id: "ai_mockups", label: "AI Product Mockups" },
    ],
  },
];

export const templateTags = {
  styles: [
    "minimal",
    "modern",
    "clean",
    "bold",
    "colorful",
    "dark",
    "gradient",
    "luxury",
    "geometric",
    "retro",
    "vintage",
    "neon",
    "elegant",
  ],
  moods: [
    "soft",
    "cute",
    "corporate",
    "energetic",
    "professional",
    "playful",
    "futuristic",
    "cinematic",
    "calm",
  ],
  industries: [
    "real_estate",
    "fitness",
    "education",
    "medical",
    "agency",
    "ecommerce",
    "fashion",
    "crypto",
    "beauty",
    "restaurant",
  ],
  formats: ["social", "video", "poster", "print", "mobile", "desktop", "banner", "square", "a4"],
};

export const templateMetadataExample = {
  id: "template_0001",
  title: "Modern SaaS Landing Page",
  description: "A clean and minimal SaaS website hero section with animations.",
  category: "websites",
  subcategory: "saas_landing_pages",
  tags: ["minimal", "modern", "saas", "website"],
  styles: ["minimal", "gradient"],
  formats: ["desktop", "web"],
  thumbnailUrl: "/thumbnails/template_0001.png",
  animation: {
    hasMotion: true,
    motionTheme: "smoothMinimal",
    timelineCount: 1,
    scrollAnimations: true,
  },
  pages: 1,
  authorId: "user_123",
  createdAt: 1712342123,
  updatedAt: 1712342123,
  rating: 4.8,
  usageCount: 302,
  aiGenerated: true,
};
