export const createNode = (overrides = {}) => ({
  id: overrides.id || crypto.randomUUID?.() || `node_${Date.now()}`,
  type: overrides.type || "frame",
  name: overrides.name || "Node",
  x: overrides.x ?? 0,
  y: overrides.y ?? 0,
  width: overrides.width ?? 100,
  height: overrides.height ?? 100,
  rotation: overrides.rotation ?? 0,
  children: overrides.children || [],
  parent: overrides.parent ?? null,
  locked: overrides.locked ?? false,
  hidden: overrides.hidden ?? false,
  opacity: overrides.opacity ?? 1,
  fill: overrides.fill,
  stroke: overrides.stroke,
  src: overrides.src,
  clipPath: overrides.clipPath,
});
