import { nanoid } from "nanoid";

const makeId = () => (typeof crypto !== "undefined" && crypto.randomUUID ? crypto.randomUUID() : nanoid());

export function blueprintToTemplate(blueprint = {}, metadata = {}) {
  const frameId = makeId();
  const width = metadata.width || 1440;
  const height = metadata.height || 900;
  const nodes = {};

  const rootFrame = {
    id: frameId,
    type: "frame",
    name: blueprint.name || metadata.name || "AI Template",
    x: 0,
    y: 0,
    width,
    height,
    children: [],
    layout: { enabled: true, direction: "vertical", spacing: 24, padding: { top: 48, right: 48, bottom: 48, left: 48 }, alignment: "start" },
    constraints: { horizontal: "left", vertical: "top" },
  };

  (blueprint.sections || []).forEach((section) => {
    const sectionId = makeId();
    const childIds = [];
    const layout = {
      enabled: true,
      direction: section.layout?.direction || "vertical",
      spacing: section.layout?.gap || 16,
      padding: {
        top: section.layout?.padding || 24,
        right: section.layout?.padding || 24,
        bottom: section.layout?.padding || 24,
        left: section.layout?.padding || 24,
      },
      alignment: section.layout?.alignment || "start",
    };

    (section.components || []).forEach((comp) => {
      const id = makeId();
      const base = {
        id,
        name: comp.role || comp.type,
        children: [],
        parent: sectionId,
        x: 0,
        y: 0,
        width: comp.width || 320,
        height: comp.height || 64,
        constraints: { horizontal: "left", vertical: "top" },
      };
      if (comp.type === "text") {
        nodes[id] = {
          ...base,
          type: "text",
          text: comp.content || comp.props?.text || "Placeholder",
          fontSize: comp.role === "heading" ? 36 : 18,
          fill: "#0f172a",
        };
      } else if (comp.type === "button") {
        nodes[id] = {
          ...base,
          type: "frame",
          width: comp.width || 180,
          height: comp.height || 48,
          background: "#6366f1",
          layout: { enabled: true, direction: "horizontal", spacing: 8, padding: { top: 10, right: 16, bottom: 10, left: 16 }, alignment: "center" },
          children: [],
        };
        const labelId = makeId();
        nodes[labelId] = {
          id: labelId,
          type: "text",
          name: "Button Label",
          text: comp.props?.text || "Get Started",
          fontSize: 16,
          fill: "#ffffff",
          parent: id,
          x: 0,
          y: 0,
          constraints: { horizontal: "center", vertical: "center" },
        };
        nodes[id].children.push(labelId);
      } else if (comp.type === "image") {
        nodes[id] = {
          ...base,
          type: "image",
          width: comp.width || 480,
          height: comp.height || 320,
          src: comp.props?.src || comp.url || "https://placehold.co/800x600",
        };
      } else {
        nodes[id] = { ...base, type: comp.type || "rect", fill: "#e5e7eb", height: comp.height || 80 };
      }
      childIds.push(id);
    });

    nodes[sectionId] = {
      id: sectionId,
      type: section.type || "frame",
      name: section.name || "Section",
      parent: frameId,
      children: childIds,
      layout,
      constraints: { horizontal: "left", vertical: "top" },
      width: section.width || width - 96,
      height: section.height || 400,
    };
    rootFrame.children.push(sectionId);
  });

  nodes[frameId] = rootFrame;

  return {
    id: makeId(),
    name: blueprint.name || metadata.name || "AI Template",
    description: blueprint.description || metadata.description || "Generated by Dropple AI",
    frame: { width, height, background: "#ffffff" },
    nodes: Object.values(nodes),
  };
}
