export type TemplateCategory = 'popular' | 'business' | 'enterprise' | 'ecommerce' | 'education';

export type TemplateComponentKey =
    | 'BusinessCard'
    | 'BusinessTemplate'
    | 'EcommerceTemplate'
    | 'EditableInstagramPost'
    | 'EducationTemplate'
    | 'EnterpriseTemplate'
    | 'Flyer'
    | 'InstagramPost'
    | 'InstagramStory'
    | 'Invoice'
    | 'PresentationSlide'
    | 'Resume'
    | 'SocialMediaTemplate'
    | 'VisualTemplate';

import { TEMPLATE_ARTBOARDS } from './json';

export type TemplateMetaRecord = {
    slug: string;
    title: string;
    category: TemplateCategory;
    componentKey: TemplateComponentKey;
    componentProps?: Record<string, unknown>;
    defaultData?: Record<string, unknown>;
    tags?: string[];
    thumbnail?: string;
};

export const TEMPLATE_META: TemplateMetaRecord[] = [
    {
        slug: 'business-card-modern',
        title: 'Business Card – Modern',
        category: 'business',
        componentKey: 'BusinessCard',
        componentProps: { variant: 'modern' },
        tags: ['card', 'identity'],
    },
    {
        slug: 'business-card-classic',
        title: 'Business Card – Classic',
        category: 'business',
        componentKey: 'BusinessCard',
        componentProps: { variant: 'classic' },
    },
    {
        slug: 'business-card-creative',
        title: 'Business Card – Creative',
        category: 'business',
        componentKey: 'BusinessCard',
        componentProps: { variant: 'creative' },
    },
    {
        slug: 'business-card-1',
        title: 'Business Card – Professional',
        category: 'business',
        componentKey: 'BusinessCard',
        componentProps: { variant: 'modern' },
        tags: ['business card', 'professional', 'networking'],
        defaultData: TEMPLATE_ARTBOARDS['business-card-1'],
    },
    {
        slug: 'business-proposal',
        title: 'Business Proposal',
        category: 'business',
        componentKey: 'BusinessTemplate',
        componentProps: { variant: 'proposal' },
        tags: ['document'],
    },
    {
        slug: 'business-letterhead',
        title: 'Letterhead',
        category: 'business',
        componentKey: 'BusinessTemplate',
        componentProps: { variant: 'letterhead' },
    },
    {
        slug: 'business-quote',
        title: 'Price Quotation',
        category: 'business',
        componentKey: 'BusinessTemplate',
        componentProps: { variant: 'quote' },
    },
    {
        slug: 'business-receipt',
        title: 'Payment Receipt',
        category: 'business',
        componentKey: 'BusinessTemplate',
        componentProps: { variant: 'receipt' },
    },
    {
        slug: 'resume-professional',
        title: 'Resume – Professional',
        category: 'business',
        componentKey: 'Resume',
        componentProps: { variant: 'professional' },
        tags: ['resume'],
    },
    {
        slug: 'resume-creative',
        title: 'Resume – Creative',
        category: 'business',
        componentKey: 'Resume',
        componentProps: { variant: 'creative' },
    },
    {
        slug: 'resume-minimal',
        title: 'Resume – Minimal',
        category: 'business',
        componentKey: 'Resume',
        componentProps: { variant: 'minimal' },
    },
    {
        slug: 'invoice-standard',
        title: 'Invoice – Standard',
        category: 'business',
        componentKey: 'Invoice',
        componentProps: { variant: 'standard' },
    },
    {
        slug: 'invoice-modern',
        title: 'Invoice – Modern',
        category: 'business',
        componentKey: 'Invoice',
        componentProps: { variant: 'modern' },
    },
    {
        slug: 'invoice-simple',
        title: 'Invoice – Simple',
        category: 'business',
        componentKey: 'Invoice',
        componentProps: { variant: 'simple' },
    },
    {
        slug: 'flyer-event',
        title: 'Flyer – Event',
        category: 'business',
        componentKey: 'Flyer',
        componentProps: { variant: 'event' },
        tags: ['flyer', 'event'],
    },
    {
        slug: 'flyer-sale',
        title: 'Flyer – Sale',
        category: 'business',
        componentKey: 'Flyer',
        componentProps: { variant: 'sale' },
    },
    {
        slug: 'flyer-service',
        title: 'Flyer – Service',
        category: 'business',
        componentKey: 'Flyer',
        componentProps: { variant: 'service' },
    },
    {
        slug: 'flyer-modern-1',
        title: 'Flyer – Bold & Colorful',
        category: 'business',
        componentKey: 'Flyer',
        componentProps: { variant: 'event' },
        tags: ['flyer', 'marketing', 'colorful'],
        defaultData: TEMPLATE_ARTBOARDS['flyer-modern-1'],
    },
    {
        slug: 'ecommerce-product-card',
        title: 'Product Card',
        category: 'ecommerce',
        componentKey: 'EcommerceTemplate',
        componentProps: { variant: 'product-card' },
    },
    {
        slug: 'ecommerce-product-showcase',
        title: 'Product Showcase',
        category: 'ecommerce',
        componentKey: 'EcommerceTemplate',
        componentProps: { variant: 'product-showcase' },
    },
    {
        slug: 'ecommerce-sale-banner',
        title: 'Sale Banner',
        category: 'ecommerce',
        componentKey: 'EcommerceTemplate',
        componentProps: { variant: 'sale-banner' },
    },
    {
        slug: 'ecommerce-email-receipt',
        title: 'Email Receipt',
        category: 'ecommerce',
        componentKey: 'EcommerceTemplate',
        componentProps: { variant: 'email-receipt' },
    },
    {
        slug: 'ecommerce-shipping-update',
        title: 'Shipping Update',
        category: 'ecommerce',
        componentKey: 'EcommerceTemplate',
        componentProps: { variant: 'shipping-update' },
    },
    {
        slug: 'ecommerce-pricing-table',
        title: 'Pricing Table',
        category: 'ecommerce',
        componentKey: 'EcommerceTemplate',
        componentProps: { variant: 'pricing-table' },
    },
    {
        slug: 'ecommerce-product-review',
        title: 'Product Review',
        category: 'ecommerce',
        componentKey: 'EcommerceTemplate',
        componentProps: { variant: 'product-review' },
    },
    {
        slug: 'enterprise-dashboard',
        title: 'Analytics Dashboard',
        category: 'enterprise',
        componentKey: 'EnterpriseTemplate',
        componentProps: { variant: 'dashboard' },
    },
    {
        slug: 'enterprise-analytics',
        title: 'Analytics Report',
        category: 'enterprise',
        componentKey: 'EnterpriseTemplate',
        componentProps: { variant: 'analytics' },
    },
    {
        slug: 'enterprise-summary',
        title: 'Executive Summary',
        category: 'enterprise',
        componentKey: 'EnterpriseTemplate',
        componentProps: { variant: 'executive-summary' },
    },
    {
        slug: 'enterprise-kpi',
        title: 'KPI Dashboard',
        category: 'enterprise',
        componentKey: 'EnterpriseTemplate',
        componentProps: { variant: 'kpi-dashboard' },
    },
    {
        slug: 'enterprise-swot',
        title: 'SWOT Analysis',
        category: 'enterprise',
        componentKey: 'EnterpriseTemplate',
        componentProps: { variant: 'swot' },
    },
    {
        slug: 'enterprise-roadmap',
        title: 'Product Roadmap',
        category: 'enterprise',
        componentKey: 'EnterpriseTemplate',
        componentProps: { variant: 'roadmap' },
    },
    {
        slug: 'presentation-title',
        title: 'Slide – Title',
        category: 'enterprise',
        componentKey: 'PresentationSlide',
        componentProps: { variant: 'title' },
    },
    {
        slug: 'presentation-content',
        title: 'Slide – Content',
        category: 'enterprise',
        componentKey: 'PresentationSlide',
        componentProps: { variant: 'content' },
    },
    {
        slug: 'presentation-data',
        title: 'Slide – Data',
        category: 'enterprise',
        componentKey: 'PresentationSlide',
        componentProps: { variant: 'data' },
    },
    {
        slug: 'building-facade',
        title: 'Building Facade',
        category: 'enterprise',
        componentKey: 'VisualTemplate',
        componentProps: { variant: 'facade' },
        tags: ['architecture', 'design'],
        thumbnail: 'https://images.unsplash.com/photo-1649767146802-1d5baa586638?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixlib=rb-4.1.0&q=80&w=400',
    },
    {
        slug: 'structural-engineering',
        title: 'Structural Engineering',
        category: 'enterprise',
        componentKey: 'VisualTemplate',
        componentProps: { variant: 'engineering' },
        tags: ['architecture', 'infrastructure'],
        thumbnail: 'https://images.unsplash.com/photo-1759397573675-5e1c3e0ef41a?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixlib=rb-4.1.0&q=80&w=400',
    },
    {
        slug: 'sustainable-design',
        title: 'Sustainable Design',
        category: 'enterprise',
        componentKey: 'VisualTemplate',
        componentProps: { variant: 'sustainable' },
        tags: ['architecture', 'sustainability'],
        thumbnail: 'https://images.unsplash.com/photo-1627141234469-24711efb373c?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixlib=rb-4.1.0&q=80&w=400',
    },
    {
        slug: 'renovation-project',
        title: 'Renovation Project',
        category: 'enterprise',
        componentKey: 'VisualTemplate',
        componentProps: { variant: 'renovation' },
        tags: ['architecture', 'before-after'],
        thumbnail: 'https://images.unsplash.com/photo-1600210491892-03d54c0aaf87?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixlib=rb-4.1.0&q=80&w=400',
    },
    {
        slug: 'presentation-slide-1',
        title: 'Presentation Slide – Modern',
        category: 'enterprise',
        componentKey: 'PresentationSlide',
        componentProps: { variant: 'content' },
        tags: ['presentation', 'business', 'modern'],
        defaultData: TEMPLATE_ARTBOARDS['presentation-slide-1'],
    },
    {
        slug: 'education-certificate',
        title: 'Certificate of Completion',
        category: 'education',
        componentKey: 'EducationTemplate',
        componentProps: { variant: 'certificate' },
    },
    {
        slug: 'education-award',
        title: 'Achievement Award',
        category: 'education',
        componentKey: 'EducationTemplate',
        componentProps: { variant: 'award' },
    },
    {
        slug: 'education-lesson-plan',
        title: 'Lesson Plan',
        category: 'education',
        componentKey: 'EducationTemplate',
        componentProps: { variant: 'lesson-plan' },
    },
    {
        slug: 'education-report-card',
        title: 'Progress Report',
        category: 'education',
        componentKey: 'EducationTemplate',
        componentProps: { variant: 'report-card' },
    },
    {
        slug: 'education-study-guide',
        title: 'Study Guide',
        category: 'education',
        componentKey: 'EducationTemplate',
        componentProps: { variant: 'study-guide' },
    },
    {
        slug: 'education-class-schedule',
        title: 'Class Schedule',
        category: 'education',
        componentKey: 'EducationTemplate',
        componentProps: { variant: 'class-schedule' },
    },
    {
        slug: 'editable-instagram-fitness',
        title: 'Editable Instagram – Fitness',
        category: 'popular',
        componentKey: 'EditableInstagramPost',
        componentProps: { variant: 'fitness' },
        tags: ['instagram', 'fitness'],
        thumbnail: 'https://images.unsplash.com/photo-1618688862225-ac941a9da58f?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixlib=rb-4.1.0&q=80&w=400',
    },
    {
        slug: 'editable-instagram-food',
        title: 'Editable Instagram – Food',
        category: 'popular',
        componentKey: 'EditableInstagramPost',
        componentProps: { variant: 'food' },
        tags: ['instagram', 'food'],
    },
    {
        slug: 'instagram-post-fitness',
        title: 'Instagram Post – Fitness',
        category: 'popular',
        componentKey: 'InstagramPost',
        componentProps: { variant: 'fitness' },
    },
    {
        slug: 'instagram-post-food',
        title: 'Instagram Post – Food',
        category: 'popular',
        componentKey: 'InstagramPost',
        componentProps: { variant: 'food' },
    },
    {
        slug: 'social-instagram-post-1',
        title: 'Instagram Post – Minimalist',
        category: 'popular',
        componentKey: 'InstagramPost',
        componentProps: { variant: 'minimal' },
        tags: ['instagram', 'social media', 'minimalist'],
        defaultData: TEMPLATE_ARTBOARDS['social-instagram-post-1'],
    },
    {
        slug: 'instagram-story-promo',
        title: 'Instagram Story – Promo',
        category: 'popular',
        componentKey: 'InstagramStory',
        componentProps: { variant: 'promo' },
    },
    {
        slug: 'social-story-1',
        title: 'Instagram Story – Gradient',
        category: 'popular',
        componentKey: 'InstagramStory',
        componentProps: { variant: 'promo' },
        tags: ['instagram', 'story', 'gradient'],
        defaultData: TEMPLATE_ARTBOARDS['social-story-1'],
    },
    {
        slug: 'social-youtube-thumbnail',
        title: 'YouTube Thumbnail',
        category: 'popular',
        componentKey: 'SocialMediaTemplate',
        componentProps: { variant: 'youtube-thumbnail' },
        tags: ['youtube'],
    },
    {
        slug: 'social-twitter-post',
        title: 'Twitter Post',
        category: 'popular',
        componentKey: 'SocialMediaTemplate',
        componentProps: { variant: 'twitter-post' },
        tags: ['twitter'],
    },
    {
        slug: 'social-linkedin-banner',
        title: 'LinkedIn Banner',
        category: 'popular',
        componentKey: 'SocialMediaTemplate',
        componentProps: { variant: 'linkedin-banner' },
        tags: ['linkedin'],
    },
    {
        slug: 'social-tiktok-cover',
        title: 'TikTok Cover',
        category: 'popular',
        componentKey: 'SocialMediaTemplate',
        componentProps: { variant: 'tiktok-cover' },
        tags: ['tiktok'],
    },
];
